// Collective Path Planner - adversarial input suite.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
//
// Every fabric in this file is SYNTHETIC: generated by the tests, never measured
// on a device. The suite proves that hostile, malformed, contradictory and
// degenerate input is refused deterministically and never produces a partial or
// unsafe plan.
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

#include "cpath/dsl.hpp"
#include "cpath/explain.hpp"
#include "cpath/planner.hpp"
#include "fixtures.hpp"
#include "test_framework.hpp"

namespace {

using cpath::ErrorCode;
using cpath::PlanningOutcome;
using cpath::PlanningRequest;

bool is_input_failure(const cpath::Status& status) {
  return cpath::category_of(status.code()) == cpath::ErrorCategory::kInput;
}

std::string replace_at(std::string text, std::size_t index, char value) {
  text[index] = value;
  return text;
}

// A request whose topology generation can be overridden, used for staleness
// proofs.
std::string generation_text(std::uint64_t topology_generation) {
  return std::string(
             "cpath-request 1\n"
             "plan-generation 1\n"
             "topology-generation ") +
         std::to_string(topology_generation) +
         "\n"
         "failure-domain-generation 2\n"
         "capacity-evidence-generation 3\n"
         "policy-generation 1\n"
         "\n"
         "[collective]\n"
         "id=c0 kind=ring\n"
         "\n"
         "[groups]\n"
         "g0 level=0 pattern=ring members=p0,p1,p2\n"
         "\n"
         "[domains]\n"
         "S0 kind=site\n"
         "R0 kind=rack parent=S0\n"
         "R1 kind=rack parent=S0\n"
         "\n"
         "[nodes]\n"
         "n0 site=S0 rack=R0 host=H0 device=0 tier=LEAF\n"
         "n1 site=S0 rack=R1 host=H1 device=0 tier=LEAF\n"
         "n2 site=S0 rack=R0 host=H2 device=0 tier=LEAF\n"
         "sp site=S0 pod=P0 rack=CORE host=SP device=0 tier=SPINE\n"
         "\n"
         "[edges]\n"
         "l0 from=n0 to=sp capacity=10000 latency=100 tier=LEAF domain=R0 evidence=synthetic\n"
         "l1 from=sp to=n0 capacity=10000 latency=100 tier=LEAF domain=R0 evidence=synthetic\n"
         "l2 from=n1 to=sp capacity=10000 latency=100 tier=LEAF domain=R1 evidence=synthetic\n"
         "l3 from=sp to=n1 capacity=10000 latency=100 tier=LEAF domain=R1 evidence=synthetic\n"
         "l4 from=n2 to=sp capacity=10000 latency=100 tier=LEAF domain=R0 evidence=synthetic\n"
         "l5 from=sp to=n2 capacity=10000 latency=100 tier=LEAF domain=R0 evidence=synthetic\n"
         "\n"
         "[bindings]\n"
         "p0 node=n0\n"
         "p1 node=n1\n"
         "p2 node=n2\n"
         "\n"
         "[policy]\n"
         "max-hops=4\n"
         "paths-per-logical-edge=1\n";
}

struct Expectation {
  const char* name;
  std::string text;
  ErrorCode code;
};

}  // namespace

CPATH_TEST(adversarial, dsl_truncation_at_every_offset_is_never_fatal) {
  const std::string full = cpath_test::four_node_ring_text();
  auto complete = cpath::parse_request_text(full);
  CPATH_REQUIRE(complete.has_value());

  std::size_t accepted = 0;
  std::size_t accepted_with_same_digest = 0;
  std::size_t refused = 0;
  for (std::size_t length = 0; length < full.size(); ++length) {
    const std::string_view prefix(full.data(), length);
    auto request = cpath::parse_request_text(prefix);
    if (request.has_value()) {
      // A line-oriented format cannot promise that a truncation is always
      // malformed: cutting a member list short yields a different but perfectly
      // well-formed collective. What must hold is that whatever was accepted is
      // a complete, self-consistent request that either plans or is denied.
      ++accepted;
      if (request.value().canonical_digest == complete.value().canonical_digest) {
        ++accepted_with_same_digest;
      }
      CPATH_CHECK(request.value().validate().is_ok());
      const PlanningOutcome outcome = cpath::plan_collective(request.value());
      CPATH_CHECK(outcome.ok() || !outcome.plan.has_value());
      if (outcome.ok()) {
        CPATH_CHECK(cpath::validate_plan(*outcome.plan, request.value()).is_ok());
      }
    } else {
      ++refused;
      CPATH_CHECK(is_input_failure(request.status()));
    }
  }
  CPATH_CHECK_EQ(accepted + refused, full.size());
  // The complete document and its newline-less prefix must be accepted.
  CPATH_CHECK(accepted >= 2u);
}

CPATH_TEST(adversarial, dsl_single_byte_mutation_is_bounded) {
  const std::string full = cpath_test::four_node_ring_text();
  const char substitutions[] = {'\0', ' ', '=', '[', ']', '#', '\n', '9', 'z', ':'};
  std::size_t accepted = 0;
  std::size_t refused = 0;
  for (std::size_t index = 0; index < full.size(); ++index) {
    for (const char substitution : substitutions) {
      const std::string mutated = replace_at(full, index, substitution);
      auto first = cpath::parse_request_text(mutated);
      auto second = cpath::parse_request_text(mutated);
      // A hostile input is answered deterministically, never differently twice.
      CPATH_CHECK_EQ(first.has_value(), second.has_value());
      if (!first.has_value()) {
        CPATH_CHECK(first.status() == second.status());
        ++refused;
        continue;
      }
      CPATH_REQUIRE(second.has_value());
      CPATH_CHECK(first.value().canonical_digest == second.value().canonical_digest);
      ++accepted;
      // Anything a mutation produces must still validate and either plan or be
      // refused with a denial that carries no plan.
      CPATH_CHECK(first.value().validate().is_ok());
      const PlanningOutcome outcome = cpath::plan_collective(first.value());
      CPATH_CHECK(outcome.ok() || !outcome.plan.has_value());
      if (outcome.ok()) {
        CPATH_CHECK(cpath::validate_plan(*outcome.plan, first.value()).is_ok());
      }
    }
  }
  CPATH_CHECK(accepted + refused == full.size() * sizeof(substitutions));
}

CPATH_TEST(adversarial, dsl_rejects_hostile_documents_with_specific_codes) {
  const std::vector<Expectation> cases = {
      {"empty", "", ErrorCode::kEmptyInput},
      {"no banner", "plan-generation 1\n", ErrorCode::kMissingRequiredField},
      {"wrong banner", "cpath-request 2\nx\n", ErrorCode::kUnsupportedFormatVersion},
      {"unknown header", "cpath-request 1\nrouter-generation 5\n", ErrorCode::kUnknownKeyword},
      {"header without value", "cpath-request 1\nplan-generation\n", ErrorCode::kInvalidSyntax},
      {"unknown section", "cpath-request 1\n[peers]\nn0 from=n1\n", ErrorCode::kUnknownKeyword},
      {"malformed section", "cpath-request 1\n[nodes\nn0 tier=LEAF\n", ErrorCode::kInvalidSyntax},
      {"empty section name", "cpath-request 1\n[]\n", ErrorCode::kInvalidSyntax},
      {"repeated section", "cpath-request 1\n[nodes]\n[nodes]\n", ErrorCode::kDuplicateIdentifier},
      {"unknown node key", "cpath-request 1\n[nodes]\nn0 weight=3\n", ErrorCode::kUnknownKeyword},
      {"missing required key",
       "cpath-request 1\n[edges]\ne0 to=n1 capacity=1\n",
       ErrorCode::kMissingRequiredField},
      {"non-numeric number",
       "cpath-request 1\nplan-generation abc\n",
       ErrorCode::kMalformedNumber},
      {"negative number",
       "cpath-request 1\nplan-generation -1\n",
       ErrorCode::kMalformedNumber},
      {"leading zero",
       "cpath-request 1\nplan-generation 007\n",
       ErrorCode::kMalformedNumber},
      {"number overflow",
       "cpath-request 1\nplan-generation 99999999999999999999999\n",
       ErrorCode::kValueOutOfRange},
      {"key without equals",
       "cpath-request 1\n[policy]\nmax-hops 4\n",
       ErrorCode::kInvalidSyntax},
      {"repeated key on one line",
       "cpath-request 1\n[policy]\nmax-hops=4 max-hops=5\n",
       ErrorCode::kDuplicateIdentifier},
      {"empty value",
       "cpath-request 1\n[policy]\nmax-hops=\n",
       ErrorCode::kInvalidSyntax},
      {"invalid identifier character",
       "cpath-request 1\n[nodes]\nn 0 tier=LEAF\n",
       ErrorCode::kInvalidSyntax},
      {"trailing garbage after a valid document",
       std::string(cpath_test::minimal_ring_text()) + "unexpected trailing content\n",
       ErrorCode::kInvalidSyntax},
      {"boolean out of range",
       "cpath-request 1\n[nodes]\nn0 eligible=2\n",
       ErrorCode::kValueOutOfRange},
  };

  for (const Expectation& expectation : cases) {
    auto spec = cpath::parse_request_spec(expectation.text);
    if (spec.has_value()) {
      // A case that parses must still be refused by the builder.
      auto built = cpath::build_request(std::move(spec.value()));
      CPATH_CHECK(!built.has_value());
      if (!built.has_value()) {
        CPATH_CHECK_EQ(static_cast<int>(built.status().code()), static_cast<int>(expectation.code));
      }
      continue;
    }
    if (static_cast<int>(spec.status().code()) != static_cast<int>(expectation.code)) {
      CPATH_FAIL(std::string("case '") + expectation.name + "' produced " +
                 cpath::code_symbol(spec.status().code()) + " but " +
                 cpath::code_symbol(expectation.code) + " was expected");
    }
  }
}

CPATH_TEST(adversarial, dsl_rejects_oversized_line_and_input) {
  std::string long_line = "cpath-request 1\nplan-generation 1\n# ";
  long_line.append(cpath::kMaxTextLineBytes + 16u, 'x');
  long_line.push_back('\n');
  auto spec = cpath::parse_request_spec(long_line);
  CPATH_REQUIRE(!spec.has_value());
  CPATH_CHECK_EQ(static_cast<int>(spec.status().code()), static_cast<int>(ErrorCode::kLineTooLong));

  std::string oversized("cpath-request 1\n# ");
  oversized.append(cpath::kMaxInputBytes + 1u, 'y');
  auto large = cpath::parse_request_spec(oversized);
  CPATH_REQUIRE(!large.has_value());
  CPATH_CHECK_EQ(static_cast<int>(large.status().code()), static_cast<int>(ErrorCode::kInputTooLarge));
}

CPATH_TEST(adversarial, dsl_rejection_is_reproducible) {
  const std::string hostile = "cpath-request 1\n[nodes]\nn0 tier=\n";
  auto first = cpath::parse_request_spec(hostile);
  auto second = cpath::parse_request_spec(hostile);
  CPATH_REQUIRE(!first.has_value());
  CPATH_REQUIRE(!second.has_value());
  CPATH_CHECK(first.status() == second.status());
}

CPATH_TEST(adversarial, plan_encoding_survives_truncation_and_mutation) {
  auto request = cpath::parse_request_text(cpath_test::four_node_ring_text());
  CPATH_REQUIRE(request.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  CPATH_REQUIRE(outcome.ok());
  const std::vector<std::uint8_t> encoded = outcome.plan->encode();

  auto whole = cpath::Plan::decode(encoded);
  CPATH_REQUIRE(whole.has_value());
  CPATH_CHECK(whole.value().body_digest() == outcome.plan->body_digest());

  for (std::size_t length = 0; length < encoded.size(); ++length) {
    const std::span<const std::uint8_t> prefix(encoded.data(), length);
    auto decoded = cpath::Plan::decode(prefix);
    CPATH_CHECK(!decoded.has_value());
  }

  std::size_t rejected = 0;
  for (std::size_t index = 0; index < encoded.size(); ++index) {
    std::vector<std::uint8_t> mutated = encoded;
    mutated[index] = static_cast<std::uint8_t>(mutated[index] ^ 0xFFu);
    auto decoded = cpath::Plan::decode(mutated);
    if (!decoded.has_value()) {
      ++rejected;
    } else {
      // A mutation may still decode; if it does, the decode must be internally
      // consistent and re-encode to the mutated bytes.
      CPATH_CHECK(decoded.value().encode() == mutated);
    }
  }
  CPATH_CHECK(rejected > 0u);
}

CPATH_TEST(adversarial, trailing_bytes_after_a_plan_are_refused) {
  auto request = cpath::parse_request_text(cpath_test::four_node_ring_text());
  CPATH_REQUIRE(request.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  CPATH_REQUIRE(outcome.ok());
  std::vector<std::uint8_t> encoded = outcome.plan->encode();
  encoded.push_back(0u);
  auto decoded = cpath::Plan::decode(encoded);
  CPATH_REQUIRE(!decoded.has_value());
  CPATH_CHECK_EQ(static_cast<int>(decoded.status().code()), static_cast<int>(ErrorCode::kTrailingGarbage));
}

CPATH_TEST(adversarial, disconnected_fabric_is_refused_without_a_partial_plan) {
  const std::string text =
      "cpath-request 1\n"
      "plan-generation 1\n"
      "topology-generation 1\n"
      "failure-domain-generation 1\n"
      "capacity-evidence-generation 1\n"
      "policy-generation 1\n"
      "\n"
      "[collective]\n"
      "id=c0 kind=ring\n"
      "\n"
      "[groups]\n"
      "g0 level=0 pattern=ring members=p0,p1\n"
      "\n"
      "[nodes]\n"
      "n0 site=S0 rack=R0 host=H0 device=0 tier=LEAF\n"
      "n1 site=S0 rack=R0 host=H1 device=0 tier=LEAF\n"
      "\n"
      "[edges]\n"
      "e0 from=n9 to=n1 capacity=1000 latency=10 tier=LEAF evidence=synthetic\n"
      "\n"
      "[bindings]\n"
      "p0 node=n0\n"
      "p1 node=n1\n";
  auto spec = cpath::parse_request_spec(text);
  CPATH_REQUIRE(spec.has_value());
  auto request = cpath::build_request(std::move(spec.value()));
  CPATH_REQUIRE(!request.has_value());
  CPATH_CHECK_EQ(static_cast<int>(request.status().code()), static_cast<int>(ErrorCode::kUnknownReference));
}

CPATH_TEST(adversarial, asymmetric_fabric_forces_a_denial_rather_than_a_reversed_path) {
  cpath_test::SyntheticParams params;
  params.participants = 4;
  params.spine_count = 1;
  params.rack_count = 2;
  params.asymmetric_percent = 100;  // only leaf -> spine edges exist
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());

  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  // One direction of every leaf/spine pair is missing, so some logical edge must
  // fail rather than silently reusing the reverse direction.
  CPATH_CHECK(!outcome.ok());
  CPATH_CHECK(!outcome.plan.has_value());
  CPATH_CHECK(!outcome.denials.empty());
  if (!outcome.denials.empty()) {
    CPATH_CHECK(outcome.denials.front().code == ErrorCode::kNoPath ||
                outcome.denials.front().code == ErrorCode::kHopLimitExceeded ||
                outcome.denials.front().code == ErrorCode::kEndpointIneligible ||
                outcome.denials.front().code == ErrorCode::kNodeForbidden);
  }
}

CPATH_TEST(adversarial, saturated_capacity_is_not_capacity) {
  cpath_test::SyntheticParams params;
  params.participants = 4;
  params.spine_count = 1;
  params.rack_count = 2;
  params.demand_mbps = 1000;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  // Every edge is fully reserved by an adjacent authority.
  for (cpath::Edge& edge : spec.fabric.edges) {
    edge.reserved_mbps = edge.capacity_mbps;
  }
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  CPATH_CHECK(!outcome.ok());
  CPATH_CHECK(!outcome.plan.has_value());
}

CPATH_TEST(adversarial, reserved_above_capacity_is_rejected_at_build_time) {
  cpath_test::SyntheticParams params;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  spec.fabric.edges.front().reserved_mbps = spec.fabric.edges.front().capacity_mbps + 1u;
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(!request.has_value());
  CPATH_CHECK_EQ(static_cast<int>(request.status().code()),
                 static_cast<int>(ErrorCode::kInconsistentMetadata));
}

CPATH_TEST(adversarial, cyclic_failure_domain_hierarchy_is_rejected) {
  cpath_test::SyntheticParams params;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  // Close a cycle over the site domain.
  for (cpath::FailureDomain& domain : spec.fabric.failure_domains) {
    if (domain.id.value() == "S0") {
      domain.parent = cpath::FailureDomainId{"R0"};
      domain.kind = cpath::DomainKind::kPod;
    }
  }
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(!request.has_value());
  CPATH_CHECK_EQ(static_cast<int>(request.status().code()),
                 static_cast<int>(ErrorCode::kInconsistentMetadata));
}

CPATH_TEST(adversarial, duplicate_identifiers_are_rejected) {
  cpath_test::SyntheticParams params;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  spec.fabric.nodes.push_back(spec.fabric.nodes.front());
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(!request.has_value());
  CPATH_CHECK_EQ(static_cast<int>(request.status().code()),
                 static_cast<int>(ErrorCode::kDuplicateIdentifier));
}

CPATH_TEST(adversarial, duplicate_physical_links_are_kept_and_used_for_diversity) {
  cpath_test::SyntheticParams params;
  params.participants = 2;
  params.spine_count = 1;
  params.rack_count = 1;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  // A second physical link in each direction. They are distinct edges with
  // distinct identities, so they are a real source of path diversity rather
  // than a duplicate that should be collapsed.
  const std::size_t original = spec.fabric.edges.size();
  for (std::size_t index = 0; index < original; ++index) {
    cpath::Edge duplicate = spec.fabric.edges[index];
    duplicate.id = cpath::EdgeId{duplicate.id.value() + "d"};
    duplicate.latency_micros += 20;
    spec.fabric.edges.push_back(duplicate);
  }
  spec.policy.paths_per_logical_edge = 2;
  spec.policy.disjointness = cpath::Disjointness::kEdge;
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());
  CPATH_CHECK_EQ(request.value().fabric.edge_count(), original * 2u);
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  CPATH_CHECK(outcome.ok());
  if (outcome.ok()) {
    CPATH_CHECK_EQ(outcome.plan->paths.size(), 4u);
    CPATH_CHECK(cpath::validate_plan(*outcome.plan, request.value()).is_ok());
  }
}

CPATH_TEST(adversarial, zero_capacity_edges_are_unusable_by_default) {
  cpath_test::SyntheticParams params;
  params.participants = 4;
  params.spine_count = 1;
  params.rack_count = 2;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  for (cpath::Edge& edge : spec.fabric.edges) {
    edge.capacity_mbps = 0;
    edge.reserved_mbps = 0;
  }
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  CPATH_CHECK(!outcome.ok());
  CPATH_CHECK(!outcome.plan.has_value());
  if (!outcome.denials.empty()) {
    CPATH_CHECK(outcome.denials.front().code == ErrorCode::kEdgeHasNoVerifiedCapacity ||
                outcome.denials.front().code == ErrorCode::kNoPath);
  }
}

CPATH_TEST(adversarial, unknown_evidence_is_labelled_and_never_upgraded) {
  cpath_test::SyntheticParams params;
  params.participants = 4;
  params.spine_count = 1;
  params.rack_count = 2;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  for (cpath::Edge& edge : spec.fabric.edges) {
    edge.evidence = cpath::EvidenceClass::kUnknown;
  }
  spec.policy.allow_unverified_capacity = false;
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  if (outcome.ok()) {
    CPATH_CHECK_EQ(static_cast<int>(outcome.plan->weakest_evidence),
                   static_cast<int>(cpath::EvidenceClass::kUnknown));
  } else {
    CPATH_CHECK(!outcome.plan.has_value());
  }

  // Requiring measured evidence must refuse a fabric that has none.
  cpath::RequestSpec measured = cpath_test::make_ring_spec(params);
  for (cpath::Edge& edge : measured.fabric.edges) {
    edge.evidence = cpath::EvidenceClass::kUnknown;
  }
  measured.policy.evidence = cpath::EvidenceRequirement::kMeasured;
  auto measured_request = cpath::build_request(std::move(measured));
  CPATH_REQUIRE(measured_request.has_value());
  const PlanningOutcome refused = cpath::plan_collective(measured_request.value());
  CPATH_CHECK(!refused.ok());
  CPATH_CHECK(!refused.plan.has_value());
}

namespace {

// Two edge-disjoint three-hop routes between the same endpoints, both of which
// transit pod PA. Edge-disjointness is satisfiable; pod independence is not.
cpath::RequestSpec shared_transit_domain_spec() {
  cpath::RequestSpec spec;
  spec.fabric.topology_generation = cpath::TopologyGeneration{1};
  spec.fabric.failure_domain_generation = cpath::FailureDomainGeneration{1};
  spec.fabric.capacity_evidence_generation = cpath::CapacityEvidenceGeneration{1};
  spec.policy.generation = cpath::PolicyGeneration{1};
  spec.plan_generation = cpath::CollectivePlanGeneration{1};

  const auto domain = [&](const char* id, cpath::DomainKind kind, const char* parent) {
    cpath::FailureDomain record;
    record.id = cpath::FailureDomainId{id};
    record.kind = kind;
    if (parent != nullptr) {
      record.parent = cpath::FailureDomainId{parent};
    }
    spec.fabric.failure_domains.push_back(record);
  };
  domain("S0", cpath::DomainKind::kSite, nullptr);
  domain("PA", cpath::DomainKind::kPod, "S0");
  domain("PB", cpath::DomainKind::kPod, "S0");

  for (const char* id : {"n0", "n1", "u1", "u2", "v1", "v2"}) {
    cpath::Node node;
    node.id = cpath::NodeId{id};
    node.tier = cpath::TierId{"LEAF"};
    spec.fabric.nodes.push_back(node);
  }
  const auto link = [&](const char* id, const char* from, const char* to, const char* failure_domain) {
    cpath::Edge edge;
    edge.id = cpath::EdgeId{id};
    edge.from = cpath::NodeId{from};
    edge.to = cpath::NodeId{to};
    edge.capacity_mbps = 10000;
    edge.latency_micros = 100;
    edge.tier = cpath::TierId{"LEAF"};
    edge.failure_domain = cpath::FailureDomainId{failure_domain};
    edge.evidence = cpath::EvidenceClass::kSynthetic;
    spec.fabric.edges.push_back(edge);
  };
  // Two transit chains with identical domain structure. The transit links
  // belong only to their own chain, so no route can mix them: every
  // edge-disjoint pair necessarily transits the same pod and is therefore not
  // failure-domain independent.
  link("a0", "n0", "u1", "PA");
  link("a1", "u1", "v1", "PA");
  link("a2", "v1", "n1", "PB");
  link("b0", "n0", "u2", "PA");
  link("b1", "u2", "v2", "PA");
  link("b2", "v2", "n1", "PB");
  link("ra0", "n1", "v1", "PB");
  link("ra1", "v1", "u1", "PA");
  link("ra2", "u1", "n0", "PA");
  link("rb0", "n1", "v2", "PB");
  link("rb1", "v2", "u2", "PA");
  link("rb2", "u2", "n0", "PA");

  cpath::GroupSpec group;
  group.id = cpath::GroupId{"g0"};
  group.level = 0;
  group.pattern = cpath::GroupPattern::kRing;
  group.members = {cpath::ParticipantId{"p0"}, cpath::ParticipantId{"p1"}};
  spec.collective.id = cpath::CollectiveId{"c0"};
  spec.collective.kind = cpath::CollectiveKind::kRing;
  spec.collective.groups.push_back(group);

  cpath::EndpointBinding first;
  first.participant = cpath::ParticipantId{"p0"};
  first.node = cpath::NodeId{"n0"};
  spec.bindings.push_back(first);
  cpath::EndpointBinding second;
  second.participant = cpath::ParticipantId{"p1"};
  second.node = cpath::NodeId{"n1"};
  spec.bindings.push_back(second);

  spec.policy.max_hops = 4;
  spec.policy.paths_per_logical_edge = 2;
  spec.policy.disjointness = cpath::Disjointness::kEdge;
  spec.policy.domain_diversity = cpath::DomainDiversity::kRequired;
  spec.policy.domain_diversity_level = cpath::DomainKind::kPod;
  return spec;
}

}  // namespace

CPATH_TEST(adversarial, node_disjoint_sibling_paths_are_satisfiable_and_verified) {
  // Sibling paths share their source and their destination by construction; node
  // disjointness is about the nodes in between. The two transit chains below have
  // disjoint interiors, so a node-disjoint mapping exists and must be found,
  // emitted and independently re-validated.
  cpath::RequestSpec spec = shared_transit_domain_spec();
  spec.policy.domain_diversity = cpath::DomainDiversity::kNone;
  spec.policy.disjointness = cpath::Disjointness::kNode;
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  CPATH_CHECK(outcome.ok());
  CPATH_REQUIRE(outcome.ok());
  CPATH_CHECK(cpath::validate_plan(*outcome.plan, request.value()).is_ok());
  CPATH_CHECK_EQ(outcome.plan->paths.size(), 4u);

  // Sibling paths of one logical edge must share no interior node.
  for (std::size_t left = 0; left < outcome.plan->paths.size(); ++left) {
    for (std::size_t right = left + 1u; right < outcome.plan->paths.size(); ++right) {
      const cpath::PathPlan& first = outcome.plan->paths[left];
      const cpath::PathPlan& second = outcome.plan->paths[right];
      if (!(first.logical_edge == second.logical_edge)) {
        continue;
      }
      for (std::size_t i = 0; i + 1u < first.hops.size(); ++i) {
        for (std::size_t j = 0; j + 1u < second.hops.size(); ++j) {
          CPATH_CHECK(!(first.hops[i].to == second.hops[j].to));
        }
      }
    }
  }
}

CPATH_TEST(adversarial, edge_disjoint_routes_that_share_a_pod_are_refused) {
  auto request = cpath::build_request(shared_transit_domain_spec());
  CPATH_REQUIRE(request.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  CPATH_CHECK(!outcome.ok());
  CPATH_CHECK(!outcome.plan.has_value());
  CPATH_REQUIRE(!outcome.denials.empty());
  CPATH_CHECK_EQ(static_cast<int>(outcome.denials.front().code),
                 static_cast<int>(ErrorCode::kDomainDiversityUnsatisfiable));
}

CPATH_TEST(adversarial, genuinely_diverse_routes_are_accepted) {
  cpath::RequestSpec spec = shared_transit_domain_spec();
  // Move the second route's transit links into a third pod, so the two routes
  // really are independent at pod level.
  cpath::FailureDomain third;
  third.id = cpath::FailureDomainId{"PC"};
  third.kind = cpath::DomainKind::kPod;
  third.parent = cpath::FailureDomainId{"S0"};
  spec.fabric.failure_domains.push_back(third);
  for (cpath::Edge& edge : spec.fabric.edges) {
    if (edge.id.value() == "b1" || edge.id.value() == "rb1") {
      edge.failure_domain = cpath::FailureDomainId{"PC"};
    }
  }
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  CPATH_CHECK(outcome.ok());
  if (outcome.ok()) {
    CPATH_CHECK(cpath::validate_plan(*outcome.plan, request.value()).is_ok());
    CPATH_CHECK_EQ(outcome.plan->paths.size(), 4u);
  }
}

CPATH_TEST(adversarial, stale_topology_generation_invalidates_a_previous_plan) {
  auto older = cpath::parse_request_text(generation_text(41));
  CPATH_REQUIRE(older.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(older.value());
  CPATH_REQUIRE(outcome.ok());

  auto newer = cpath::parse_request_text(generation_text(42));
  CPATH_REQUIRE(newer.has_value());
  CPATH_CHECK(!(newer.value().canonical_digest == older.value().canonical_digest));
  CPATH_CHECK_EQ(static_cast<int>(cpath::assess_freshness(*outcome.plan, newer.value().current_bindings())),
                 static_cast<int>(cpath::PlanFreshness::kStaleTopology));
  const cpath::Status validation = cpath::validate_plan(*outcome.plan, newer.value());
  CPATH_CHECK(!validation.is_ok());
  CPATH_CHECK(validation.code() == ErrorCode::kPlanInputMismatch ||
              validation.code() == ErrorCode::kStalePlanGeneration ||
              validation.code() == ErrorCode::kGenerationRegression);
}

CPATH_TEST(adversarial, search_budget_exhaustion_is_reported_as_indeterminate) {
  cpath_test::SyntheticParams params;
  params.participants = 8;
  params.spine_count = 2;
  params.rack_count = 4;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  // Starve every budget the planner has, so it can neither enumerate nor search.
  spec.policy.max_search_expansions = 1;
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());

  cpath::PlannerLimits limits;
  limits.max_enumeration_steps = 1;
  limits.max_total_enumeration_steps = 1;
  const PlanningOutcome outcome = cpath::plan_collective(request.value(), limits);

  CPATH_CHECK(!outcome.ok());
  CPATH_CHECK(!outcome.plan.has_value());
  CPATH_REQUIRE(!outcome.denials.empty());
  // The result is INDETERMINATE. It must never claim that no mapping exists:
  // failing to find a solution is not proof that there is none.
  CPATH_CHECK(outcome.indeterminate());
  CPATH_CHECK(!outcome.proven_infeasible());
  CPATH_CHECK_EQ(static_cast<int>(outcome.primary_code()),
                 static_cast<int>(ErrorCode::kSearchBudgetExceeded));
  CPATH_CHECK_EQ(static_cast<int>(outcome.primary_kind()),
                 static_cast<int>(cpath::DenialKind::kSearchLimitReached));
  CPATH_CHECK(outcome.search_expansions <= 1u);
  CPATH_CHECK(outcome.enumeration_steps <= 1u);
}

CPATH_TEST(adversarial, enumeration_exhaustion_never_withdraws_a_feasible_plan) {
  // Running out of enumeration budget costs PROOF strength, never feasibility:
  // the heuristic pool still finds a mapping, and the outcome says that the
  // result is not proven optimal.
  cpath_test::SyntheticParams params;
  params.participants = 4;
  params.spine_count = 2;
  params.rack_count = 2;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());

  cpath::PlannerLimits limits;
  limits.max_enumeration_steps = 1;
  limits.max_total_enumeration_steps = 1;
  const PlanningOutcome starved = cpath::plan_collective(request.value(), limits);
  CPATH_CHECK(starved.ok());
  if (starved.ok()) {
    CPATH_CHECK(cpath::validate_plan(*starved.plan, request.value()).is_ok());
    CPATH_CHECK(!starved.optimal);
  }

  // The same request with a full budget is proven optimal and must agree.
  const PlanningOutcome full = cpath::plan_collective(request.value());
  CPATH_CHECK(full.ok());
  if (full.ok() && starved.ok()) {
    CPATH_CHECK(full.plan->stats.total_cost <= starved.plan->stats.total_cost);
  }
}

CPATH_TEST(adversarial, huge_latency_saturates_instead_of_wrapping) {
  cpath_test::SyntheticParams params;
  params.participants = 4;
  params.spine_count = 1;
  params.rack_count = 2;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  for (cpath::Edge& edge : spec.fabric.edges) {
    edge.latency_micros = cpath::kMaxLatencyMicros;
  }
  spec.policy.latency_weight_milli = cpath::kMaxScoringWeightMilli;
  spec.policy.max_path_cost = cpath::kCostCeiling;
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  if (outcome.ok()) {
    for (const cpath::PathPlan& path : outcome.plan->paths) {
      CPATH_CHECK(path.cost <= cpath::kCostCeiling);
    }
    CPATH_CHECK(outcome.plan->stats.total_cost <= cpath::kCostCeiling);
    CPATH_CHECK(cpath::validate_plan(*outcome.plan, request.value()).is_ok());
  } else {
    CPATH_CHECK(!outcome.plan.has_value());
  }
}

CPATH_TEST(adversarial, unbound_participant_is_a_denial_not_a_default) {
  cpath_test::SyntheticParams params;
  params.participants = 4;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  spec.bindings.pop_back();
  auto request = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(request.has_value());
  const PlanningOutcome outcome = cpath::plan_collective(request.value());
  CPATH_CHECK(!outcome.ok());
  CPATH_REQUIRE(!outcome.denials.empty());
  CPATH_CHECK_EQ(static_cast<int>(outcome.denials.front().code),
                 static_cast<int>(ErrorCode::kUnboundParticipant));
  CPATH_CHECK_EQ(static_cast<int>(outcome.denials.front().conflict),
                 static_cast<int>(cpath::ConflictKind::kMissingBinding));
  CPATH_CHECK(!outcome.plan.has_value());
}

CPATH_TEST(adversarial, boundary_policy_values_are_validated) {
  cpath_test::SyntheticParams params;
  cpath::RequestSpec spec = cpath_test::make_ring_spec(params);
  spec.policy.max_hops = 0;
  auto zero_hops = cpath::build_request(spec);
  CPATH_REQUIRE(!zero_hops.has_value());
  CPATH_CHECK_EQ(static_cast<int>(zero_hops.status().code()), static_cast<int>(ErrorCode::kValueOutOfRange));

  spec.policy = cpath::Policy{};
  spec.policy.generation = cpath::PolicyGeneration{1};
  spec.policy.paths_per_logical_edge = cpath::kMaxPathsPerLogicalEdge + 1u;
  auto too_many = cpath::build_request(std::move(spec));
  CPATH_REQUIRE(!too_many.has_value());
  CPATH_CHECK_EQ(static_cast<int>(too_many.status().code()),
                 static_cast<int>(ErrorCode::kPathCountUnsupported));
}

int main(int argc, char** argv) { return cpath_test::Registry::instance().run(argc, argv); }
