// Collective Path Planner - end-to-end integration proofs through the public API.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
//
// Every fabric used here is SYNTHETIC: generated by this test or by the shared
// fixture layer, never measured on a device. Nothing in this file reaches into
// planner internals: the only entry points used are the frozen public headers,
// and every promise is re-derived from the returned plan and the request it
// claims to have used.
#include <algorithm>
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include "cpath/collective.hpp"
#include "cpath/digest.hpp"
#include "cpath/dsl.hpp"
#include "cpath/explain.hpp"
#include "cpath/fabric.hpp"
#include "cpath/ids.hpp"
#include "cpath/plan.hpp"
#include "cpath/planner.hpp"
#include "cpath/policy.hpp"
#include "cpath/request.hpp"
#include "cpath/status.hpp"
#include "fixtures.hpp"
#include "test_framework.hpp"

namespace cp = cpath;
namespace ct = cpath_test;

namespace {

std::string code_of(const cp::Status& status) { return std::string(cp::code_symbol(status.code())); }
std::string symbol_of(cp::ErrorCode code) { return std::string(cp::code_symbol(code)); }

template <class T>
T require_value(const cp::Result<T>& result, const std::string& context) {
  if (!result.has_value()) {
    CPATH_FAIL(context + ": unexpected failure " + result.status().to_string());
  }
  return result.value();
}

void check_rejected(const cp::Status& status, cp::ErrorCode expected, const std::string& context) {
  if (status.code() != expected) {
    ct::record_failure(__FILE__, __LINE__, context + ": expected " + symbol_of(expected) + " but got " +
                                                 code_of(status) + " (" + status.detail() + ")");
  }
}

// --- synthetic model helpers ----------------------------------------------

cp::Node make_node(const std::string& id, const std::string& rack, const std::string& tier) {
  cp::Node node;
  node.id = cp::NodeId{id};
  node.placement.supplied = true;
  node.placement.site = "S0";
  node.placement.rack = rack;
  node.placement.host = id;
  node.tier = cp::TierId{tier};
  return node;
}

cp::Edge make_edge(const std::string& id, const std::string& from, const std::string& to, const std::string& tier,
                   const std::string& domain, std::uint64_t latency_micros, std::uint64_t capacity_mbps) {
  cp::Edge edge;
  edge.id = cp::EdgeId{id};
  edge.from = cp::NodeId{from};
  edge.to = cp::NodeId{to};
  edge.capacity_mbps = capacity_mbps;
  edge.latency_micros = latency_micros;
  edge.tier = cp::TierId{tier};
  edge.failure_domain = cp::FailureDomainId{domain};
  edge.evidence = cp::EvidenceClass::kSynthetic;
  return edge;
}

cp::FailureDomain make_domain(const std::string& id, cp::DomainKind kind, const std::string& parent) {
  cp::FailureDomain domain;
  domain.id = cp::FailureDomainId{id};
  domain.kind = kind;
  if (!parent.empty()) {
    domain.parent = cp::FailureDomainId{parent};
  }
  return domain;
}

// Replaces the fixture fabric with a two-plane topology for the same four
// participant leaves, keeping the parsed collective, bindings, generations and
// policy untouched. Every logical edge is then carried by two three-hop paths
// n{i} -> A{i}{k} -> B{k} -> n{j}, one per plane, which cross disjoint access and
// core nodes. Each leaf link owns its own failure domain, so a plane is
// identified by its core domain alone; with shared_core_domain both planes end
// in one core domain and rack-level independence between siblings is genuinely
// impossible. SYNTHETIC.
cp::RequestSpec two_plane_ring(const cp::RequestSpec& base, bool shared_core_domain) {
  cp::RequestSpec spec = base;
  spec.fabric.failure_domains.clear();
  spec.fabric.nodes.clear();
  spec.fabric.edges.clear();

  spec.fabric.failure_domains.push_back(make_domain("S0", cp::DomainKind::kSite, std::string()));
  spec.fabric.failure_domains.push_back(
      make_domain(shared_core_domain ? "CORE" : "CORE0", cp::DomainKind::kRack, "S0"));
  spec.fabric.failure_domains.push_back(make_domain("CORE1", cp::DomainKind::kRack, "S0"));

  const char* leaves[4] = {"n0", "n1", "n2", "n3"};
  for (std::size_t index = 0; index < 4u; ++index) {
    const std::string leaf = leaves[index];
    spec.fabric.nodes.push_back(make_node(leaf, "R" + std::to_string(index), "LEAF"));
  }
  for (std::size_t plane = 0; plane < 2u; ++plane) {
    spec.fabric.nodes.push_back(make_node("B" + std::to_string(plane), "CORE", "SPINE"));
    for (std::size_t index = 0; index < 4u; ++index) {
      const std::string leaf = leaves[index];
      const std::string suffix = leaf + std::to_string(plane);
      const std::string access = "A" + suffix;
      const std::string core = "B" + std::to_string(plane);
      spec.fabric.nodes.push_back(make_node(access, "CORE", "LEAF"));
      spec.fabric.failure_domains.push_back(make_domain("DL" + suffix, cp::DomainKind::kRack, "S0"));
      spec.fabric.edges.push_back(
          make_edge("la-" + suffix, leaf, access, "LEAF", "DL" + suffix, 100u, 25000u));
      spec.fabric.edges.push_back(
          make_edge("ac-" + suffix, access, core, "SPINE", shared_core_domain ? "CORE" : "CORE" + std::to_string(plane),
                    100u, 25000u));
    }
  }
  for (std::size_t plane = 0; plane < 2u; ++plane) {
    const std::string core = "B" + std::to_string(plane);
    for (std::size_t index = 0; index < 4u; ++index) {
      const std::string leaf = leaves[index];
      const std::string suffix = leaf + std::to_string(plane);
      spec.fabric.failure_domains.push_back(make_domain("DZ" + suffix, cp::DomainKind::kRack, "S0"));
      spec.fabric.edges.push_back(
          make_edge("cz-" + suffix, core, leaf, "LEAF", "DZ" + suffix, 100u, 25000u));
    }
  }
  return spec;
}

// Re-derives every invariant the planner promises directly from the returned
// plan and the request it claims to have used. Nothing here trusts the planner.
void check_plan_invariants(const cp::Plan& plan, const cp::PlanningRequest& request, const std::string& label) {
  const cp::Policy& policy = request.policy;
  const cp::FabricGraph& fabric = request.fabric;
  const cp::Collective& collective = request.collective;

  const cp::Status validated = cp::validate_plan(plan, request);
  if (!validated.is_ok()) {
    ct::record_failure(__FILE__, __LINE__, label + ": validate_plan refused the plan: " + validated.to_string());
  }
  if (!(plan.id.value() == request.canonical_digest)) {
    ct::record_failure(__FILE__, __LINE__, label + ": plan identity is not the canonical request digest");
  }
  if (!(plan.input_digest == request.canonical_digest)) {
    ct::record_failure(__FILE__, __LINE__, label + ": plan input digest does not match the request");
  }
  if (!(plan.generation == request.plan_generation)) {
    ct::record_failure(__FILE__, __LINE__, label + ": plan generation does not match the request");
  }
  if (!(plan.bindings == request.current_bindings())) {
    ct::record_failure(__FILE__, __LINE__, label + ": plan does not bind the current generations");
  }
  if (!(plan.collective == collective.id) || !(plan.kind == collective.kind)) {
    ct::record_failure(__FILE__, __LINE__, label + ": plan names a different collective");
  }
  CPATH_CHECK_EQ(plan.stage_count, collective.stage_count);
  CPATH_CHECK_EQ(plan.stages.size(), static_cast<std::size_t>(collective.stage_count));
  CPATH_CHECK_EQ(plan.stats.logical_edge_count, collective.logical_edges.size());
  CPATH_CHECK_EQ(plan.stats.path_count, plan.paths.size());
  std::size_t total_hops = 0;
  for (const cp::PathPlan& path : plan.paths) {
    total_hops += path.hops.size();
  }
  CPATH_CHECK_EQ(plan.stats.hop_count, total_hops);

  std::vector<std::vector<const cp::PathPlan*>> per_logical(collective.logical_edges.size());
  for (const cp::PathPlan& path : plan.paths) {
    if (path.logical_edge.value() < 1u || path.logical_edge.value() > collective.logical_edges.size()) {
      ct::record_failure(__FILE__, __LINE__, label + ": plan path names an unknown logical edge");
      continue;
    }
    const std::size_t edge_index = static_cast<std::size_t>(path.logical_edge.value() - 1u);
    const cp::LogicalEdge& logical = collective.logical_edges[edge_index];
    per_logical[edge_index].push_back(&path);

    CPATH_CHECK(path.src == logical.src);
    CPATH_CHECK(path.dst == logical.dst);
    CPATH_CHECK_EQ(path.stage, collective.logical_edge_stage[edge_index]);

    const cp::EndpointBinding* source = request.find_binding(logical.src);
    const cp::EndpointBinding* target = request.find_binding(logical.dst);
    if (source == nullptr || target == nullptr) {
      ct::record_failure(__FILE__, __LINE__, label + ": plan path uses an unbound participant");
      continue;
    }
    // The endpoint nodes differ in every fabric used here, so a mapping always
    // has at least one physical hop.
    if (path.hops.empty()) {
      ct::record_failure(__FILE__, __LINE__, label + ": plan path has no hops between distinct endpoints");
      continue;
    }
    CPATH_CHECK(path.hops.size() <= policy.max_hops);
    CPATH_CHECK(path.hops.front().from == source->node);
    CPATH_CHECK(path.hops.back().to == target->node);

    for (std::size_t hop_index = 0; hop_index < path.hops.size(); ++hop_index) {
      const cp::Hop& hop = path.hops[hop_index];
      const cp::Edge* edge = fabric.find_edge(hop.edge);
      if (edge == nullptr) {
        ct::record_failure(__FILE__, __LINE__, label + ": plan hop references an edge outside the fabric");
        continue;
      }
      CPATH_CHECK(edge->from == hop.from);
      CPATH_CHECK(edge->to == hop.to);
      CPATH_CHECK(edge->eligible);
      CPATH_CHECK(edge->capacity_mbps > 0u);
      if (hop_index + 1u < path.hops.size()) {
        CPATH_CHECK(path.hops[hop_index + 1u].from == hop.to);
      }
      CPATH_CHECK(std::find(policy.forbidden_nodes.begin(), policy.forbidden_nodes.end(), hop.from) ==
                  policy.forbidden_nodes.end());
      CPATH_CHECK(std::find(policy.forbidden_nodes.begin(), policy.forbidden_nodes.end(), hop.to) ==
                  policy.forbidden_nodes.end());
      if (edge->tier.valid()) {
        CPATH_CHECK(!std::binary_search(policy.forbidden_tiers.begin(), policy.forbidden_tiers.end(), edge->tier));
        if (!policy.allowed_path_tiers.empty()) {
          CPATH_CHECK(std::binary_search(policy.allowed_path_tiers.begin(), policy.allowed_path_tiers.end(),
                                         edge->tier));
        }
      }
      for (const cp::FailureDomainId& forbidden : policy.forbidden_failure_domains) {
        CPATH_CHECK(!fabric.domain_contains(forbidden, edge->failure_domain));
      }
    }
  }

  for (std::size_t index = 0; index < per_logical.size(); ++index) {
    CPATH_CHECK_EQ(per_logical[index].size(), policy.paths_per_logical_edge);
    for (std::size_t left = 0; left < per_logical[index].size(); ++left) {
      for (std::size_t right = left + 1u; right < per_logical[index].size(); ++right) {
        const cp::PathPlan& lhs = *per_logical[index][left];
        const cp::PathPlan& rhs = *per_logical[index][right];
        if (policy.disjointness != cp::Disjointness::kNone) {
          for (const cp::Hop& left_hop : lhs.hops) {
            for (const cp::Hop& right_hop : rhs.hops) {
              CPATH_CHECK(!(left_hop.edge == right_hop.edge));
            }
          }
        }
        if (policy.disjointness == cp::Disjointness::kNode) {
          for (const cp::Hop& left_hop : lhs.hops) {
            for (const cp::Hop& right_hop : rhs.hops) {
              CPATH_CHECK(!(left_hop.to == right_hop.to));
            }
          }
        }
        if (policy.domain_diversity == cp::DomainDiversity::kRequired) {
          // The planner's promise: no failure domain at the configured level is
          // shared by two sibling paths.
          CPATH_CHECK(!lhs.domain_signature.empty());
          CPATH_CHECK(!rhs.domain_signature.empty());
          for (const cp::FailureDomainId& domain : lhs.domain_signature) {
            CPATH_CHECK(!std::binary_search(rhs.domain_signature.begin(), rhs.domain_signature.end(), domain));
          }
        }
      }
    }
  }
}

// The interior nodes a path crosses, i.e. everything but its endpoints. Two
// siblings with disjoint interiors cannot be taken down by one shared fabric
// failure, which is what rack independence means physically.
std::vector<std::string> interior_nodes(const cp::PathPlan& path) {
  std::vector<std::string> nodes;
  for (std::size_t index = 0; index + 1u < path.hops.size(); ++index) {
    nodes.push_back(path.hops[index].to.value());
  }
  std::sort(nodes.begin(), nodes.end());
  nodes.erase(std::unique(nodes.begin(), nodes.end()), nodes.end());
  return nodes;
}

// A deliberately small structural JSON check: it proves the rendering is
// balanced and quote-correct without pretending to be a full JSON parser.
bool json_is_balanced(const std::string& text, std::string& error) {
  std::vector<char> stack;
  bool in_string = false;
  bool escaped = false;
  for (const char ch : text) {
    if (in_string) {
      if (escaped) {
        escaped = false;
      } else if (ch == '\\') {
        escaped = true;
      } else if (ch == '"') {
        in_string = false;
      } else if (static_cast<unsigned char>(ch) < 0x20u) {
        error = "raw control character inside a JSON string";
        return false;
      }
      continue;
    }
    if (ch == '"') {
      in_string = true;
    } else if (ch == '{' || ch == '[') {
      stack.push_back(ch);
    } else if (ch == '}' || ch == ']') {
      if (stack.empty()) {
        error = "closing bracket without an opener";
        return false;
      }
      const char opener = stack.back();
      stack.pop_back();
      if ((ch == '}' && opener != '{') || (ch == ']' && opener != '[')) {
        error = "mismatched bracket";
        return false;
      }
    }
  }
  if (in_string) {
    error = "unterminated string";
    return false;
  }
  if (!stack.empty()) {
    error = "unclosed bracket";
    return false;
  }
  return true;
}

void check_json(const std::string& text, const std::string& needle, const std::string& label) {
  std::string error;
  if (!json_is_balanced(text, error)) {
    ct::record_failure(__FILE__, __LINE__, label + ": rendered JSON is not balanced: " + error);
  }
  if (text.size() < 2u || text.front() != '{' || text.back() != '}') {
    ct::record_failure(__FILE__, __LINE__, label + ": rendered JSON is not a single object");
  }
  if (text.find(needle) == std::string::npos) {
    ct::record_failure(__FILE__, __LINE__, label + ": rendered JSON does not contain " + needle);
  }
}

// Eight participants spread over four racks, two spines, one spine-to-spine link
// pair. SYNTHETIC.
cp::RequestSpec eight_participant_spec() {
  ct::SyntheticParams params;
  params.seed = 1;
  params.participants = 8;
  params.spine_count = 2;
  params.rack_count = 4;
  params.capacity_mbps = 25000;
  params.latency_micros = 100;
  params.demand_mbps = 1000;
  return ct::make_ring_spec(params);
}

}  // namespace

// ===========================================================================
// The smallest end-to-end path
// ===========================================================================

CPATH_TEST(IntegrationPipeline, minimal_ring_end_to_end) {
  const cp::PlanningRequest request =
      require_value(cp::parse_request_text(ct::minimal_ring_text()), "minimal_ring_text");  // SYNTHETIC fabric
  const cp::PlanningOutcome outcome = cp::plan_collective(request);
  if (!outcome.ok()) {
    CPATH_FAIL("minimal ring was refused: " + ct::describe_outcome(outcome));
  }
  const cp::Plan& plan = *outcome.plan;
  CPATH_CHECK(cp::validate_plan(plan, request).is_ok());
  CPATH_CHECK_EQ(plan.paths.size(), std::size_t{2});
  CPATH_CHECK_EQ(plan.stats.logical_edge_count, std::size_t{2});
  CPATH_CHECK_EQ(plan.stats.hop_count, std::size_t{2});
  CPATH_CHECK_EQ(plan.id.value().hex(), request.canonical_digest.hex());

  // The audit rendering contains every chosen route verbatim.
  const std::string plan_text = cp::encode_plan_text(plan);
  CPATH_CHECK(plan_text.find(plan.id.value().hex()) != std::string::npos);
  for (const cp::PathPlan& path : plan.paths) {
    if (path.hops.empty()) {
      CPATH_FAIL("minimal ring path has no hops");
    }
    for (const cp::Hop& hop : path.hops) {
      const std::string route = "hop " + hop.edge.value() + " " + hop.from.value() + " -> " + hop.to.value();
      if (plan_text.find(route) == std::string::npos) {
        ct::record_failure(__FILE__, __LINE__, "encode_plan_text omits the chosen route " + route);
      }
    }
  }
  CPATH_CHECK(plan_text.find("collective c0 kind ring") != std::string::npos);

  // The machine rendering is structurally sound and identifies the plan.
  const std::string json = cp::render_plan_json(plan);
  check_json(json, plan.id.value().hex(), "render_plan_json");
  check_json(cp::render_outcome_json(outcome), plan.id.value().hex(), "render_outcome_json");
  CPATH_CHECK(json.find("\"paths\":[") != std::string::npos);
  CPATH_CHECK(cp::explain_plan(plan, &request).find("all plan invariants hold for these inputs") !=
              std::string::npos);

  // Storage round trip: byte identical, stable body digest.
  const std::vector<std::uint8_t> bytes = plan.encode();
  CPATH_CHECK(!bytes.empty());
  const cp::Plan decoded = require_value(cp::Plan::decode(bytes), "plan decode");
  CPATH_CHECK(decoded.encode() == bytes);
  CPATH_CHECK_EQ(decoded.body_digest().hex(), plan.body_digest().hex());
  CPATH_CHECK(decoded.id == plan.id);
  CPATH_CHECK(decoded.input_digest == plan.input_digest);
  CPATH_CHECK(decoded.bindings == plan.bindings);
  CPATH_CHECK(decoded.paths == plan.paths);
  CPATH_CHECK(decoded.stages == plan.stages);
  CPATH_CHECK(decoded.allocations == plan.allocations);
  CPATH_CHECK(decoded.stats == plan.stats);
  CPATH_CHECK(cp::validate_plan(decoded, request).is_ok());
  CPATH_CHECK_EQ(cp::encode_plan_text(decoded), plan_text);

  // A truncated record is refused instead of being partially decoded.
  const std::vector<std::uint8_t> truncated(bytes.begin(), bytes.end() - 1);
  check_rejected(cp::Plan::decode(truncated).status(), cp::ErrorCode::kTruncatedRecord, "truncated plan record");
}

// ===========================================================================
// Two edge- and rack-independent paths per logical edge
// ===========================================================================

CPATH_TEST(IntegrationRing, four_node_ring_two_disjoint_paths) {
  const cp::RequestSpec parsed =
      require_value(cp::parse_request_spec(ct::four_node_ring_text()), "four_node_ring_text");
  const cp::PlanningRequest request =
      require_value(cp::build_request(two_plane_ring(parsed, false)), "two plane fabric");  // SYNTHETIC

  // The policy is the one the fixture declares; only the fabric was replaced.
  CPATH_CHECK_EQ(request.policy.paths_per_logical_edge, std::size_t{2});
  CPATH_CHECK_EQ(std::string(cp::to_string(request.policy.disjointness)), std::string("edge"));
  CPATH_CHECK_EQ(std::string(cp::to_string(request.policy.domain_diversity)), std::string("required"));
  CPATH_CHECK_EQ(std::string(cp::to_string(request.policy.domain_diversity_level)), std::string("rack"));
  CPATH_CHECK_EQ(request.policy.max_hops, std::size_t{6});
  CPATH_CHECK_EQ(request.collective.logical_edges.size(), std::size_t{4});
  CPATH_CHECK_EQ(request.fabric.node_count(), std::size_t{14});
  CPATH_CHECK_EQ(request.fabric.edge_count(), std::size_t{24});

  const cp::PlanningOutcome outcome = cp::plan_collective(request);
  if (!outcome.ok()) {
    CPATH_FAIL("two plane ring was refused: " + ct::describe_outcome(outcome));
  }
  const cp::Plan& plan = *outcome.plan;
  check_plan_invariants(plan, request, "four node ring");
  CPATH_CHECK_EQ(plan.paths.size(), std::size_t{8});
  CPATH_CHECK_EQ(plan.stats.hop_count, std::size_t{24});
  CPATH_CHECK_EQ(plan.stages.size(), std::size_t{1});
  CPATH_CHECK_EQ(plan.stages[0].paths.size(), std::size_t{8});
  CPATH_CHECK_EQ(plan.stages[0].logical_edges.size(), std::size_t{4});

  for (std::size_t index = 0; index < plan.paths.size(); ++index) {
    CPATH_CHECK_EQ(plan.paths[index].hops.size(), std::size_t{3});
    CPATH_CHECK_EQ(plan.paths[index].cost, std::uint64_t{300u});
    // Rack-level diversity is only meaningful when the signature is not empty.
    CPATH_CHECK_EQ(plan.paths[index].domain_signature.size(), std::size_t{1});
  }

  // Each logical edge is carried by exactly two paths that share no physical
  // edge, no interior node and no failure domain: one failure cannot remove both.
  for (std::size_t index = 0; index + 1u < plan.paths.size(); index += 2u) {
    const cp::PathPlan& first = plan.paths[index];
    const cp::PathPlan& second = plan.paths[index + 1u];
    CPATH_CHECK(first.logical_edge == second.logical_edge);
    CPATH_REQUIRE_EQ(first.domain_signature.size(), std::size_t{1});
    CPATH_REQUIRE_EQ(second.domain_signature.size(), std::size_t{1});
    CPATH_CHECK(first.domain_signature[0] != second.domain_signature[0]);
    const std::vector<std::string> left_interior = interior_nodes(first);
    const std::vector<std::string> right_interior = interior_nodes(second);
    CPATH_CHECK(!left_interior.empty());
    CPATH_CHECK(!right_interior.empty());
    for (const std::string& node : left_interior) {
      CPATH_CHECK(std::find(right_interior.begin(), right_interior.end(), node) == right_interior.end());
    }
  }

  // The declared demand is split across the sibling paths: 1000 mbps over two
  // paths is 500 mbps per path per hop, and every physical edge carries exactly
  // one path of one logical edge here.
  CPATH_CHECK_EQ(request.collective.demand_mbps, std::uint64_t{1000u});
  CPATH_CHECK_EQ(plan.allocations.size(), std::size_t{24});
  for (const cp::Allocation& allocation : plan.allocations) {
    CPATH_CHECK_EQ(allocation.planned_mbps, std::uint64_t{500u});
    CPATH_CHECK(request.fabric.find_edge(allocation.edge) != nullptr);
  }

  // The same request planned again is byte identical, and the stored form
  // survives a round trip that is re-checked against the same request.
  const cp::PlanningOutcome again = cp::plan_collective(request);
  CPATH_REQUIRE(again.ok());
  CPATH_CHECK(again.plan->encode() == plan.encode());
  const cp::Plan decoded = require_value(cp::Plan::decode(plan.encode()), "ring plan decode");
  check_plan_invariants(decoded, request, "four node ring (decoded)");
  CPATH_CHECK(decoded.paths == plan.paths);
  CPATH_CHECK(decoded.allocations == plan.allocations);
  CPATH_CHECK(decoded.stats == plan.stats);
}

CPATH_TEST(IntegrationRing, shipped_fixture_fabric_plans_end_to_end) {
  // The shipped four-node fixture now ships a two-spine fabric, so its own
  // declared policy (two edge-disjoint paths, rack diversity required) must be
  // satisfiable without any augmentation. SYNTHETIC.
  const cp::PlanningRequest request =
      require_value(cp::parse_request_text(ct::four_node_ring_text()), "four_node_ring_text");
  const cp::PlanningOutcome outcome = cp::plan_collective(request);
  if (!outcome.ok()) {
    CPATH_FAIL("the shipped four-node fixture was refused: " + ct::describe_outcome(outcome));
  }
  const cp::Plan& plan = *outcome.plan;
  CPATH_CHECK(cp::validate_plan(plan, request).is_ok());
  CPATH_CHECK_EQ(plan.paths.size(), std::size_t{8});
  CPATH_CHECK_EQ(plan.stats.logical_edge_count, std::size_t{4});

  // Sibling paths share no physical edge and no interior node: each logical edge
  // is carried once through each spine, so a single spine failure cannot take
  // both down.
  for (std::size_t index = 0; index + 1u < plan.paths.size(); index += 2u) {
    const cp::PathPlan& first = plan.paths[index];
    const cp::PathPlan& second = plan.paths[index + 1u];
    CPATH_CHECK(first.logical_edge == second.logical_edge);
    for (const cp::Hop& left : first.hops) {
      for (const cp::Hop& right : second.hops) {
        CPATH_CHECK(!(left.edge == right.edge));
      }
    }
    const std::vector<std::string> left_interior = interior_nodes(first);
    const std::vector<std::string> right_interior = interior_nodes(second);
    CPATH_CHECK(!left_interior.empty());
    CPATH_CHECK(!right_interior.empty());
    for (const std::string& node : left_interior) {
      CPATH_CHECK(std::find(right_interior.begin(), right_interior.end(), node) == right_interior.end());
    }
  }

  // Both spines are used, which is what makes the two siblings independent.
  std::vector<std::string> spines;
  for (const cp::PathPlan& path : plan.paths) {
    for (const std::string& node : interior_nodes(path)) {
      spines.push_back(node);
    }
  }
  std::sort(spines.begin(), spines.end());
  spines.erase(std::unique(spines.begin(), spines.end()), spines.end());
  CPATH_CHECK(std::find(spines.begin(), spines.end(), std::string("s0")) != spines.end());
  CPATH_CHECK(std::find(spines.begin(), spines.end(), std::string("s1")) != spines.end());
}

// ===========================================================================
// Determinism
// ===========================================================================

CPATH_TEST(IntegrationDeterminism, same_request_plans_identically) {
  const cp::RequestSpec spec = eight_participant_spec();  // SYNTHETIC
  const cp::PlanningRequest request = require_value(cp::build_request(spec), "eight participant request");
  const cp::PlanningOutcome first = cp::plan_collective(request);
  const cp::PlanningOutcome second = cp::plan_collective(request);
  CPATH_REQUIRE(first.ok());
  CPATH_REQUIRE(second.ok());
  CPATH_CHECK(first.plan->encode() == second.plan->encode());
  CPATH_CHECK(first.plan->id == second.plan->id);
  CPATH_CHECK_EQ(first.plan->body_digest().hex(), second.plan->body_digest().hex());
  CPATH_CHECK_EQ(first.search_expansions, second.search_expansions);
  CPATH_CHECK_EQ(cp::encode_plan_text(*first.plan), cp::encode_plan_text(*second.plan));
  CPATH_CHECK_EQ(cp::render_plan_json(*first.plan), cp::render_plan_json(*second.plan));
  const cp::PlanComparison comparison = cp::compare_plans(*first.plan, *second.plan);
  CPATH_CHECK(comparison.identical);
  CPATH_CHECK_EQ(comparison.changed_logical_edges, std::size_t{0});
}

CPATH_TEST(IntegrationDeterminism, declaration_order_does_not_change_the_plan) {
  const cp::RequestSpec ordered = eight_participant_spec();  // SYNTHETIC
  cp::RequestSpec reversed = ordered;
  std::reverse(reversed.fabric.failure_domains.begin(), reversed.fabric.failure_domains.end());
  std::reverse(reversed.fabric.nodes.begin(), reversed.fabric.nodes.end());
  std::reverse(reversed.fabric.edges.begin(), reversed.fabric.edges.end());
  std::reverse(reversed.bindings.begin(), reversed.bindings.end());
  std::reverse(reversed.collective.groups.begin(), reversed.collective.groups.end());
  CPATH_REQUIRE(reversed.fabric.nodes.size() > 1u);
  CPATH_CHECK(reversed.fabric.nodes[0].id.value() != ordered.fabric.nodes[0].id.value());

  const cp::PlanningRequest first = require_value(cp::build_request(ordered), "ordered declarations");
  const cp::PlanningRequest second = require_value(cp::build_request(reversed), "reversed declarations");
  CPATH_CHECK_EQ(first.canonical_digest.hex(), second.canonical_digest.hex());

  const cp::PlanningOutcome left = cp::plan_collective(first);
  const cp::PlanningOutcome right = cp::plan_collective(second);
  CPATH_REQUIRE(left.ok());
  CPATH_REQUIRE(right.ok());
  CPATH_CHECK(left.plan->encode() == right.plan->encode());
  CPATH_CHECK(left.plan->id == right.plan->id);
  CPATH_CHECK_EQ(cp::encode_plan_text(*left.plan), cp::encode_plan_text(*right.plan));
  check_plan_invariants(*right.plan, second, "reversed declarations");
}

// ===========================================================================
// Staleness after a topology change
// ===========================================================================

CPATH_TEST(IntegrationStaleness, topology_generation_change_is_stale) {
  cp::RequestSpec current = eight_participant_spec();  // SYNTHETIC
  current.fabric.topology_generation = cp::TopologyGeneration{7};
  const cp::PlanningRequest before = require_value(cp::build_request(current), "topology generation 7");
  const cp::PlanningOutcome outcome = cp::plan_collective(before);
  CPATH_REQUIRE(outcome.ok());
  const cp::Plan& plan = *outcome.plan;
  CPATH_CHECK_EQ(plan.bindings.topology.value(), std::uint64_t{7u});

  // Only the topology generation moves; every physical fact stays the same.
  cp::RequestSpec advanced = current;
  advanced.fabric.topology_generation = cp::TopologyGeneration{8};
  const cp::PlanningRequest after = require_value(cp::build_request(advanced), "topology generation 8");

  CPATH_CHECK_EQ(std::string(cp::to_string(cp::assess_freshness(plan, after.current_bindings()))),
                 std::string("stale-topology"));
  cp::ErrorCode code = cp::ErrorCode::kOk;
  const char* description = cp::describe_freshness(cp::PlanFreshness::kStaleTopology, code);
  CPATH_CHECK(code == cp::ErrorCode::kStaleTopologyGeneration);
  CPATH_CHECK(std::string(description).size() > 0u);

  const std::string freshness_json = cp::render_freshness_json(plan, cp::PlanFreshness::kStaleTopology);
  check_json(freshness_json, "stale_topology_generation", "render_freshness_json");
  CPATH_CHECK(freshness_json.find("\"current\":false") != std::string::npos);

  // Re-validating the old plan against the new request fails at the strictest
  // check first: the topology generation is part of the canonical digest, so the
  // plan no longer matches the request it would be used for.
  check_rejected(cp::validate_plan(plan, after), cp::ErrorCode::kPlanInputMismatch,
                 "plan validated against a newer topology generation");
  CPATH_CHECK(cp::validate_plan(plan, before).is_ok());

  // The advanced request still plans, and the two plans are not interchangeable.
  const cp::PlanningOutcome replanned = cp::plan_collective(after);
  CPATH_REQUIRE(replanned.ok());
  CPATH_CHECK_EQ(replanned.plan->bindings.topology.value(), std::uint64_t{8u});
  CPATH_CHECK(!(replanned.plan->encode() == plan.encode()));
  const cp::PlanComparison comparison = cp::compare_plans(*replanned.plan, plan);
  CPATH_CHECK(!comparison.same_input_digest);
  CPATH_CHECK(comparison.same_collective);
}

// ===========================================================================
// Denials
// ===========================================================================

CPATH_TEST(IntegrationDenials, domain_diversity_denial_returns_no_plan) {
  const cp::RequestSpec parsed =
      require_value(cp::parse_request_spec(ct::four_node_ring_text()), "four_node_ring_text");
  // Both planes end in the same core failure domain, so the two edge-disjoint
  // siblings that exist are never rack independent. SYNTHETIC.
  cp::RequestSpec spec = two_plane_ring(parsed, true);
  const cp::PlanningRequest request = require_value(cp::build_request(spec), "shared core fabric");
  CPATH_CHECK_EQ(std::string(cp::to_string(request.policy.domain_diversity)), std::string("required"));

  const cp::PlanningOutcome refused = cp::plan_collective(request);
  if (refused.plan.has_value()) {
    CPATH_FAIL("a denial must never be accompanied by a partial plan");
  }
  CPATH_CHECK(!refused.ok());
  CPATH_CHECK(!refused.denials.empty());
  CPATH_CHECK(refused.primary_code() == cp::ErrorCode::kDomainDiversityUnsatisfiable);
  for (const cp::DenialDetail& denial : refused.denials) {
    CPATH_CHECK(denial.code == cp::ErrorCode::kDomainDiversityUnsatisfiable);
    CPATH_CHECK(denial.conflict == cp::ConflictKind::kDomainDiversity);
    CPATH_CHECK(!denial.message.empty());
    CPATH_CHECK(denial.logical_edge.valid());
  }

  // Proof that the refusal is about diversity, not about a missing path: the
  // identical fabric with diversity relaxed does provide two edge-disjoint paths
  // for every logical edge.
  cp::RequestSpec relaxed = spec;
  relaxed.policy.domain_diversity = cp::DomainDiversity::kNone;
  const cp::PlanningRequest permissive = require_value(cp::build_request(relaxed), "relaxed fabric");
  const cp::PlanningOutcome accepted = cp::plan_collective(permissive);
  if (!accepted.ok()) {
    CPATH_FAIL("relaxed diversity was refused: " + ct::describe_outcome(accepted));
  }
  check_plan_invariants(*accepted.plan, permissive, "relaxed diversity");
  CPATH_CHECK_EQ(accepted.plan->paths.size(), std::size_t{8});
  for (std::size_t index = 0; index + 1u < accepted.plan->paths.size(); index += 2u) {
    const cp::PathPlan& left = accepted.plan->paths[index];
    const cp::PathPlan& right = accepted.plan->paths[index + 1u];
    CPATH_CHECK(left.logical_edge == right.logical_edge);
    for (const cp::Hop& left_hop : left.hops) {
      for (const cp::Hop& right_hop : right.hops) {
        CPATH_CHECK(!(left_hop.edge == right_hop.edge));
      }
    }
  }
}

CPATH_TEST(IntegrationDenials, explain_denials_names_the_constraint_and_code) {
  const cp::RequestSpec parsed =
      require_value(cp::parse_request_spec(ct::four_node_ring_text()), "four_node_ring_text");
  const cp::PlanningRequest request =
      require_value(cp::build_request(two_plane_ring(parsed, true)), "shared core fabric");  // SYNTHETIC
  const cp::PlanningOutcome refused = cp::plan_collective(request);
  if (refused.ok()) {
    CPATH_FAIL("expected a domain-diversity denial but the request planned");
  }

  const std::string explanation = cp::explain_denials(refused);
  CPATH_CHECK(explanation.find("domain_diversity_unsatisfiable") != std::string::npos);
  CPATH_CHECK(explanation.find("domain-diversity") != std::string::npos);
  CPATH_CHECK(explanation.find("planning refused") != std::string::npos);

  // The machine rendering carries the same symbol and the conflict class.
  const std::string json = cp::render_outcome_json(refused);
  check_json(json, "domain_diversity_unsatisfiable", "render_outcome_json denial");
  CPATH_CHECK(json.find("\"ok\":false") != std::string::npos);
  CPATH_CHECK(json.find("domain-diversity") != std::string::npos);

  // A successful outcome explains itself without inventing denials.
  const cp::PlanningOutcome ok = cp::plan_collective(
      require_value(cp::build_request(two_plane_ring(parsed, false)), "two plane fabric"));
  CPATH_REQUIRE(ok.ok());
  CPATH_CHECK_EQ(cp::explain_denials(ok), std::string("planning succeeded; no denials\n"));
  CPATH_CHECK(ok.primary_code() == cp::ErrorCode::kOk);
}

// ===========================================================================
// The full pipeline on a wider synthetic fabric
// ===========================================================================

CPATH_TEST(IntegrationPipeline, eight_participant_two_spine_pipeline) {
  // SYNTHETIC: eight participants, two spines, four racks, generated by the
  // shared fixture layer. No measurement is involved anywhere.
  const cp::RequestSpec spec = eight_participant_spec();
  const cp::PlanningRequest request = require_value(cp::build_request(spec), "eight participant request");
  CPATH_CHECK_EQ(request.collective.participants.size(), std::size_t{8});
  CPATH_CHECK_EQ(request.collective.logical_edges.size(), std::size_t{8});
  CPATH_CHECK(request.fabric.node_count() >= 10u);
  CPATH_CHECK_EQ(std::string(cp::to_string(request.fabric.edges()[0].evidence)), std::string("synthetic"));
  CPATH_CHECK_EQ(request.collective.demand_mbps, std::uint64_t{1000u});

  const cp::PlanningOutcome outcome = cp::plan_collective(request);
  if (!outcome.ok()) {
    CPATH_FAIL("eight participant pipeline was refused: " + ct::describe_outcome(outcome));
  }
  const cp::Plan& plan = *outcome.plan;
  CPATH_CHECK(cp::validate_plan(plan, request).is_ok());
  CPATH_CHECK_EQ(plan.paths.size(), std::size_t{8});
  CPATH_CHECK_EQ(plan.stats.hop_count, std::size_t{16});
  CPATH_CHECK(ct::plan_uses_ineligible_edge(plan, request.fabric) == false);
  CPATH_CHECK_EQ(std::string(cp::to_string(plan.weakest_evidence)), std::string("synthetic"));
  CPATH_CHECK_EQ(plan.allocations.size(), std::size_t{16});
  for (const cp::Allocation& allocation : plan.allocations) {
    CPATH_CHECK_EQ(allocation.planned_mbps, std::uint64_t{1000u});
    CPATH_CHECK(request.fabric.find_edge(allocation.edge) != nullptr);
  }

  // Every hop of every path is a real fabric edge whose endpoints agree.
  for (const cp::PathPlan& path : plan.paths) {
    if (path.hops.empty()) {
      CPATH_FAIL("eight participant path has no hops");
    }
    for (std::size_t index = 0; index < path.hops.size(); ++index) {
      const cp::Edge* edge = request.fabric.find_edge(path.hops[index].edge);
      if (edge == nullptr) {
        CPATH_FAIL("eight participant path uses an edge outside the fabric");
      }
      CPATH_CHECK(edge->from == path.hops[index].from);
      CPATH_CHECK(edge->to == path.hops[index].to);
      if (index + 1u < path.hops.size()) {
        CPATH_CHECK(path.hops[index + 1u].from == path.hops[index].to);
      }
    }
  }

  // Round trip through the canonical text and the canonical bytes.
  const cp::PlanningRequest reparsed =
      require_value(cp::parse_request_text(cp::encode_request_text(request)), "re-parsed request text");
  CPATH_CHECK_EQ(reparsed.canonical_digest.hex(), request.canonical_digest.hex());
  const cp::PlanningOutcome rebuilt = cp::plan_collective(reparsed);
  CPATH_REQUIRE(rebuilt.ok());
  CPATH_CHECK(rebuilt.plan->encode() == plan.encode());
  CPATH_CHECK(cp::validate_plan(*rebuilt.plan, request).is_ok());
  CPATH_CHECK(require_value(cp::Plan::decode(plan.encode()), "plan decode").encode() == plan.encode());
  check_json(cp::render_plan_json(plan), plan.id.value().hex(), "eight participant plan json");
  CPATH_CHECK(cp::explain_plan(plan, &request).find("all plan invariants hold for these inputs") !=
              std::string::npos);
}

int main(int argc, char** argv) { return cpath_test::Registry::instance().run(argc, argv); }
