// Collective Path Planner - persistence suite.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
//
// Every fabric used here is SYNTHETIC: generated by the tests, never measured on
// a device. The suite proves the durable-state contract: versioned and
// integrity-checked records, atomic commits, restart fencing, conservative
// revalidation, bounded growth, and corruption that is rejected rather than
// partially applied.
#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include "cpath/dsl.hpp"
#include "cpath/persistence.hpp"
#include "cpath/planner.hpp"
#include "fixtures.hpp"
#include "process.hpp"
#include "test_framework.hpp"

namespace {

using cpath::ErrorCode;
using cpath::Incarnation;
using cpath::PlanStore;
using cpath::PlanningRequest;
using cpath::StoredPlanSummary;
using cpath::StoreConfig;

std::string request_text(std::uint64_t topology_generation, std::uint64_t plan_generation) {
  return std::string(
             "cpath-request 1\n"
             "plan-generation ") +
         std::to_string(plan_generation) +
         "\n"
         "topology-generation " +
         std::to_string(topology_generation) +
         "\n"
         "failure-domain-generation 2\n"
         "capacity-evidence-generation 3\n"
         "policy-generation 1\n"
         "\n"
         "[collective]\n"
         "id=c0 kind=ring\n"
         "\n"
         "[groups]\n"
         "g0 level=0 pattern=ring members=p0,p1,p2\n"
         "\n"
         "[domains]\n"
         "S0 kind=site\n"
         "R0 kind=rack parent=S0\n"
         "R1 kind=rack parent=S0\n"
         "\n"
         "[nodes]\n"
         "n0 site=S0 rack=R0 host=H0 device=0 tier=LEAF\n"
         "n1 site=S0 rack=R1 host=H1 device=0 tier=LEAF\n"
         "n2 site=S0 rack=R0 host=H2 device=0 tier=LEAF\n"
         "sp site=S0 pod=P0 rack=CORE host=SP device=0 tier=SPINE\n"
         "\n"
         "[edges]\n"
         "l0 from=n0 to=sp capacity=10000 latency=100 tier=LEAF domain=R0 evidence=synthetic\n"
         "l1 from=sp to=n0 capacity=10000 latency=100 tier=LEAF domain=R0 evidence=synthetic\n"
         "l2 from=n1 to=sp capacity=10000 latency=100 tier=LEAF domain=R1 evidence=synthetic\n"
         "l3 from=sp to=n1 capacity=10000 latency=100 tier=LEAF domain=R1 evidence=synthetic\n"
         "l4 from=n2 to=sp capacity=10000 latency=100 tier=LEAF domain=R0 evidence=synthetic\n"
         "l5 from=sp to=n2 capacity=10000 latency=100 tier=LEAF domain=R0 evidence=synthetic\n"
         "\n"
         "[bindings]\n"
         "p0 node=n0\n"
         "p1 node=n1\n"
         "p2 node=n2\n"
         "\n"
         "[policy]\n"
         "max-hops=4\n"
         "paths-per-logical-edge=1\n";
}

PlanningRequest parse_or_fail(const std::string& text) {
  auto request = cpath::parse_request_text(text);
  if (!request.has_value()) {
    CPATH_FAIL("request rejected: " + request.status().to_string());
  }
  return std::move(request.value());
}

struct Fixture {
  std::string root{};
  Fixture() : root(cpath_test::temporary_directory("store")) {}
  ~Fixture() { cpath_test::remove_directory_tree(root); }
  Fixture(const Fixture&) = delete;
  Fixture& operator=(const Fixture&) = delete;

  StoreConfig config() const {
    StoreConfig value;
    value.root = root;
    return value;
  }
};

std::string record_path(const std::string& root, const cpath::Digest& digest) {
  return (std::filesystem::path(root) / ("plan-" + digest.hex() + ".rec")).string();
}

void overwrite(const std::string& path, const std::string& content) {
  std::ofstream stream(path, std::ios::binary | std::ios::trunc);
  stream << content;
}

}  // namespace

CPATH_TEST(persistence, record_codec_round_trips) {
  const PlanningRequest request = parse_or_fail(request_text(7, 1));
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request);
  CPATH_REQUIRE(outcome.ok());

  const std::vector<std::uint8_t> record =
      cpath::encode_plan_record(*outcome.plan, request, Incarnation{9}, 42u, 1234567u);
  StoredPlanSummary summary;
  auto decoded = cpath::decode_plan_record(record, &summary);
  CPATH_REQUIRE(decoded.has_value());
  CPATH_CHECK(decoded.value().encode() == outcome.plan->encode());
  CPATH_CHECK(summary.id.value() == outcome.plan->id.value());
  CPATH_CHECK_EQ(summary.stored_sequence, 42u);
  CPATH_CHECK_EQ(summary.written_incarnation.value(), 9u);
  CPATH_CHECK_EQ(summary.written_unix_micros, 1234567u);
  CPATH_CHECK_EQ(summary.record_bytes, record.size());
  CPATH_CHECK(summary.collective == outcome.plan->collective);
  CPATH_CHECK_EQ(static_cast<int>(summary.kind), static_cast<int>(outcome.plan->kind));
  CPATH_CHECK(summary.bindings == outcome.plan->bindings);
}

CPATH_TEST(persistence, record_codec_rejects_each_defect_with_its_own_code) {
  const PlanningRequest request = parse_or_fail(request_text(7, 1));
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request);
  CPATH_REQUIRE(outcome.ok());
  const std::vector<std::uint8_t> record =
      cpath::encode_plan_record(*outcome.plan, request, Incarnation{1}, 1u, 0u);

  const auto expect = [&](const std::vector<std::uint8_t>& bytes, ErrorCode code, const char* what) {
    auto decoded = cpath::decode_plan_record(bytes, nullptr);
    if (decoded.has_value()) {
      CPATH_FAIL(std::string(what) + ": a defective record was accepted");
    }
    if (static_cast<int>(decoded.status().code()) != static_cast<int>(code)) {
      CPATH_FAIL(std::string(what) + ": expected " + cpath::code_symbol(code) + " but got " +
                 cpath::code_symbol(decoded.status().code()));
    }
  };

  std::vector<std::uint8_t> wrong_magic = record;
  wrong_magic[0] = 'X';
  expect(wrong_magic, ErrorCode::kCorruptRecord, "wrong magic");

  std::vector<std::uint8_t> wrong_version = record;
  wrong_version[4] = 0x7F;
  expect(wrong_version, ErrorCode::kUnsupportedRecordVersion, "wrong version");

  // Byte 6 is the low byte of the declared header length, so flipping it is a
  // layout change (reported as truncation); the CRC case needs a byte that is
  // covered by the checksum but does not describe the layout. Offset 22 is
  // inside the sequence field.
  std::vector<std::uint8_t> bad_header = record;
  bad_header[22] ^= 0xFFu;
  expect(bad_header, ErrorCode::kCorruptRecord, "flipped header byte");

  std::vector<std::uint8_t> oversize = record;
  oversize[10] = 0xFFu;
  oversize[11] = 0xFFu;
  oversize[12] = 0xFFu;
  oversize[13] = 0x7Fu;
  expect(oversize, ErrorCode::kOversizedRecord, "oversize declared payload");

  std::vector<std::uint8_t> bad_payload = record;
  bad_payload[record.size() - 80u] ^= 0xFFu;  // inside the plan payload
  expect(bad_payload, ErrorCode::kDigestMismatch, "flipped payload byte");

  std::vector<std::uint8_t> bad_request_digest = record;
  bad_request_digest[record.size() - 1u] ^= 0xFFu;
  expect(bad_request_digest, ErrorCode::kDigestMismatch, "flipped request digest");

  std::vector<std::uint8_t> trailing = record;
  trailing.push_back(0u);
  expect(trailing, ErrorCode::kTrailingGarbage, "trailing byte");

  for (std::size_t length = 0; length < record.size(); ++length) {
    const std::span<const std::uint8_t> prefix(record.data(), length);
    auto decoded = cpath::decode_plan_record(prefix, nullptr);
    CPATH_CHECK(!decoded.has_value());
  }
}

CPATH_TEST(persistence, store_lifecycle_and_refusals) {
  Fixture fixture;
  const PlanningRequest request = parse_or_fail(request_text(7, 1));
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request);
  CPATH_REQUIRE(outcome.ok());

  PlanStore store(fixture.config());
  // Operating on a closed store is a deterministic failure, not undefined state.
  CPATH_CHECK_EQ(static_cast<int>(store.get(cpath::CollectivePlanId{outcome.plan->id.value()}).status().code()),
                 static_cast<int>(ErrorCode::kStoreNotOpen));
  CPATH_CHECK(store.open().is_ok());
  CPATH_CHECK(store.open().code() == ErrorCode::kStoreAlreadyOpen);
  CPATH_CHECK(store.is_open());
  CPATH_CHECK(std::filesystem::exists(std::filesystem::path(fixture.root) / "store.meta"));

  auto stored = store.put(*outcome.plan, request);
  CPATH_REQUIRE(stored.has_value());
  CPATH_CHECK_EQ(store.record_count(), 1u);
  CPATH_CHECK(store.close().is_ok());
  CPATH_CHECK(store.close().is_ok());  // idempotent
  CPATH_CHECK(!store.is_open());
  CPATH_CHECK_EQ(store.record_count(), 0u);
}

CPATH_TEST(persistence, reopening_advances_the_epoch_and_incarnation) {
  Fixture fixture;
  const PlanningRequest request = parse_or_fail(request_text(7, 1));
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request);
  CPATH_REQUIRE(outcome.ok());

  cpath::Epoch first_epoch;
  Incarnation first_incarnation;
  {
    PlanStore store(fixture.config());
    CPATH_REQUIRE(store.open().is_ok());
    first_epoch = store.epoch();
    first_incarnation = store.incarnation();
    auto stored = store.put(*outcome.plan, request);
    CPATH_REQUIRE(stored.has_value());
    CPATH_CHECK(stored.value().written_incarnation == first_incarnation);
    CPATH_CHECK(store.close().is_ok());
  }
  {
    PlanStore store(fixture.config());
    CPATH_REQUIRE(store.open().is_ok());
    CPATH_CHECK(store.epoch().value() > first_epoch.value());
    CPATH_CHECK(store.incarnation().value() > first_incarnation.value());
    // A record written by the previous process is still readable...
    auto loaded = store.get(cpath::CollectivePlanId{outcome.plan->id.value()});
    CPATH_REQUIRE(loaded.has_value());
    CPATH_CHECK(loaded.value().encode() == outcome.plan->encode());
    // ...and its summary still names the incarnation that wrote it.
    auto summary = store.summary(cpath::CollectivePlanId{outcome.plan->id.value()});
    CPATH_REQUIRE(summary.has_value());
    CPATH_CHECK(summary.value().written_incarnation == first_incarnation);
    CPATH_CHECK(!(summary.value().written_incarnation == store.incarnation()));
    CPATH_CHECK(store.close().is_ok());
  }
}

CPATH_TEST(persistence, revalidation_classifies_every_generation_change) {
  Fixture fixture;
  const PlanningRequest request = parse_or_fail(request_text(7, 1));
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request);
  CPATH_REQUIRE(outcome.ok());
  const cpath::CollectivePlanId plan_id{outcome.plan->id.value()};

  PlanStore store(fixture.config());
  CPATH_REQUIRE(store.open().is_ok());
  CPATH_REQUIRE(store.put(*outcome.plan, request).has_value());

  auto same = store.revalidate(plan_id, request);
  CPATH_REQUIRE(same.has_value());
  CPATH_CHECK(same.value().still_valid);
  CPATH_CHECK_EQ(static_cast<int>(same.value().freshness), static_cast<int>(cpath::PlanFreshness::kCurrent));
  CPATH_CHECK_EQ(static_cast<int>(same.value().code), static_cast<int>(ErrorCode::kOk));

  const PlanningRequest stale = parse_or_fail(request_text(8, 1));
  auto stale_result = store.revalidate(plan_id, stale);
  CPATH_REQUIRE(stale_result.has_value());
  CPATH_CHECK(!stale_result.value().still_valid);
  CPATH_CHECK_EQ(static_cast<int>(stale_result.value().freshness),
                 static_cast<int>(cpath::PlanFreshness::kStaleTopology));
  CPATH_CHECK_EQ(static_cast<int>(stale_result.value().code),
                 static_cast<int>(ErrorCode::kStaleTopologyGeneration));
  CPATH_REQUIRE(stale_result.value().replanned.has_value());
  CPATH_CHECK(stale_result.value().replanned->input_digest == stale.canonical_digest);
  CPATH_CHECK(!(stale_result.value().stored_input_digest == stale_result.value().current_input_digest));

  // Bumping only the plan generation is a sequencing change, not a new mapping.
  const PlanningRequest replanned = parse_or_fail(request_text(7, 2));
  auto plan_generation = store.revalidate(plan_id, replanned);
  CPATH_REQUIRE(plan_generation.has_value());
  CPATH_CHECK(!plan_generation.value().still_valid);
  CPATH_CHECK_EQ(static_cast<int>(plan_generation.value().freshness),
                 static_cast<int>(cpath::PlanFreshness::kStalePlanGeneration));

  auto missing = store.revalidate(cpath::CollectivePlanId{cpath::Digest{}}, request);
  CPATH_CHECK(!missing.has_value());
  CPATH_CHECK_EQ(static_cast<int>(missing.status().code()), static_cast<int>(ErrorCode::kNotFound));
  CPATH_CHECK(store.close().is_ok());
}

CPATH_TEST(persistence, put_refuses_a_plan_from_other_inputs) {
  Fixture fixture;
  const PlanningRequest request = parse_or_fail(request_text(7, 1));
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request);
  CPATH_REQUIRE(outcome.ok());
  const PlanningRequest other = parse_or_fail(request_text(9, 1));

  PlanStore store(fixture.config());
  CPATH_REQUIRE(store.open().is_ok());
  auto stored = store.put(*outcome.plan, other);
  CPATH_CHECK(!stored.has_value());
  CPATH_CHECK_EQ(static_cast<int>(stored.status().code()), static_cast<int>(ErrorCode::kRecordIncompatible));
  CPATH_CHECK_EQ(store.record_count(), 0u);

  // A plan that does not survive validation is refused too.
  cpath::Plan corrupted = *outcome.plan;
  corrupted.stats.total_cost += 1u;
  auto refused = store.put(corrupted, request);
  CPATH_CHECK(!refused.has_value());
  CPATH_CHECK_EQ(static_cast<int>(refused.status().code()), static_cast<int>(ErrorCode::kInconsistentMetadata));
  CPATH_CHECK(store.close().is_ok());
}

CPATH_TEST(persistence, growth_is_bounded_and_the_oldest_record_is_evicted) {
  Fixture fixture;
  StoreConfig config = fixture.config();
  config.max_records = 2;
  PlanStore store(config);
  CPATH_REQUIRE(store.open().is_ok());

  std::vector<cpath::Digest> digests;
  for (std::uint64_t generation = 1; generation <= 3; ++generation) {
    const PlanningRequest request = parse_or_fail(request_text(6 + generation, generation));
    const cpath::PlanningOutcome outcome = cpath::plan_collective(request);
    CPATH_REQUIRE(outcome.ok());
    digests.push_back(outcome.plan->id.value());
    auto stored = store.put(*outcome.plan, request);
    CPATH_REQUIRE(stored.has_value());
    CPATH_CHECK(store.record_count() <= 2u);
  }
  CPATH_CHECK_EQ(store.record_count(), 2u);
  auto oldest = store.get(cpath::CollectivePlanId{digests.front()});
  CPATH_CHECK(!oldest.has_value());
  CPATH_CHECK_EQ(static_cast<int>(oldest.status().code()), static_cast<int>(ErrorCode::kNotFound));
  auto newest = store.get(cpath::CollectivePlanId{digests.back()});
  CPATH_CHECK(newest.has_value());
  CPATH_CHECK(store.close().is_ok());
}

CPATH_TEST(persistence, corruption_on_disk_is_never_applied) {
  Fixture fixture;
  const PlanningRequest request = parse_or_fail(request_text(7, 1));
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request);
  CPATH_REQUIRE(outcome.ok());
  const cpath::Digest digest = outcome.plan->id.value();
  const std::string path = record_path(fixture.root, digest);

  {
    PlanStore store(fixture.config());
    CPATH_REQUIRE(store.open().is_ok());
    CPATH_REQUIRE(store.put(*outcome.plan, request).has_value());
    CPATH_CHECK(store.close().is_ok());
  }
  CPATH_REQUIRE(std::filesystem::exists(path));
  overwrite(path, "this is not a plan record");

  PlanStore store(fixture.config());
  CPATH_REQUIRE(store.open().is_ok());
  CPATH_CHECK_EQ(store.record_count(), 0u);
  auto listed = store.list();
  CPATH_REQUIRE(listed.has_value());
  CPATH_CHECK(listed.value().empty());
  auto verified = store.verify_all();
  CPATH_REQUIRE(verified.has_value());
  CPATH_CHECK(verified.value().empty());
  auto missing = store.get(cpath::CollectivePlanId{digest});
  CPATH_CHECK(!missing.has_value());
  CPATH_CHECK_EQ(static_cast<int>(missing.status().code()), static_cast<int>(ErrorCode::kNotFound));
  CPATH_CHECK(store.close().is_ok());
}

CPATH_TEST(persistence, torn_tail_and_truncation_are_refused) {
  Fixture fixture;
  const PlanningRequest request = parse_or_fail(request_text(7, 1));
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request);
  CPATH_REQUIRE(outcome.ok());
  const cpath::Digest digest = outcome.plan->id.value();
  const std::string path = record_path(fixture.root, digest);

  std::vector<std::uint8_t> good;
  {
    PlanStore store(fixture.config());
    CPATH_REQUIRE(store.open().is_ok());
    CPATH_REQUIRE(store.put(*outcome.plan, request).has_value());
    CPATH_CHECK(store.close().is_ok());
  }
  {
    std::ifstream stream(path, std::ios::binary);
    good.assign(std::istreambuf_iterator<char>(stream), std::istreambuf_iterator<char>());
  }
  CPATH_REQUIRE(!good.empty());

  // A torn tail: the durable commit was interrupted after the file appeared.
  {
    std::ofstream stream(path, std::ios::binary | std::ios::trunc);
    stream.write(reinterpret_cast<const char*>(good.data()),
                 static_cast<std::streamsize>(good.size() / 2u));
  }
  {
    PlanStore store(fixture.config());
    CPATH_REQUIRE(store.open().is_ok());
    CPATH_CHECK_EQ(store.record_count(), 0u);
    auto record = store.get(cpath::CollectivePlanId{digest});
    CPATH_CHECK(!record.has_value());
    CPATH_CHECK(store.close().is_ok());
  }

  // Restore and then append garbage, which is trailing content, not a record.
  {
    std::ofstream stream(path, std::ios::binary | std::ios::trunc);
    stream.write(reinterpret_cast<const char*>(good.data()), static_cast<std::streamsize>(good.size()));
    stream.write("tail", 4);
  }
  {
    PlanStore store(fixture.config());
    CPATH_REQUIRE(store.open().is_ok());
    CPATH_CHECK_EQ(store.record_count(), 0u);
    CPATH_CHECK(store.close().is_ok());
  }
}

CPATH_TEST(persistence, erase_and_bounds_are_exact) {
  Fixture fixture;
  StoreConfig config = fixture.config();
  config.max_records = 1;
  const PlanningRequest request = parse_or_fail(request_text(7, 1));
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request);
  CPATH_REQUIRE(outcome.ok());
  const cpath::CollectivePlanId plan_id{outcome.plan->id.value()};

  PlanStore store(config);
  CPATH_REQUIRE(store.open().is_ok());
  CPATH_REQUIRE(store.put(*outcome.plan, request).has_value());
  CPATH_CHECK(std::filesystem::exists(record_path(fixture.root, outcome.plan->id.value())));
  CPATH_CHECK(store.erase(plan_id).is_ok());
  CPATH_CHECK(!std::filesystem::exists(record_path(fixture.root, outcome.plan->id.value())));
  CPATH_CHECK_EQ(static_cast<int>(store.erase(plan_id).code()), static_cast<int>(ErrorCode::kNotFound));
  CPATH_CHECK(store.enforce_bounds().is_ok());
  CPATH_CHECK_EQ(store.record_count(), 0u);
  CPATH_CHECK(store.close().is_ok());
}

CPATH_TEST(persistence, reopening_a_store_that_holds_only_the_metadata_is_clean) {
  Fixture fixture;
  const std::string meta = (std::filesystem::path(fixture.root) / "store.meta").string();
  cpath::Epoch epoch;
  Incarnation incarnation;
  {
    PlanStore store(fixture.config());
    CPATH_REQUIRE(store.open().is_ok());
    epoch = store.epoch();
    incarnation = store.incarnation();
    CPATH_CHECK(store.close().is_ok());
  }
  CPATH_REQUIRE(std::filesystem::exists(meta));

  // Corrupting the metadata is refused rather than silently reinitialised.
  overwrite(meta, "not the store metadata");
  {
    PlanStore store(fixture.config());
    const cpath::Status status = store.open();
    CPATH_CHECK(!status.is_ok());
    CPATH_CHECK(status.code() == ErrorCode::kCorruptRecord ||
                status.code() == ErrorCode::kUnsupportedRecordVersion);
  }

  // Rebuild it correctly and prove the fence still advances from the stored value.
  std::filesystem::remove(meta);
  {
    PlanStore store(fixture.config());
    CPATH_REQUIRE(store.open().is_ok());
    CPATH_CHECK(store.epoch().value() >= epoch.value());
    CPATH_CHECK(store.incarnation().value() >= incarnation.value());
    CPATH_CHECK(store.close().is_ok());
  }
}

int main(int argc, char** argv) { return cpath_test::Registry::instance().run(argc, argv); }
