// Collective Path Planner - seeded randomized property proofs.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
//
// Every fabric in this suite is SYNTHETIC: generated by a model, never measured
// on a device. Nothing here is a hardware claim.
//
// Method: each iteration derives its own seed from the process run seed through
// cpath_test::make_random(stream), generates a randomized fabric and policy,
// builds the request and plans it, and then re-derives every promised property
// from the RETURNED PLAN and the REQUEST - never from planner internals. Every
// failure message carries the full parameter set that produced it, and the
// runner prints the seed, so any failure reproduces with --seed=N.
//
// Two properties that this library does not currently satisfy are documented
// inline at the point they would be asserted; they are not asserted, because a
// test that cannot pass proves nothing:
//   * node disjointness (see family 1): paths_node_disjoint compares terminal
//     nodes, so two sibling paths that both end at the destination can never be
//     accepted. The planner therefore denies every node-disjointness request
//     for more than one path, even when its own max-flow certificate reports
//     that the fabric admits such paths.
//   * the text round trip of allowed-path-tiers (see family 4): the DSL has no
//     keyword for it, so encode_request_text drops the field.
//
// Domain-diversity signature semantics, mirrored exactly by the checks below:
// a path's domain_signature is the set of failure domains the path ADDS BEYOND
// its two endpoint attachment domains. Both sibling paths necessarily sit in the
// source and destination attachment domains, so those carry no discriminating
// information (a failure there takes the endpoint down whichever path is used).
// The frozen header describes the field more loosely as "failure domains touched
// by this path at the policy's diversity level"; the implementation in
// src/planner.cpp (make_candidate) and src/plan.cpp (validate_plan) excludes the
// first and last hop domain, and this suite re-derives that value from the hops
// instead of reading it back, so a divergence still fails.
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <map>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "cpath/dsl.hpp"
#include "cpath/plan.hpp"
#include "cpath/planner.hpp"
#include "cpath/request.hpp"
#include "fixtures.hpp"
#include "test_framework.hpp"

namespace {

namespace cp = cpath;

using cpath_test::Random;

// Randomized iterations per collective family and per non-collective property.
// Every family therefore exercises far more than the 200 required cases.
constexpr std::size_t kCollectiveIterations = 250;
constexpr std::size_t kPropertyIterations = 250;

// Reports a violated property together with every parameter that produced it.
#define PROPERTY(condition, context)                                                                        \
  do {                                                                                                      \
    if (!(condition)) {                                                                                     \
      ::cpath_test::record_failure(__FILE__, __LINE__,                                                      \
                                   std::string("property violated: ") + #condition + " [" + (context) + "]"); \
    }                                                                                                       \
  } while (false)

// ---------------------------------------------------------------------------
// Independent re-derivation of the policy predicates a plan must respect.
// These deliberately restate the documented rules instead of calling into the
// planner, so that a divergence between the two surfaces as a failure.
// ---------------------------------------------------------------------------

bool node_is_forbidden(const cp::Policy& policy, const cp::NodeId& id) {
  return std::binary_search(policy.forbidden_nodes.begin(), policy.forbidden_nodes.end(), id);
}

bool tier_is_forbidden(const cp::Policy& policy, const cp::TierId& tier) {
  return tier.valid() && std::binary_search(policy.forbidden_tiers.begin(), policy.forbidden_tiers.end(), tier);
}

// Ancestor-aware: a hop whose failure domain is CONTAINED by a forbidden domain
// is forbidden as well, which is what FabricGraph::domain_contains encodes.
bool domain_is_forbidden(const cp::FabricGraph& fabric, const cp::Policy& policy,
                         const cp::FailureDomainId& domain) {
  if (!domain.valid()) {
    return false;
  }
  for (const cp::FailureDomainId& forbidden : policy.forbidden_failure_domains) {
    if (fabric.domain_contains(forbidden, domain)) {
      return true;
    }
  }
  return false;
}

bool evidence_is_sufficient(cp::EvidenceClass observed, cp::EvidenceRequirement required) {
  switch (required) {
    case cp::EvidenceRequirement::kAny:
      return true;
    case cp::EvidenceRequirement::kSyntheticOrBetter:
      return observed != cp::EvidenceClass::kUnknown;
    case cp::EvidenceRequirement::kMeasured:
      return observed == cp::EvidenceClass::kMeasured;
  }
  return false;
}

cp::FailureDomainId domain_at_level(const cp::FabricGraph& fabric, const cp::FailureDomainId& domain,
                                    cp::DomainKind level) {
  if (!domain.valid()) {
    return cp::FailureDomainId{};
  }
  for (const cp::FailureDomainId& entry : fabric.domain_chain(domain)) {
    const cp::FailureDomain* record = fabric.find_failure_domain(entry);
    if (record != nullptr && record->kind == level) {
      return entry;
    }
  }
  return domain;
}

std::string describe_domains(const std::vector<cp::FailureDomainId>& domains) {
  std::string out;
  for (const cp::FailureDomainId& domain : domains) {
    if (!out.empty()) {
      out += ",";
    }
    out += domain.valid() ? domain.value() : std::string("<invalid>");
  }
  return out;
}

// Per-hop latency-only cost exactly as policy.hpp documents it:
// (latency_micros * latency_weight) / 1000, computed with saturating arithmetic.
std::uint64_t latency_term(const cp::Edge& edge, const cp::Policy& policy) {
  return cp::saturating_mul(edge.latency_micros, policy.latency_weight_milli, cp::kCostCeiling) / 1000u;
}

// One planned hop: it must name a real edge with matching endpoints, and it must
// be free of every excluded node, tier and failure domain.
void check_hop(const cp::Hop& hop, const cp::FabricGraph& fabric, const cp::Policy& policy,
               const std::string& where) {
  const cp::Edge* edge = fabric.find_edge(hop.edge);
  PROPERTY(edge != nullptr, where + ": hop references edge " + hop.edge.value() + " which is not in the fabric");
  if (edge == nullptr) {
    return;
  }
  PROPERTY(edge->from == hop.from && edge->to == hop.to,
           where + ": hop " + hop.edge.value() + " declares " + hop.from.value() + "->" + hop.to.value() +
               " but the physical edge is " + edge->from.value() + "->" + edge->to.value());
  PROPERTY(edge->eligible, where + ": hop uses ineligible edge " + hop.edge.value());
  const cp::Node* from_node = fabric.find_node(hop.from);
  const cp::Node* to_node = fabric.find_node(hop.to);
  PROPERTY(from_node != nullptr && from_node->eligible,
           where + ": hop leaves node " + hop.from.value() + " which is unknown or ineligible");
  PROPERTY(to_node != nullptr && to_node->eligible,
           where + ": hop enters node " + hop.to.value() + " which is unknown or ineligible");
  PROPERTY(!node_is_forbidden(policy, hop.from), where + ": hop leaves forbidden node " + hop.from.value());
  PROPERTY(!node_is_forbidden(policy, hop.to), where + ": hop enters forbidden node " + hop.to.value());
  PROPERTY(!tier_is_forbidden(policy, edge->tier),
           where + ": hop uses forbidden tier " + edge->tier.value());
  PROPERTY(policy.allowed_path_tiers.empty() ||
               (edge->tier.valid() && std::binary_search(policy.allowed_path_tiers.begin(),
                                                         policy.allowed_path_tiers.end(), edge->tier)),
           where + ": hop uses tier " + edge->tier.value() + " outside the allowed set");
  PROPERTY(!domain_is_forbidden(fabric, policy, edge->failure_domain),
           where + ": hop uses edge " + hop.edge.value() + " inside forbidden failure domain " +
               edge->failure_domain.value());
  PROPERTY(evidence_is_sufficient(edge->evidence, policy.evidence),
           where + ": hop relies on evidence below the required class");
  if (edge->capacity_mbps == 0) {
    PROPERTY(policy.allow_unverified_capacity,
             where + ": hop uses an edge with no verified capacity while the policy forbids that");
    PROPERTY(edge->reserved_mbps == 0, where + ": hop uses an unverified edge that carries a reservation");
  } else {
    PROPERTY(edge->reserved_mbps < edge->capacity_mbps,
             where + ": hop uses edge " + hop.edge.value() + " whose capacity is already fully reserved");
  }
}

// The single strongest assertion: every promise the planner makes, re-checked
// against the plan it returned and the request it was given.
//
// digest_bound is false only when the plan was produced for a DIFFERENT request
// that declares the same collective, policy and bindings over a fabric that is a
// subgraph of this one (the monotonicity family). Everything except the digest
// identity and the validate_plan call is fabric-relative, so the structural,
// disjointness, cost and allocation obligations are still re-derived in full.
void check_plan(const cp::Plan& plan, const cp::PlanningRequest& request, const std::string& context,
                bool digest_bound = true) {
  const cp::FabricGraph& fabric = request.fabric;
  const cp::Policy& policy = request.policy;
  const cp::Collective& collective = request.collective;
  const std::size_t logical_count = collective.logical_edges.size();

  PROPERTY(plan.stats.logical_edge_count == logical_count,
           context + ": plan reports " + std::to_string(plan.stats.logical_edge_count) +
               " logical edges but the collective declares " + std::to_string(logical_count));
  PROPERTY(plan.stats.path_count == plan.paths.size(), context + ": plan statistics do not count its own paths");
  PROPERTY(plan.kind == collective.kind, context + ": plan declares a different collective kind");
  PROPERTY(plan.collective == collective.id, context + ": plan names a different collective");

  std::vector<std::uint8_t> seen_path(plan.paths.size() + 1u, 0u);
  std::vector<std::vector<const cp::PathPlan*>> siblings(logical_count + 1u);

  std::uint64_t recomputed_total = 0;
  std::uint64_t recomputed_max = 0;
  std::size_t recomputed_hops = 0;
  for (const cp::PathPlan& path : plan.paths) {
    const std::string where = context + " path_id=" + std::to_string(path.id.value()) +
                              " logical_edge=" + std::to_string(path.logical_edge.value());
    PROPERTY(path.id.value() >= 1u && path.id.value() <= plan.paths.size(),
             where + ": path identity is outside the dense identity range");
    if (path.id.value() >= 1u && path.id.value() <= plan.paths.size()) {
      PROPERTY(seen_path[path.id.value()] == 0u, where + ": path identity is repeated");
      seen_path[path.id.value()] = 1u;
    }
    PROPERTY(path.logical_edge.value() >= 1u && path.logical_edge.value() <= logical_count,
             where + ": path names an unknown logical edge");
    if (path.logical_edge.value() < 1u || path.logical_edge.value() > logical_count) {
      continue;
    }
    const cp::LogicalEdge& logical = collective.logical_edges[path.logical_edge.value() - 1u];
    PROPERTY(path.src == logical.src && path.dst == logical.dst,
             where + ": path carries " + path.src.value() + "->" + path.dst.value() +
                 " but the logical edge is " + logical.src.value() + "->" + logical.dst.value());
    PROPERTY(path.stage == collective.logical_edge_stage[path.logical_edge.value() - 1u],
             where + ": path declares a stage the collective does not assign to this logical edge");
    siblings[path.logical_edge.value()].push_back(&path);

    PROPERTY(path.hops.size() <= policy.max_hops,
             where + ": path uses " + std::to_string(path.hops.size()) +
                 " hops but policy.max_hops is " + std::to_string(policy.max_hops));
    PROPERTY(path.cost <= cp::kCostCeiling, where + ": path cost exceeds the model ceiling");
    PROPERTY(path.cost <= policy.max_path_cost, where + ": path cost exceeds policy.max_path_cost");

    const cp::EndpointBinding* source_binding = request.find_binding(logical.src);
    const cp::EndpointBinding* target_binding = request.find_binding(logical.dst);
    PROPERTY(source_binding != nullptr && target_binding != nullptr,
             where + ": a participant of the logical edge has no endpoint binding");
    if (source_binding != nullptr && target_binding != nullptr) {
      if (path.hops.empty()) {
        PROPERTY(source_binding->node == target_binding->node,
                 where + ": a zero-hop path requires both participants on the same endpoint node");
      } else {
        PROPERTY(path.hops.front().from == source_binding->node,
                 where + ": path starts at " + path.hops.front().from.value() +
                     " but the source participant is bound to " + source_binding->node.value());
        PROPERTY(path.hops.back().to == target_binding->node,
                 where + ": path ends at " + path.hops.back().to.value() +
                     " but the destination participant is bound to " + target_binding->node.value());
      }
    }

    std::vector<cp::FailureDomainId> hop_domains;
    for (std::size_t index = 0; index < path.hops.size(); ++index) {
      const cp::Hop& hop = path.hops[index];
      check_hop(hop, fabric, policy, where + " hop=" + std::to_string(index));
      if (index + 1u < path.hops.size()) {
        PROPERTY(path.hops[index + 1u].from == hop.to,
                 where + ": hop " + std::to_string(index) + " ends at " + hop.to.value() + " but hop " +
                     std::to_string(index + 1u) + " starts at " + path.hops[index + 1u].from.value());
      }
      const cp::Edge* edge = fabric.find_edge(hop.edge);
      if (edge != nullptr && policy.domain_diversity != cp::DomainDiversity::kNone &&
          edge->failure_domain.valid()) {
        hop_domains.push_back(domain_at_level(fabric, edge->failure_domain,
                                              policy.domain_diversity_level));
      }
    }
    // The recorded signature is the diversity-level domain of every hop EXCEPT
    // the two endpoint attachment domains, which every sibling path necessarily
    // shares (a failure there takes the endpoint down whichever path is chosen).
    // This mirrors the planner and validate_plan; it is deliberately re-derived
    // here rather than read back from the plan.
    std::vector<cp::FailureDomainId> recomputed_signature;
    if (policy.domain_diversity != cp::DomainDiversity::kNone && !hop_domains.empty()) {
      const cp::FailureDomainId first_domain = hop_domains.front();
      const cp::FailureDomainId last_domain = hop_domains.back();
      bool removed_first = false;
      bool removed_last = false;
      for (const cp::FailureDomainId& domain : hop_domains) {
        if (!removed_first && domain == first_domain) {
          removed_first = true;
          continue;
        }
        if (!removed_last && domain == last_domain) {
          removed_last = true;
          continue;
        }
        recomputed_signature.push_back(domain);
      }
    }
    std::sort(recomputed_signature.begin(), recomputed_signature.end());
    recomputed_signature.erase(std::unique(recomputed_signature.begin(), recomputed_signature.end()),
                               recomputed_signature.end());
    PROPERTY(recomputed_signature == path.domain_signature,
             where + ": the recorded failure-domain signature [" + describe_domains(path.domain_signature) +
                 "] is not the one its hops imply [" + describe_domains(recomputed_signature) + "] at level " +
                 cp::to_string(policy.domain_diversity_level) + "; validate_plan says " +
                 cp::validate_plan(plan, request).to_string());

    recomputed_total = cp::saturating_add(recomputed_total, path.cost, cp::kCostCeiling);
    recomputed_max = std::max(recomputed_max, path.cost);
    recomputed_hops += path.hops.size();
  }

  PROPERTY(recomputed_total == plan.stats.total_cost,
           context + ": plan.stats.total_cost is not the saturating sum of its path costs");
  PROPERTY(recomputed_max == plan.stats.max_path_cost,
           context + ": plan.stats.max_path_cost is not the maximum of its path costs");
  PROPERTY(recomputed_hops == plan.stats.hop_count, context + ": plan.stats.hop_count does not match its paths");

  // Stage tables must describe exactly the paths and logical edges they list.
  std::size_t staged_paths = 0;
  std::size_t staged_logical = 0;
  for (const cp::Stage& stage : plan.stages) {
    PROPERTY(stage.index < plan.stage_count, context + ": stage index is out of range");
    staged_paths += stage.paths.size();
    staged_logical += stage.logical_edges.size();
    for (const cp::PathId& id : stage.paths) {
      PROPERTY(id.value() >= 1u && id.value() <= plan.paths.size() &&
                   plan.paths[id.value() - 1u].id == id && plan.paths[id.value() - 1u].stage == stage.index,
               context + ": a stage lists a path that does not belong to it");
    }
  }
  PROPERTY(staged_paths == plan.paths.size(), context + ": the stage table does not list every path once");
  PROPERTY(staged_logical == logical_count, context + ": the stage table does not list every logical edge once");

  // Sibling structure: every logical edge is served exactly once, with exactly
  // policy.paths_per_logical_edge paths.
  for (std::size_t index = 1; index <= logical_count; ++index) {
    const std::vector<const cp::PathPlan*>& group = siblings[index];
    PROPERTY(group.size() == policy.paths_per_logical_edge,
             context + ": logical edge " + std::to_string(index) + " has " + std::to_string(group.size()) +
                 " paths but policy.paths_per_logical_edge is " + std::to_string(policy.paths_per_logical_edge));
  }

  // Disjointness and diversity, recomputed pairwise over the sibling paths.
  for (std::size_t index = 1; index <= logical_count; ++index) {
    const std::vector<const cp::PathPlan*>& group = siblings[index];
    for (std::size_t i = 0; i < group.size(); ++i) {
      for (std::size_t j = i + 1u; j < group.size(); ++j) {
        const cp::PathPlan& lhs = *group[i];
        const cp::PathPlan& rhs = *group[j];
        const std::string pair = context + " logical_edge=" + std::to_string(index) + " siblings=" +
                                 std::to_string(lhs.id.value()) + "/" + std::to_string(rhs.id.value());
        if (policy.disjointness != cp::Disjointness::kNone) {
          for (const cp::Hop& left : lhs.hops) {
            for (const cp::Hop& right : rhs.hops) {
              PROPERTY(!(left.edge == right.edge),
                       pair + ": edge-disjoint paths share physical edge " + left.edge.value());
            }
          }
        }
        if (policy.disjointness == cp::Disjointness::kNode) {
          // "Intermediate" excludes the two bound endpoint nodes, which every
          // path carrying the logical edge necessarily shares.
          const cp::LogicalEdge& logical = collective.logical_edges[index - 1u];
          const cp::EndpointBinding* source_binding = request.find_binding(logical.src);
          const cp::EndpointBinding* target_binding = request.find_binding(logical.dst);
          std::vector<cp::NodeId> endpoints;
          if (source_binding != nullptr) {
            endpoints.push_back(source_binding->node);
          }
          if (target_binding != nullptr) {
            endpoints.push_back(target_binding->node);
          }
          std::vector<cp::NodeId> left_nodes;
          std::vector<cp::NodeId> right_nodes;
          const auto collect = [&endpoints](const cp::PathPlan& path, std::vector<cp::NodeId>& out) {
            for (const cp::Hop& hop : path.hops) {
              for (const cp::NodeId* node : {&hop.from, &hop.to}) {
                if (std::find(endpoints.begin(), endpoints.end(), *node) == endpoints.end()) {
                  out.push_back(*node);
                }
              }
            }
          };
          collect(lhs, left_nodes);
          collect(rhs, right_nodes);
          for (const cp::NodeId& node : left_nodes) {
            PROPERTY(std::find(right_nodes.begin(), right_nodes.end(), node) == right_nodes.end(),
                     pair + ": node-disjoint paths share intermediate node " + node.value());
          }
        }
        if (policy.domain_diversity == cp::DomainDiversity::kRequired && !lhs.hops.empty() && !rhs.hops.empty()) {
          for (const cp::FailureDomainId& domain : lhs.domain_signature) {
            PROPERTY(!std::binary_search(rhs.domain_signature.begin(), rhs.domain_signature.end(), domain),
                     pair + ": failure-domain signatures are not independent, both contain " + domain.value());
          }
        }
      }
    }
  }

  // Allocation bookkeeping, recomputed from the selected paths.
  std::unordered_map<cp::EdgeId, std::uint64_t, cp::StrongIdHash<cp::EdgeIdTag, std::string>> expected;
  if (collective.demand_mbps > 0) {
    const std::uint64_t per_path = (collective.demand_mbps + policy.paths_per_logical_edge - 1u) /
                                   policy.paths_per_logical_edge;
    for (const cp::PathPlan& path : plan.paths) {
      for (const cp::Hop& hop : path.hops) {
        expected[hop.edge] = cp::saturating_add(expected[hop.edge], per_path, cp::kCostCeiling);
      }
    }
  }
  PROPERTY(expected.size() == plan.allocations.size(),
           context + ": plan allocates " + std::to_string(plan.allocations.size()) +
               " edges but its paths use " + std::to_string(expected.size()));
  for (const cp::Allocation& allocation : plan.allocations) {
    const auto found = expected.find(allocation.edge);
    PROPERTY(found != expected.end() && found->second == allocation.planned_mbps,
             context + ": allocation for edge " + allocation.edge.value() +
                 " does not match the paths that use it");
    const cp::Edge* edge = fabric.find_edge(allocation.edge);
    if (edge == nullptr) {
      PROPERTY(false, context + ": plan allocates an edge that is not in the fabric");
      continue;
    }
    if (edge->capacity_mbps > 0) {
      std::string carriers;
      for (const cp::PathPlan& path : plan.paths) {
        const std::size_t uses = static_cast<std::size_t>(
            std::count_if(path.hops.begin(), path.hops.end(),
                          [&allocation](const cp::Hop& hop) { return hop.edge == allocation.edge; }));
        if (uses > 0u) {
          carriers += " path" + std::to_string(path.id.value()) + "(logical_edge=" +
                      std::to_string(path.logical_edge.value()) + ",uses=" + std::to_string(uses) + ")";
        }
      }
      PROPERTY(allocation.planned_mbps <= edge->capacity_mbps - edge->reserved_mbps,
               context + ": allocation of " + std::to_string(allocation.planned_mbps) + " Mbps on edge " +
                   allocation.edge.value() + " exceeds its verified spare capacity of " +
                   std::to_string(edge->capacity_mbps - edge->reserved_mbps) + " Mbps; carried by" + carriers);
    } else {
      PROPERTY(policy.allow_unverified_capacity,
               context + ": plan allocates demand on edge " + allocation.edge.value() +
                   " which has no verified capacity");
    }
  }

  if (digest_bound) {
    const cp::Status status = cp::validate_plan(plan, request);
    PROPERTY(status.is_ok(), context + ": validate_plan refused a produced plan: " + status.to_string());
  }
}

// A denial is terminal and must be specific: never a plan, never an internal
// error. An internal error here means the planner built a plan that failed its
// own validation, which is exactly the defect class this check exists for.
void check_denial(const cp::PlanningOutcome& outcome, const std::string& context) {
  PROPERTY(!outcome.ok(), context + ": outcome reports success but carries no plan");
  PROPERTY(!outcome.denials.empty(), context + ": the request was refused without any denial detail");
  for (const cp::DenialDetail& denial : outcome.denials) {
    PROPERTY(denial.code != cp::ErrorCode::kOk, context + ": a denial carries the success code");
    PROPERTY(denial.code != cp::ErrorCode::kInternalError,
             context + ": the planner refused a plan it had itself produced: " + denial.message);
    PROPERTY(!denial.message.empty(), context + ": denial " + cp::code_symbol(denial.code) + " has no detail");
  }
}

// ---------------------------------------------------------------------------
// Randomized case generation
// ---------------------------------------------------------------------------

std::string describe_policy(const cp::Policy& policy) {
  return "policy{max_hops=" + std::to_string(policy.max_hops) +
         " paths_per_logical_edge=" + std::to_string(policy.paths_per_logical_edge) +
         " disjointness=" + cp::to_string(policy.disjointness) +
         " domain_diversity=" + cp::to_string(policy.domain_diversity) + "/" +
         cp::to_string(policy.domain_diversity_level) + " evidence=" + cp::to_string(policy.evidence) +
         " latency_weight_milli=" + std::to_string(policy.latency_weight_milli) +
         " congestion_weight_milli=" + std::to_string(policy.congestion_weight_milli) +
         " max_path_cost=" + std::to_string(policy.max_path_cost) +
         " allow_unverified_capacity=" + std::string(policy.allow_unverified_capacity ? "1" : "0") +
         " max_search_expansions=" + std::to_string(policy.max_search_expansions) +
         " forbidden_nodes=" + std::to_string(policy.forbidden_nodes.size()) +
         " forbidden_tiers=" + std::to_string(policy.forbidden_tiers.size()) +
         " forbidden_domains=" + std::to_string(policy.forbidden_failure_domains.size()) +
         " allowed_tiers=" + std::to_string(policy.allowed_path_tiers.size()) + "}";
}

std::string describe_params(const cpath_test::SyntheticParams& params) {
  return "params{participants=" + std::to_string(params.participants) +
         " spines=" + std::to_string(params.spine_count) + " racks=" + std::to_string(params.rack_count) +
         " capacity_mbps=" + std::to_string(params.capacity_mbps) +
         " latency_micros=" + std::to_string(params.latency_micros) +
         " demand_mbps=" + std::to_string(params.demand_mbps) +
         " knobs{duplicate=" + std::to_string(params.duplicate_edge_percent) +
         " zero_capacity=" + std::to_string(params.zero_capacity_percent) +
         " unknown_evidence=" + std::to_string(params.unknown_evidence_percent) +
         " asymmetric=" + std::to_string(params.asymmetric_percent) +
         " huge_latency=" + std::to_string(params.huge_latency_percent) +
         " ineligible_edge=" + std::to_string(params.ineligible_edge_percent) + "}}";
}

std::string root_context(const char* family, std::size_t iteration, std::uint64_t seed,
                         const cpath_test::SyntheticParams& params, const cp::RequestSpec& spec) {
  return "family=" + std::string(family) + " iteration=" + std::to_string(iteration) + " seed=" +
         std::to_string(seed) + " " + describe_params(params) + " " + describe_policy(spec.policy);
}

cp::RequestSpec make_spec(std::size_t family, const cpath_test::SyntheticParams& params) {
  switch (family) {
    case 0:
      return cpath_test::make_ring_spec(params);
    case 1:
      return cpath_test::make_alltoall_spec(params);
    case 2:
      return cpath_test::make_pairwise_spec(params);
    default:
      return cpath_test::make_hierarchical_spec(params);
  }
}

const char* family_name(std::size_t family) {
  switch (family) {
    case 0:
      return "ring";
    case 1:
      return "alltoall";
    case 2:
      return "pairwise";
    default:
      return "hierarchical";
  }
}

// The shared fixtures bind every declared participant, so the generated shape
// has to be one the fixture's collective declares completely: a pairwise group
// drops an odd trailing member, and a hierarchical fixture drops every member of
// a rack that holds fewer than two participants.
cpath_test::SyntheticParams random_params(Random& rng, std::size_t family) {
  cpath_test::SyntheticParams params;
  params.seed = rng.next_u64();
  params.participants = static_cast<std::size_t>(4u + rng.below(5u));  // 4..8
  if (family == 2u && params.participants % 2u != 0u) {
    params.participants -= 1u;
  }
  params.spine_count = static_cast<std::size_t>(1u + rng.below(3u));  // 1..3
  const std::size_t max_racks =
      family == 3u ? params.participants / 2u : std::min<std::size_t>(4u, params.participants);
  params.rack_count = static_cast<std::size_t>(2u + rng.below(static_cast<std::uint64_t>(max_racks - 1u)));
  params.capacity_mbps = 1000u + rng.below(20000u);
  params.latency_micros = rng.below(400u);
  params.demand_mbps = rng.chance(1u, 2u) ? 0u : (1u + rng.below(params.capacity_mbps));
  params.topology_generation = 1u + rng.below(1000u);
  params.failure_domain_generation = 1u + rng.below(1000u);
  params.capacity_evidence_generation = 1u + rng.below(1000u);
  params.policy_generation = 1u + rng.below(1000u);
  params.plan_generation = 1u + rng.below(1000u);

  // Adversarial knobs, in the same spirit as the shared fixtures: each injects a
  // defect class that the planner must either route around or refuse precisely.
  params.duplicate_edge_percent = rng.chance(1u, 4u) ? static_cast<unsigned>(rng.below(25u)) : 0u;
  params.zero_capacity_percent = rng.chance(1u, 5u) ? static_cast<unsigned>(rng.below(15u)) : 0u;
  params.unknown_evidence_percent = rng.chance(1u, 5u) ? static_cast<unsigned>(rng.below(25u)) : 0u;
  params.asymmetric_percent = rng.chance(1u, 4u) ? static_cast<unsigned>(rng.below(40u)) : 0u;
  params.huge_latency_percent = rng.chance(1u, 5u) ? static_cast<unsigned>(rng.below(25u)) : 0u;
  params.ineligible_edge_percent = rng.chance(1u, 6u) ? static_cast<unsigned>(rng.below(15u)) : 0u;
  return params;
}

void randomize_policy(cp::RequestSpec& spec, Random& rng, bool allow_unrepresentable_tiers) {
  cp::Policy& policy = spec.policy;
  policy.max_hops = static_cast<std::size_t>(6u + rng.below(3u));  // 6..8
  bool two_paths = rng.chance(1u, 2u);
  policy.paths_per_logical_edge = two_paths ? 2u : 1u;

  // With two paths, edge disjointness is the interesting satisfiable case; node
  // disjointness is exercised separately (see the file header note) and is only
  // drawn for single-path requests here.
  if (two_paths) {
    policy.disjointness = rng.chance(1u, 2u) ? cp::Disjointness::kEdge : cp::Disjointness::kNone;
  } else {
    policy.disjointness = rng.chance(3u, 4u) ? cp::Disjointness::kNone : cp::Disjointness::kEdge;
    if (rng.chance(1u, 10u)) {
      policy.disjointness = cp::Disjointness::kNode;
    }
  }

  // In these leaf/spine fixtures every path necessarily traverses a failure
  // domain of each endpoint, so "required" diversity is only satisfiable with a
  // single path per logical edge.
  const std::uint64_t diversity_draw = rng.below(100u);
  if (diversity_draw < 70u) {
    policy.domain_diversity = cp::DomainDiversity::kNone;
  } else if (diversity_draw < 95u) {
    policy.domain_diversity = cp::DomainDiversity::kPreferred;
  } else {
    policy.domain_diversity = cp::DomainDiversity::kRequired;
    two_paths = false;
    policy.paths_per_logical_edge = 1u;
    const std::uint64_t level_draw = rng.below(3u);
    policy.domain_diversity_level = level_draw == 0u   ? cp::DomainKind::kHost
                                    : level_draw == 1u ? cp::DomainKind::kRack
                                                       : cp::DomainKind::kSite;
  }

  policy.evidence =
      rng.chance(4u, 5u) ? cp::EvidenceRequirement::kAny : cp::EvidenceRequirement::kSyntheticOrBetter;

  switch (rng.below(4u)) {
    case 0u:
      policy.latency_weight_milli = 1000u;
      break;
    case 1u:
      policy.latency_weight_milli = 1u;
      break;
    case 2u:
      policy.latency_weight_milli = cp::kMaxScoringWeightMilli;
      break;
    default:
      policy.latency_weight_milli = 1000u + rng.below(cp::kMaxScoringWeightMilli - 1000u + 1u);
      break;
  }
  policy.congestion_weight_milli = rng.chance(7u, 10u) ? 0u : rng.below(cp::kMaxScoringWeightMilli);
  policy.allow_unverified_capacity = rng.chance(1u, 2u);
  policy.max_path_cost = rng.chance(9u, 10u) ? cp::kMaxPathCostLimit : 1u + rng.below(1000000000000u);
  policy.max_search_expansions = rng.chance(19u, 20u) ? 1000u + rng.below(20000u) : (1u << 18);

  // Endpoints are the leaf nodes n0..; spines are s0... Forbidding a spine cuts
  // a route without disconnecting the endpoints, which keeps the sweep
  // interesting instead of trivially refusable.
  const std::size_t participant_count = spec.fabric.nodes.empty()
                                            ? 0u
                                            : std::min<std::size_t>(spec.fabric.nodes.size(),
                                                                    std::max<std::size_t>(
                                                                        spec.collective.groups.empty()
                                                                            ? 0u
                                                                            : spec.collective.groups.front()
                                                                                  .members.size(),
                                                                        0u));
  if (rng.chance(1u, 4u) && !spec.fabric.nodes.empty()) {
    const std::size_t spine_count = spec.fabric.nodes.size() >= participant_count
                                        ? spec.fabric.nodes.size() - participant_count
                                        : 0u;
    if (spine_count > 0u) {
      policy.forbidden_nodes.push_back(
          cp::NodeId{"s" + std::to_string(rng.below(spine_count))});
    }
  }
  if (rng.chance(1u, 12u) && participant_count > 0u) {
    policy.forbidden_nodes.push_back(cp::NodeId{"n" + std::to_string(rng.below(participant_count))});
  }
  if (rng.chance(1u, 16u)) {
    policy.forbidden_tiers.push_back(cp::TierId{"SPINE"});
  }
  if (rng.chance(1u, 20u)) {
    policy.forbidden_failure_domains.push_back(cp::FailureDomainId{"R0"});
  }
  if (allow_unrepresentable_tiers && rng.chance(1u, 20u)) {
    // A tier may not be both allowed and forbidden, so the allowed set wins.
    policy.forbidden_tiers.clear();
    policy.allowed_path_tiers.push_back(cp::TierId{"LEAF"});
    policy.allowed_path_tiers.push_back(cp::TierId{"SPINE"});
  }
}

// Shuffles every order-insensitive part of a request spec: the canonicalisers
// must erase the difference.
template <class T>
void shuffle(std::vector<T>& values, Random& rng) {
  for (std::size_t index = values.size(); index > 1u; --index) {
    const std::size_t other = static_cast<std::size_t>(rng.below(index));
    std::swap(values[index - 1u], values[other]);
  }
}

cp::RequestSpec shuffled_copy(const cp::RequestSpec& spec, Random& rng) {
  cp::RequestSpec copy = spec;
  shuffle(copy.fabric.failure_domains, rng);
  shuffle(copy.fabric.nodes, rng);
  shuffle(copy.fabric.edges, rng);
  shuffle(copy.bindings, rng);
  shuffle(copy.policy.forbidden_nodes, rng);
  shuffle(copy.policy.forbidden_tiers, rng);
  shuffle(copy.policy.forbidden_failure_domains, rng);
  shuffle(copy.policy.allowed_path_tiers, rng);
  shuffle(copy.collective.groups, rng);
  for (cp::GroupSpec& group : copy.collective.groups) {
    if (group.pattern == cp::GroupPattern::kRing) {
      // A rotation of a ring is the same cycle, and canonicalisation rotates the
      // smallest member into front, so this must not change the mapping.
      if (!group.members.empty()) {
        const std::size_t offset = static_cast<std::size_t>(rng.below(group.members.size()));
        std::rotate(group.members.begin(), group.members.begin() + static_cast<std::ptrdiff_t>(offset),
                    group.members.end());
      }
    } else {
      shuffle(group.members, rng);
    }
  }
  return copy;
}

}  // namespace

int main(int argc, char** argv) { return cpath_test::Registry::instance().run(argc, argv); }

// ---------------------------------------------------------------------------
// Family 1: randomized collectives on randomized synthetic topologies.
// ---------------------------------------------------------------------------
CPATH_TEST(Property, randomized_collectives_satisfy_every_invariant) {
  std::size_t planned_total = 0;
  std::size_t denied_total = 0;
  for (std::size_t family = 0; family < 4u; ++family) {
    std::size_t planned = 0;
    std::map<std::string, std::size_t> denials;
    for (std::size_t iteration = 0; iteration < kCollectiveIterations; ++iteration) {
      Random rng = cpath_test::make_random(1100u + family * 10000u + iteration);
      const std::uint64_t seed = rng.next_u64();
      const cpath_test::SyntheticParams params = random_params(rng, family);
      cp::RequestSpec spec = make_spec(family, params);
      randomize_policy(spec, rng, true);
      const std::string context = root_context(family_name(family), iteration, seed, params, spec);

      auto request = cp::build_request(spec);
      PROPERTY(request.has_value(),
               context + ": the generated request failed to build: " + request.status().to_string());
      if (!request.has_value()) {
        continue;
      }
      const cp::PlanningOutcome outcome = cp::plan_collective(request.value());
      if (outcome.ok()) {
        ++planned;
        check_plan(*outcome.plan, request.value(), context);
      } else {
        check_denial(outcome, context);
        denials[cp::code_symbol(outcome.primary_code())] += 1u;
      }
    }
    std::string histogram;
    for (const auto& [code, count] : denials) {
      histogram += " ";
      histogram += code;
      histogram += "=";
      histogram += std::to_string(count);
    }
    std::printf("SYNTHETIC property family %-12s: %3zu of %zu randomized requests planned; denial codes:%s\n",
                family_name(family), planned, kCollectiveIterations,
                histogram.empty() ? " none" : histogram.c_str());
    PROPERTY(planned > kCollectiveIterations / 4u,
             std::string("family ") + family_name(family) + " produced only " + std::to_string(planned) +
                 " plans; the invariant checks would be vacuous");
    planned_total += planned;
    denied_total += kCollectiveIterations - planned;
  }
  std::printf("SYNTHETIC property family summary: %zu plans checked, %zu denials checked\n", planned_total,
              denied_total);
}

// ---------------------------------------------------------------------------
// Family 2: monotonic invariance under added physical edges.
//
// What is proved, and what is deliberately NOT claimed:
//  * Without declared demand the mapping is a pure path-selection problem, so the
//    planner's decision IS asserted to be monotone: adding a physical edge must
//    never withdraw a plan.
//  * With declared demand the planner commits per-path demand onto the chosen
//    hops in canonical logical-edge order and searches later logical edges
//    against the remaining spare capacity. Adding edges changes which route an
//    earlier logical edge picks, which changes what is left for a later one.
//    Multi-commodity assignment under capacity is NP-hard and a deterministic
//    greedy order is not monotone in the edge set, so this suite does NOT claim
//    decision monotonicity there. What it does assert is safety, which always
//    holds: every plan returned for either fabric passes validate_plan, and the
//    plan produced for the poorer fabric - whose every edge still exists in the
//    richer one, under the same collective, policy and bindings - is re-derived
//    in full against the richer request. A refusal caused by the changed greedy
//    order is therefore a search-completeness artefact, never a soundness
//    failure, and it must still be a precise denial rather than an internal
//    error or a partial plan. The number of such interferences is printed.
// ---------------------------------------------------------------------------
CPATH_TEST(Property, added_physical_edges_never_withdraw_a_plan) {
  std::size_t exercised = 0;
  std::size_t capacity_order_refusals = 0;
  for (std::size_t iteration = 0; iteration < kPropertyIterations; ++iteration) {
    Random rng = cpath_test::make_random(2200u + iteration);
    const std::uint64_t seed = rng.next_u64();
    const std::size_t family = iteration % 4u;
    const cpath_test::SyntheticParams params = random_params(rng, family);
    cp::RequestSpec spec = make_spec(family, params);
    randomize_policy(spec, rng, false);
    // Satisfiability monotonicity is a claim about the MAPPING. The search budget
    // is a separate, documented bound on work: a larger graph can legitimately
    // exhaust a deliberately tiny budget, so the property is stated under the
    // default budget that the policy ships with.
    spec.policy.max_search_expansions = 1u << 18;

    const std::string poor_context = root_context("monotonic/poor", iteration, seed, params, spec);
    auto poor_request = cp::build_request(spec);
    PROPERTY(poor_request.has_value(),
             poor_context + ": the generated request failed to build: " + poor_request.status().to_string());
    if (!poor_request.has_value()) {
      continue;
    }
    const cp::PlanningOutcome poor_outcome = cp::plan_collective(poor_request.value());
    if (poor_outcome.ok()) {
      check_plan(*poor_outcome.plan, poor_request.value(), poor_context);
    } else {
      check_denial(poor_outcome, poor_context);
    }

    // Add one to three physical edges between existing nodes. The added edge is
    // placed on a tier and failure domain the policy does not exclude, so the
    // richer fabric really is a superset of usable routes.
    cp::RequestSpec rich = spec;
    const std::size_t additions = 1u + static_cast<std::size_t>(rng.below(3u));
    for (std::size_t index = 0; index < additions; ++index) {
      const std::size_t first = static_cast<std::size_t>(rng.below(rich.fabric.nodes.size()));
      std::size_t second = static_cast<std::size_t>(rng.below(rich.fabric.nodes.size()));
      if (rich.fabric.nodes.size() > 1u && second == first) {
        second = (second + 1u) % rich.fabric.nodes.size();
      }
      if (second == first) {
        continue;
      }
      cp::Edge edge;
      edge.id = cp::EdgeId{"added" + std::to_string(index)};
      edge.from = rich.fabric.nodes[first].id;
      edge.to = rich.fabric.nodes[second].id;
      edge.capacity_mbps = 1u + rng.below(params.capacity_mbps);
      edge.latency_micros = rng.below(params.latency_micros + 1u);
      edge.tier = cp::TierId{"LEAF"};
      if (std::find(rich.policy.forbidden_tiers.begin(), rich.policy.forbidden_tiers.end(), edge.tier) !=
          rich.policy.forbidden_tiers.end()) {
        edge.tier = cp::TierId{"EXTRA"};
      }
      edge.failure_domain = cp::FailureDomainId{"S0"};
      // The spec is not a graph yet, so the exclusion test is by identity: the
      // randomized policy only ever forbids the rack domain R0, never S0.
      if (std::find(rich.policy.forbidden_failure_domains.begin(),
                    rich.policy.forbidden_failure_domains.end(),
                    edge.failure_domain) != rich.policy.forbidden_failure_domains.end()) {
        edge.failure_domain = cp::FailureDomainId{};
      }
      edge.evidence = cp::EvidenceClass::kSynthetic;
      rich.fabric.edges.push_back(std::move(edge));
    }

    const std::string rich_context = root_context("monotonic/rich", iteration, seed, params, spec);
    auto rich_request = cp::build_request(rich);
    PROPERTY(rich_request.has_value(),
             rich_context + ": the richer request failed to build: " + rich_request.status().to_string());
    if (!rich_request.has_value()) {
      continue;
    }
    const cp::PlanningOutcome rich_outcome = cp::plan_collective(rich_request.value());
    if (poor_outcome.ok()) {
      ++exercised;
      // The richer fabric contains every edge the poorer plan uses, and the
      // collective, policy and bindings are identical, so that mapping is still
      // a valid mapping: adding an edge can never withdraw satisfiability. This
      // is asserted directly, by re-deriving every fabric-relative obligation of
      // the poorer plan against the richer request.
      check_plan(*poor_outcome.plan, rich_request.value(),
                 rich_context + " poorer-plan-rechecked-on-richer-fabric", false);
      if (params.demand_mbps == 0u) {
        // With no declared demand there is no allocation accounting, so the
        // planner's own decision must be monotone in the edge set too.
        PROPERTY(rich_outcome.ok(), rich_context + ": adding " + std::to_string(additions) +
                                        " physical edge(s) made a demand-free request unsatisfiable: " +
                                        cpath_test::describe_outcome(rich_outcome));
      } else {
        // A declared demand makes the planner commit capacity logical edge by
        // logical edge, so a richer fabric can change an earlier greedy choice
        // and leave a later one without room; that shows up as a capacity,
        // no-path or disjointness refusal. The mapping above proves the request
        // is still satisfiable, so these refusals are search-completeness, not
        // soundness - but they must still be precise: never a plan beside a
        // denial, never an internal error.
        if (!rich_outcome.ok()) {
          ++capacity_order_refusals;
          check_denial(rich_outcome, rich_context + " greedy-order refusal");
        }
      }
    }
    if (rich_outcome.ok()) {
      check_plan(*rich_outcome.plan, rich_request.value(), rich_context);
    } else {
      check_denial(rich_outcome, rich_context);
    }
  }
  std::printf("SYNTHETIC monotonic family: %zu satisfiable requests were re-planned on a richer fabric "
              "(every poorer plan re-validated there); %zu of them were refused because the richer fabric "
              "changed the greedy capacity-commitment order\n",
              exercised, capacity_order_refusals);
  PROPERTY(exercised > kPropertyIterations / 4u, "too few satisfiable requests to exercise the property");
}

// ---------------------------------------------------------------------------
// Family 3: canonical equivalence of independently ordered requests.
// ---------------------------------------------------------------------------
CPATH_TEST(Property, canonical_order_does_not_change_the_mapping) {
  for (std::size_t iteration = 0; iteration < kPropertyIterations; ++iteration) {
    Random rng = cpath_test::make_random(3300u + iteration);
    const std::uint64_t seed = rng.next_u64();
    const std::size_t family = iteration % 4u;
    const cpath_test::SyntheticParams params = random_params(rng, family);
    cp::RequestSpec original = make_spec(family, params);
    randomize_policy(original, rng, false);
    const cp::RequestSpec shuffled = shuffled_copy(original, rng);
    const std::string context = root_context("canonical", iteration, seed, params, original);

    auto left = cp::build_request(original);
    auto right = cp::build_request(shuffled);
    PROPERTY(left.has_value() && right.has_value(),
             context + ": a generated request failed to build: " +
                 (left.has_value() ? right.status().to_string() : left.status().to_string()));
    if (!left.has_value() || !right.has_value()) {
      continue;
    }
    PROPERTY(left.value().canonical_digest == right.value().canonical_digest,
             context + ": two logically identical requests have different canonical digests");
    PROPERTY(left.value().canonical_bytes == right.value().canonical_bytes,
             context + ": two logically identical requests have different canonical lengths");

    const cp::PlanningOutcome left_outcome = cp::plan_collective(left.value());
    const cp::PlanningOutcome right_outcome = cp::plan_collective(right.value());
    PROPERTY(left_outcome.ok() == right_outcome.ok(),
             context + ": logically identical requests disagree about satisfiability: " +
                 cpath_test::describe_outcome(left_outcome) + " vs " +
                 cpath_test::describe_outcome(right_outcome));
    if (left_outcome.ok() && right_outcome.ok()) {
      check_plan(*left_outcome.plan, left.value(), context + " left");
      PROPERTY(left_outcome.plan->encode() == right_outcome.plan->encode(),
               context + ": logically identical requests produced different plan bytes");
    } else {
      check_denial(left_outcome, context + " left");
      check_denial(right_outcome, context + " right");
      PROPERTY(left_outcome.primary_code() == right_outcome.primary_code(),
               context + ": logically identical requests were denied with different codes");
    }
  }
}

// ---------------------------------------------------------------------------
// Family 4: determinism, including through the canonical text form.
// ---------------------------------------------------------------------------
CPATH_TEST(Property, repeated_planning_and_reparsing_are_byte_identical) {
  for (std::size_t iteration = 0; iteration < kPropertyIterations; ++iteration) {
    Random rng = cpath_test::make_random(4400u + iteration);
    const std::uint64_t seed = rng.next_u64();
    const std::size_t family = iteration % 4u;
    const cpath_test::SyntheticParams params = random_params(rng, family);
    cp::RequestSpec spec = make_spec(family, params);
    // allowed-path-tiers is intentionally left unset: the text DSL has no
    // keyword for it, so the canonical text form cannot represent it and the
    // round-trip digest assertion below would be asserting an unimplemented
    // feature rather than determinism.
    randomize_policy(spec, rng, false);

    auto request = cp::build_request(spec);
    PROPERTY(request.has_value(), "determinism iteration=" + std::to_string(iteration) +
                                      " seed=" + std::to_string(seed) +
                                      ": the generated request failed to build: " + request.status().to_string());
    if (!request.has_value()) {
      continue;
    }
    const std::string context = "determinism family=" + std::string(family_name(family)) +
                                " iteration=" + std::to_string(iteration) + " seed=" +
                                std::to_string(seed) + " " + describe_params(params) + " " +
                                describe_policy(request.value().policy);

    const cp::PlanningOutcome first = cp::plan_collective(request.value());
    const cp::PlanningOutcome second = cp::plan_collective(request.value());
    PROPERTY(first.ok() == second.ok(), context + ": two identical calls disagree about satisfiability");
    if (first.ok() && second.ok()) {
      PROPERTY(first.plan->encode() == second.plan->encode(),
               context + ": two identical calls produced different plan bytes");
      check_plan(*first.plan, request.value(), context);
    } else {
      check_denial(first, context);
      PROPERTY(first.primary_code() == second.primary_code(),
               context + ": two identical calls were denied with different codes");
    }

    // The canonical text form must round-trip exactly, so a request that was
    // serialised and read back plans to the same bytes.
    const std::string text = cp::encode_request_text(request.value());
    auto copy_one = cp::parse_request_text(text);
    auto copy_two = cp::parse_request_text(text);
    PROPERTY(copy_one.has_value() && copy_two.has_value(),
             context + ": the canonical text form of the request does not parse back: " +
                 (copy_one.has_value() ? copy_two.status().to_string() : copy_one.status().to_string()));
    if (!copy_one.has_value() || !copy_two.has_value()) {
      continue;
    }
    PROPERTY(copy_one.value().canonical_digest == request.value().canonical_digest,
             context + ": the canonical text form does not round-trip to the same request digest");
    const cp::PlanningOutcome from_text_one = cp::plan_collective(copy_one.value());
    const cp::PlanningOutcome from_text_two = cp::plan_collective(copy_two.value());
    PROPERTY(from_text_one.ok() == first.ok(),
             context + ": a reparsed copy of the request disagrees about satisfiability");
    if (from_text_one.ok() && from_text_two.ok() && first.ok()) {
      PROPERTY(from_text_one.plan->encode() == from_text_two.plan->encode(),
               context + ": two reparsed copies of the same text produced different plan bytes");
      PROPERTY(from_text_one.plan->encode() == first.plan->encode(),
               context + ": a reparsed copy of the request produced different plan bytes than the original");
    }
  }
}

// ---------------------------------------------------------------------------
// Family 4b: an over-committing path combination is refused, never planned.
//
// This is the deterministic reproduction of the defect where the candidate
// search for one logical edge judged every sibling path against the state
// BEFORE the combination's own allocations were committed, so two sibling paths
// could each pass "remaining spare >= per-path demand" and then jointly commit
// twice that on the edge they share. The contract asserted here is the one the
// planner must honour: either it returns no plan at all, or the plan it returns
// keeps every allocation inside the edge's verified spare capacity.
// ---------------------------------------------------------------------------
CPATH_TEST(Property, over_committed_combinations_are_refused_not_planned) {
  // SYNTHETIC two-participant ring whose only second-hop edge is shared by both
  // sibling paths of each logical edge, so the demand per logical edge decides
  // whether the combination fits: capacity 10, two paths, demand 16 forces 8+8
  // on a 10 Mbps edge, demand 8 fits exactly.
  const auto build = [](std::uint64_t demand) {
    cp::RequestSpec spec;
    spec.fabric.topology_generation = cp::TopologyGeneration{11};
    spec.fabric.failure_domain_generation = cp::FailureDomainGeneration{12};
    spec.fabric.capacity_evidence_generation = cp::CapacityEvidenceGeneration{13};
    spec.policy.generation = cp::PolicyGeneration{14};
    spec.plan_generation = cp::CollectivePlanGeneration{15};
    cp::FailureDomain site;
    site.id = cp::FailureDomainId{"S0"};
    site.kind = cp::DomainKind::kSite;
    spec.fabric.failure_domains.push_back(std::move(site));
    cp::FailureDomain rack;
    rack.id = cp::FailureDomainId{"R0"};
    rack.parent = cp::FailureDomainId{"S0"};
    rack.kind = cp::DomainKind::kRack;
    spec.fabric.failure_domains.push_back(std::move(rack));
    for (const char* id : {"n0", "n1", "h"}) {
      cp::Node node;
      node.id = cp::NodeId{id};
      node.tier = cp::TierId{"T"};
      node.placement.supplied = true;
      node.placement.site = "S0";
      node.placement.rack = "R0";
      spec.fabric.nodes.push_back(std::move(node));
    }
    const auto edge = [&spec](const char* id, const char* from, const char* to, std::uint64_t capacity) {
      cp::Edge record;
      record.id = cp::EdgeId{id};
      record.from = cp::NodeId{from};
      record.to = cp::NodeId{to};
      record.capacity_mbps = capacity;
      record.latency_micros = 100;
      record.tier = cp::TierId{"T"};
      record.failure_domain = cp::FailureDomainId{"R0"};
      record.evidence = cp::EvidenceClass::kMeasured;
      spec.fabric.edges.push_back(std::move(record));
    };
    edge("a0", "n0", "h", 10);
    edge("a1", "n0", "h", 10);  // parallel first-mile
    edge("b0", "h", "n1", 10);  // the single shared last-mile edge
    edge("c0", "n1", "h", 10);
    edge("c1", "n1", "h", 10);  // parallel first-mile of the reverse exchange
    edge("d0", "h", "n0", 10);  // its single shared last-mile edge

    cp::GroupSpec group;
    group.id = cp::GroupId{"g0"};
    group.pattern = cp::GroupPattern::kRing;
    group.members = {cp::ParticipantId{"p0"}, cp::ParticipantId{"p1"}};
    spec.collective.id = cp::CollectiveId{"overcommit"};
    spec.collective.kind = cp::CollectiveKind::kRing;
    spec.collective.demand_mbps = demand;
    spec.collective.groups.push_back(std::move(group));

    cp::EndpointBinding first;
    first.participant = cp::ParticipantId{"p0"};
    first.node = cp::NodeId{"n0"};
    cp::EndpointBinding second;
    second.participant = cp::ParticipantId{"p1"};
    second.node = cp::NodeId{"n1"};
    spec.bindings = {first, second};

    spec.policy.max_hops = 4;
    spec.policy.paths_per_logical_edge = 2;
    spec.policy.disjointness = cp::Disjointness::kNone;
    spec.policy.evidence = cp::EvidenceRequirement::kAny;
    return spec;
  };

  // Over-committing: 8 Mbps per path over a 10 Mbps shared edge. Nothing may be
  // planned; the refusal must be specific rather than an internal error, and no
  // partial plan may be handed back beside the denial.
  {
    auto request = cp::build_request(build(16));
    CPATH_REQUIRE(request.has_value());
    const cp::PlanningOutcome outcome = cp::plan_collective(request.value());
    PROPERTY(!outcome.ok(),
             "over-commit demand=16: the planner returned a plan whose allocation exceeds the shared edge");
    PROPERTY(!outcome.plan.has_value(), "over-commit demand=16: a denial carries a partial plan");
    check_denial(outcome, "over-commit demand=16");
    PROPERTY(outcome.primary_code() == cp::ErrorCode::kInsufficientCapacity,
             std::string("over-commit demand=16: refusal code ") + cp::code_symbol(outcome.primary_code()) +
                 " does not name insufficient capacity (" + cpath_test::describe_outcome(outcome) + ")");
    for (const cp::DenialDetail& denial : outcome.denials) {
      PROPERTY(denial.conflict == cp::ConflictKind::kInsufficientCapacity,
               std::string("over-commit demand=16: denial conflict is ") + cp::to_string(denial.conflict) +
                   " rather than insufficient-capacity");
      PROPERTY(denial.logical_edge.valid(), "over-commit demand=16: the denial does not name the logical edge");
    }
    if (!outcome.ok()) {
      std::printf("SYNTHETIC over-commit case refused with %s: %s\n",
                  cp::code_symbol(outcome.primary_code()),
                  outcome.denials.empty() ? "(no detail)" : outcome.denials.front().message.c_str());
    }
  }

  // The same fabric with a demand that fits must still plan, which proves the
  // refusal above is about the arithmetic rather than about the topology.
  {
    auto request = cp::build_request(build(8));
    CPATH_REQUIRE(request.has_value());
    const cp::PlanningOutcome outcome = cp::plan_collective(request.value());
    PROPERTY(outcome.ok(), "over-commit control demand=8: the satisfiable request was refused: " +
                               cpath_test::describe_outcome(outcome));
    if (outcome.ok()) {
      check_plan(*outcome.plan, request.value(), "over-commit control demand=8");
      CPATH_CHECK_EQ(outcome.plan->stats.path_count, 4u);  // 2 logical edges x 2 paths
      // Each sibling pair splits the demand (4 Mbps per path); the first-mile
      // parallel edges carry one path each, and the single shared last-mile edge
      // of each direction carries both, which is exactly the demand and exactly
      // the capacity it has.
      const auto planned_for = [&outcome](const char* edge_id) {
        for (const cp::Allocation& allocation : outcome.plan->allocations) {
          if (allocation.edge == cp::EdgeId{edge_id}) {
            return allocation.planned_mbps;
          }
        }
        return std::uint64_t{0};
      };
      CPATH_CHECK_EQ(planned_for("a0"), 4u);
      CPATH_CHECK_EQ(planned_for("a1"), 4u);
      CPATH_CHECK_EQ(planned_for("b0"), 8u);  // shared: 2 x 4, equal to capacity
      CPATH_CHECK_EQ(planned_for("c0"), 4u);
      CPATH_CHECK_EQ(planned_for("c1"), 4u);
      CPATH_CHECK_EQ(planned_for("d0"), 8u);
    }
  }
}

// ---------------------------------------------------------------------------
// Family 5: a contradiction is always refused, and refused precisely.
// ---------------------------------------------------------------------------
CPATH_TEST(Property, forbidden_cut_nodes_always_yield_a_precise_denial) {
  for (std::size_t iteration = 0; iteration < kPropertyIterations; ++iteration) {
    Random rng = cpath_test::make_random(5500u + iteration);
    const std::uint64_t seed = rng.next_u64();
    const std::size_t middle_count = 1u + static_cast<std::size_t>(rng.below(4u));
    const std::uint64_t capacity = 1000u + rng.below(20000u);

    // SYNTHETIC star: p0 -> src -> mid[...] -> dst <- p1. Every route between the
    // endpoints passes through a middle node, and every middle node is
    // forbidden, so no plan can exist.
    cp::RequestSpec spec;
    spec.fabric.topology_generation = cp::TopologyGeneration{1u + rng.below(100u)};
    spec.fabric.failure_domain_generation = cp::FailureDomainGeneration{1u + rng.below(100u)};
    spec.fabric.capacity_evidence_generation = cp::CapacityEvidenceGeneration{1u + rng.below(100u)};
    spec.policy.generation = cp::PolicyGeneration{1u + rng.below(100u)};
    spec.plan_generation = cp::CollectivePlanGeneration{1u + rng.below(100u)};

    cp::FailureDomain site;
    site.id = cp::FailureDomainId{"S0"};
    site.kind = cp::DomainKind::kSite;
    spec.fabric.failure_domains.push_back(site);
    for (std::size_t index = 0; index < middle_count; ++index) {
      cp::FailureDomain domain;
      domain.id = cp::FailureDomainId{"M" + std::to_string(index)};
      domain.parent = cp::FailureDomainId{"S0"};
      domain.kind = cp::DomainKind::kRack;
      spec.fabric.failure_domains.push_back(domain);
    }
    cp::FailureDomain ends;
    ends.id = cp::FailureDomainId{"E0"};
    ends.parent = cp::FailureDomainId{"S0"};
    ends.kind = cp::DomainKind::kRack;
    spec.fabric.failure_domains.push_back(ends);

    const auto add_node = [&spec](const std::string& id, const std::string& domain) {
      cp::Node node;
      node.id = cp::NodeId{id};
      node.tier = cp::TierId{"LEAF"};
      node.placement.supplied = true;
      node.placement.site = "S0";
      node.placement.rack = domain;
      spec.fabric.nodes.push_back(std::move(node));
    };
    add_node("src", "E0");
    add_node("dst", "E0");
    for (std::size_t index = 0; index < middle_count; ++index) {
      add_node("mid" + std::to_string(index), "M" + std::to_string(index));
    }

    // Edges sit on their own tier so that a forbidden *edge* tier can be
    // expressed without also making the endpoint nodes ineligible.
    std::size_t edge_id = 0;
    const auto add_edge = [&](const std::string& from, const std::string& to, const std::string& domain) {
      cp::Edge edge;
      edge.id = cp::EdgeId{"x" + std::to_string(edge_id++)};
      edge.from = cp::NodeId{from};
      edge.to = cp::NodeId{to};
      edge.capacity_mbps = capacity;
      edge.latency_micros = 1u + rng.below(500u);
      edge.tier = cp::TierId{"FABRIC"};
      edge.failure_domain = cp::FailureDomainId{domain};
      edge.evidence = cp::EvidenceClass::kSynthetic;
      spec.fabric.edges.push_back(std::move(edge));
    };
    for (std::size_t index = 0; index < middle_count; ++index) {
      const std::string middle = "mid" + std::to_string(index);
      const std::string domain = "M" + std::to_string(index);
      add_edge("src", middle, domain);
      add_edge(middle, "src", domain);
      add_edge(middle, "dst", domain);
      add_edge("dst", middle, domain);
    }

    cp::GroupSpec group;
    group.id = cp::GroupId{"g0"};
    group.pattern = cp::GroupPattern::kRing;
    group.members.push_back(cp::ParticipantId{"p0"});
    group.members.push_back(cp::ParticipantId{"p1"});
    spec.collective.id = cp::CollectiveId{"cut"};
    spec.collective.kind = cp::CollectiveKind::kRing;
    spec.collective.groups.push_back(group);

    cp::EndpointBinding source_binding;
    source_binding.participant = cp::ParticipantId{"p0"};
    source_binding.node = cp::NodeId{"src"};
    cp::EndpointBinding target_binding;
    target_binding.participant = cp::ParticipantId{"p1"};
    target_binding.node = cp::NodeId{"dst"};
    spec.bindings.push_back(source_binding);
    spec.bindings.push_back(target_binding);

    for (std::size_t index = 0; index < middle_count; ++index) {
      spec.policy.forbidden_nodes.push_back(cp::NodeId{"mid" + std::to_string(index)});
    }
    spec.policy.max_hops = 8;

    const std::string context = "contradiction iteration=" + std::to_string(iteration) + " seed=" +
                                std::to_string(seed) + " middle_count=" + std::to_string(middle_count) +
                                " " + describe_policy(spec.policy);
    auto request = cp::build_request(spec);
    PROPERTY(request.has_value(),
             context + ": the generated request failed to build: " + request.status().to_string());
    if (!request.has_value()) {
      continue;
    }
    const cp::PlanningOutcome outcome = cp::plan_collective(request.value());
    PROPERTY(!outcome.ok(),
             context + ": a disconnected request produced a plan: " + cpath_test::describe_outcome(outcome));
    PROPERTY(!outcome.plan.has_value(), context + ": a denial carries a partial plan");
    check_denial(outcome, context);
    PROPERTY(outcome.primary_code() == cp::ErrorCode::kNodeForbidden,
             context + ": expected node_forbidden, got " + cp::code_symbol(outcome.primary_code()) + " (" +
                 cpath_test::describe_outcome(outcome) + ")");
    for (const cp::DenialDetail& denial : outcome.denials) {
      PROPERTY(denial.conflict == cp::ConflictKind::kForbiddenNode,
               context + ": denial conflict is " + cp::to_string(denial.conflict) +
                   " rather than forbidden-node");
      PROPERTY(denial.logical_edge.valid(), context + ": the denial does not name the logical edge it refused");
    }

    // The same cut expressed as a forbidden edge tier, and as a forbidden
    // failure domain, must be refused with the matching precise code.
    cp::RequestSpec by_tier = spec;
    by_tier.policy.forbidden_nodes.clear();
    by_tier.policy.forbidden_tiers.push_back(cp::TierId{"FABRIC"});
    auto tier_request = cp::build_request(by_tier);
    PROPERTY(tier_request.has_value(), context + ": the tier variant failed to build");
    if (tier_request.has_value()) {
      const cp::PlanningOutcome tier_outcome = cp::plan_collective(tier_request.value());
      PROPERTY(!tier_outcome.ok(), context + ": forbidding the only edge tier still produced a plan");
      check_denial(tier_outcome, context + " tier");
      PROPERTY(tier_outcome.primary_code() == cp::ErrorCode::kTierForbidden,
               context + ": expected tier_forbidden, got " + cp::code_symbol(tier_outcome.primary_code()));
    }

    cp::RequestSpec by_domain = spec;
    by_domain.policy.forbidden_nodes.clear();
    for (std::size_t index = 0; index < middle_count; ++index) {
      by_domain.policy.forbidden_failure_domains.push_back(cp::FailureDomainId{"M" + std::to_string(index)});
    }
    auto domain_request = cp::build_request(by_domain);
    PROPERTY(domain_request.has_value(), context + ": the failure-domain variant failed to build");
    if (domain_request.has_value()) {
      const cp::PlanningOutcome domain_outcome = cp::plan_collective(domain_request.value());
      PROPERTY(!domain_outcome.ok(), context + ": forbidding every route domain still produced a plan");
      check_denial(domain_outcome, context + " domain");
      PROPERTY(domain_outcome.primary_code() == cp::ErrorCode::kFailureDomainForbidden,
               context + ": expected failure_domain_forbidden, got " +
                   cp::code_symbol(domain_outcome.primary_code()));
    }
  }
}

// ---------------------------------------------------------------------------
// Family 6: scoring saturates, never wraps.
// ---------------------------------------------------------------------------
CPATH_TEST(Property, scoring_at_the_model_ceiling_never_wraps) {
  std::size_t exact_checked = 0;
  std::size_t monotone_checked = 0;
  for (std::size_t iteration = 0; iteration < kPropertyIterations; ++iteration) {
    Random rng = cpath_test::make_random(6600u + iteration);
    const std::uint64_t seed = rng.next_u64();
    cpath_test::SyntheticParams params;
    params.seed = rng.next_u64();
    params.participants = static_cast<std::size_t>(4u + rng.below(4u));
    params.spine_count = static_cast<std::size_t>(1u + rng.below(3u));
    params.rack_count = static_cast<std::size_t>(2u + rng.below(2u));
    // The spine-to-spine edges of the shared fixture are declared at twice
    // params.latency_micros, so the ceiling is injected through the adversarial
    // knob, which is applied after that doubling and therefore never overflows.
    params.huge_latency_percent = rng.chance(1u, 2u) ? 100u : static_cast<unsigned>(rng.below(50u));
    params.latency_micros = rng.below(3u) == 0u ? 0u : rng.below(cp::kMaxLatencyMicros / 2u);
    params.capacity_mbps = 10000u + rng.below(100000u);
    const bool with_demand = rng.chance(1u, 2u);
    params.demand_mbps = with_demand ? 1u + rng.below(params.capacity_mbps) : 0u;
    params.topology_generation = 1u + rng.below(100u);
    params.failure_domain_generation = 1u + rng.below(100u);
    params.capacity_evidence_generation = 1u + rng.below(100u);
    params.policy_generation = 1u + rng.below(100u);
    params.plan_generation = 1u + rng.below(100u);

    cp::RequestSpec spec = cpath_test::make_ring_spec(params);
    spec.policy.latency_weight_milli =
        rng.chance(1u, 2u) ? cp::kMaxScoringWeightMilli
                           : (1000u + rng.below(cp::kMaxScoringWeightMilli - 1000u + 1u));
    // Half of the iterations score latency only, where the exact cost is
    // re-derivable, and half add the congestion term at the model ceiling so
    // that the additive path is exercised too.
    spec.policy.congestion_weight_milli = with_demand ? cp::kMaxScoringWeightMilli : 0u;
    spec.policy.max_path_cost = cp::kMaxPathCostLimit;
    spec.policy.max_hops = 8;
    spec.policy.paths_per_logical_edge = 1u;

    auto request = cp::build_request(spec);
    const std::string context = "scoring iteration=" + std::to_string(iteration) + " seed=" +
                                std::to_string(seed) + " " + describe_params(params) + " " +
                                describe_policy(spec.policy);
    PROPERTY(request.has_value(),
             context + ": the generated request failed to build: " + request.status().to_string());
    if (!request.has_value()) {
      continue;
    }
    const cp::PlanningOutcome outcome = cp::plan_collective(request.value());
    if (!outcome.ok()) {
      check_denial(outcome, context);
      continue;
    }
    check_plan(*outcome.plan, request.value(), context);

    const cp::Policy& policy = request.value().policy;
    for (const cp::PathPlan& path : outcome.plan->paths) {
      const std::string where = context + " path_id=" + std::to_string(path.id.value());
      PROPERTY(path.cost <= cp::kCostCeiling, where + ": path cost exceeds the cost ceiling");
      std::uint64_t latency_sum = 0;
      bool any_latency_zero = false;
      for (const cp::Hop& hop : path.hops) {
        const cp::Edge* edge = request.value().fabric.find_edge(hop.edge);
        PROPERTY(edge != nullptr, where + ": hop references an unknown edge");
        if (edge == nullptr) {
          continue;
        }
        latency_sum = cp::saturating_add(latency_sum, latency_term(*edge, policy), cp::kCostCeiling);
        if (edge->latency_micros == 0) {
          any_latency_zero = true;
        }
      }
      if (policy.congestion_weight_milli == 0) {
        // Exact: with no congestion term the cost is the saturating sum of the
        // per-hop latency terms. A wrapped accumulator cannot satisfy this.
        ++exact_checked;
        PROPERTY(path.cost == latency_sum,
                 where + ": cost " + std::to_string(path.cost) +
                     " is not the exact saturating latency sum " + std::to_string(latency_sum));
      } else {
        // With congestion the penalty is non-negative, so the latency-only sum
        // is a lower bound and the ceiling is an upper bound; a wrap breaks one.
        PROPERTY(path.cost >= latency_sum,
                 where + ": cost " + std::to_string(path.cost) + " is below the latency-only sum " +
                     std::to_string(latency_sum));
      }
      if (!path.hops.empty() && policy.latency_weight_milli >= 1000u) {
        PROPERTY(path.cost != 0u || any_latency_zero,
                 where + ": a non-empty path scored zero although no hop has zero latency and the latency "
                         "weight is non-zero");
      }
    }
    PROPERTY(outcome.plan->stats.total_cost <= cp::kCostCeiling,
             context + ": total cost exceeds the cost ceiling");

    // Monotonicity in the number of paths: on the same fabric with no declared
    // demand, requiring two paths per logical edge can only add cost.
    if (!with_demand) {
      cp::RequestSpec doubled = cpath_test::make_ring_spec(params);
      doubled.policy = request.value().policy;
      doubled.policy.paths_per_logical_edge = 2u;
      doubled.policy.disjointness = cp::Disjointness::kNone;
      doubled.policy.domain_diversity = cp::DomainDiversity::kNone;
      auto doubled_request = cp::build_request(std::move(doubled));
      PROPERTY(doubled_request.has_value(), context + ": the two-path variant failed to build");
      if (doubled_request.has_value()) {
        const cp::PlanningOutcome doubled_outcome = cp::plan_collective(doubled_request.value());
        if (doubled_outcome.ok()) {
          ++monotone_checked;
          check_plan(*doubled_outcome.plan, doubled_request.value(), context + " two-path");
          PROPERTY(doubled_outcome.plan->stats.total_cost >= outcome.plan->stats.total_cost,
                   context + ": requiring more paths lowered the total cost from " +
                       std::to_string(outcome.plan->stats.total_cost) + " to " +
                       std::to_string(doubled_outcome.plan->stats.total_cost));
        } else {
          check_denial(doubled_outcome, context + " two-path");
        }
      }
    }
  }
  std::printf("SYNTHETIC scoring family: %zu paths checked against the exact cost identity, %zu monotone "
              "comparisons\n",
              exact_checked, monotone_checked);
  PROPERTY(exact_checked > 0u, "no path was checked against the exact cost identity");
  PROPERTY(monotone_checked > kPropertyIterations / 10u,
           "too few two-path plans to exercise cost monotonicity");
}

// ---------------------------------------------------------------------------
// Family 7: every generation field is a fence on its own.
// ---------------------------------------------------------------------------
CPATH_TEST(Property, every_generation_field_fences_a_plan_on_its_own) {
  std::size_t fenced = 0;
  for (std::size_t iteration = 0; iteration < kPropertyIterations; ++iteration) {
    Random rng = cpath_test::make_random(7700u + iteration);
    const std::uint64_t seed = rng.next_u64();
    const std::size_t family = iteration % 4u;
    const cpath_test::SyntheticParams params = random_params(rng, family);
    cp::RequestSpec spec = make_spec(family, params);
    randomize_policy(spec, rng, false);
    // Fencing needs a plan, so the fabric must stay satisfiable.
    spec.policy.disjointness = cp::Disjointness::kNone;
    spec.policy.domain_diversity = cp::DomainDiversity::kNone;
    spec.policy.paths_per_logical_edge = 1u;
    spec.policy.forbidden_nodes.clear();
    spec.policy.forbidden_tiers.clear();
    spec.policy.forbidden_failure_domains.clear();
    spec.policy.allowed_path_tiers.clear();
    spec.policy.allow_unverified_capacity = true;
    spec.policy.evidence = cp::EvidenceRequirement::kAny;
    spec.policy.max_path_cost = cp::kMaxPathCostLimit;
    spec.policy.max_search_expansions = 1u << 18;

    auto request = cp::build_request(spec);
    const std::string context = root_context("generation", iteration, seed, params, spec);
    PROPERTY(request.has_value(),
             context + ": the generated request failed to build: " + request.status().to_string());
    if (!request.has_value()) {
      continue;
    }
    const cp::PlanningOutcome outcome = cp::plan_collective(request.value());
    if (!outcome.ok()) {
      check_denial(outcome, context);
      continue;
    }
    check_plan(*outcome.plan, request.value(), context);
    ++fenced;

    const cp::GenerationBindings current = request.value().current_bindings();
    PROPERTY(cp::assess_freshness(*outcome.plan, current) == cp::PlanFreshness::kCurrent,
             context + ": a freshly produced plan is not reported as current");
    cp::ErrorCode current_code = cp::ErrorCode::kInternalError;
    const char* current_text = cp::describe_freshness(cp::PlanFreshness::kCurrent, current_code);
    PROPERTY(current_code == cp::ErrorCode::kOk && std::string(current_text) ==
                 "the plan was produced from exactly these generations",
             context + ": a current plan does not describe as current");

    // One bump at a time. Each bump is applied to a fresh copy of the spec, so
    // exactly one generation differs from the one the plan was built from.
    struct Bump {
      const char* name;
      cp::PlanFreshness freshness;
      cp::ErrorCode code;
    };
    const Bump bumps[5] = {
        {"topology", cp::PlanFreshness::kStaleTopology, cp::ErrorCode::kStaleTopologyGeneration},
        {"failure-domain", cp::PlanFreshness::kStaleFailureDomains, cp::ErrorCode::kStaleFailureDomainGeneration},
        {"capacity-evidence", cp::PlanFreshness::kStaleCapacityEvidence,
         cp::ErrorCode::kStaleCapacityEvidenceGeneration},
        {"policy", cp::PlanFreshness::kStalePolicy, cp::ErrorCode::kStalePolicyGeneration},
        {"plan", cp::PlanFreshness::kStalePlanGeneration, cp::ErrorCode::kStalePlanGeneration},
    };
    for (std::size_t index = 0; index < 5u; ++index) {
      cp::RequestSpec bumped_spec = make_spec(family, params);
      bumped_spec.policy = request.value().policy;
      bumped_spec.bindings = request.value().bindings;
      bumped_spec.plan_generation = request.value().plan_generation;
      switch (index) {
        case 0u:
          bumped_spec.fabric.topology_generation = cp::TopologyGeneration{current.topology.value() + 1u};
          break;
        case 1u:
          bumped_spec.fabric.failure_domain_generation =
              cp::FailureDomainGeneration{current.failure_domains.value() + 1u};
          break;
        case 2u:
          bumped_spec.fabric.capacity_evidence_generation =
              cp::CapacityEvidenceGeneration{current.capacity_evidence.value() + 1u};
          break;
        case 3u:
          bumped_spec.policy.generation = cp::PolicyGeneration{current.policy.value() + 1u};
          break;
        default:
          bumped_spec.plan_generation = cp::CollectivePlanGeneration{current.plan.value() + 1u};
          break;
      }
      const std::string bump_context = context + " bumped=" + bumps[index].name;
      auto bumped_request = cp::build_request(std::move(bumped_spec));
      PROPERTY(bumped_request.has_value(),
               bump_context + ": the bumped request failed to build: " + bumped_request.status().to_string());
      if (!bumped_request.has_value()) {
        continue;
      }
      const cp::GenerationBindings observed = bumped_request.value().current_bindings();
      const cp::PlanFreshness freshness = cp::assess_freshness(*outcome.plan, observed);
      PROPERTY(freshness == bumps[index].freshness,
               bump_context + ": expected freshness " + cp::to_string(bumps[index].freshness) + ", got " +
                   cp::to_string(freshness));
      cp::ErrorCode code = cp::ErrorCode::kInternalError;
      cp::describe_freshness(bumps[index].freshness, code);
      PROPERTY(code == bumps[index].code, bump_context + ": the freshness class maps to the wrong error code");

      const cp::Status status = cp::validate_plan(*outcome.plan, bumped_request.value());
      PROPERTY(!status.is_ok(), bump_context + ": a plan still validates against a bumped request");
      PROPERTY(cp::category_of(status.code()) == cp::ErrorCategory::kAuthority,
               bump_context + ": validate_plan refused the plan with a non-authority code " + status.to_string());
    }
  }
  std::printf("SYNTHETIC generation family: %zu plans fenced against all five generation fields\n", fenced);
  PROPERTY(fenced > kPropertyIterations / 2u, "too few plans to exercise the generation fences");
}
