// Collective Path Planner - deterministic unit tests for model and state-machine semantics.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
//
// Every fabric, collective and policy built here is SYNTHETIC: generated by this
// test, never measured on a device. The suite is deterministic: the runner seed
// only feeds the reproducible shuffles used by the canonicalisation proofs, so a
// randomised failure always reports the seed that produced it.
#include <algorithm>
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include "cpath/buffer.hpp"
#include "cpath/collective.hpp"
#include "cpath/digest.hpp"
#include "cpath/dsl.hpp"
#include "cpath/explain.hpp"
#include "cpath/fabric.hpp"
#include "cpath/ids.hpp"
#include "cpath/limits.hpp"
#include "cpath/plan.hpp"
#include "cpath/planner.hpp"
#include "cpath/policy.hpp"
#include "cpath/request.hpp"
#include "cpath/status.hpp"
#include "fixtures.hpp"
#include "test_framework.hpp"

namespace cp = cpath;
namespace ct = cpath_test;

namespace {

// --- diagnostics -----------------------------------------------------------

std::string code_of(const cp::Status& status) { return std::string(cp::code_symbol(status.code())); }
std::string symbol_of(cp::ErrorCode code) { return std::string(cp::code_symbol(code)); }

// Records a failure - without aborting the test - when a call did not fail with
// exactly the expected code.
void check_rejected(const cp::Status& status, cp::ErrorCode expected, const std::string& context) {
  if (status.code() != expected) {
    ct::record_failure(__FILE__, __LINE__, context + ": expected " + symbol_of(expected) + " but got " +
                                                 code_of(status) + " (" + status.detail() + ")");
  }
}

template <class T>
void check_rejected(const cp::Result<T>& result, cp::ErrorCode expected, const std::string& context) {
  if (result.has_value()) {
    ct::record_failure(__FILE__, __LINE__,
                       context + ": expected " + symbol_of(expected) + " but the call succeeded");
    return;
  }
  check_rejected(result.status(), expected, context);
}

// Aborts the test when a Result carries no value; used when every later
// assertion depends on that value. Returns by value so that binding it to a
// const reference cannot outlive the temporary Result it came from.
template <class T>
T require_value(const cp::Result<T>& result, const std::string& context) {
  if (!result.has_value()) {
    CPATH_FAIL(context + ": unexpected failure " + result.status().to_string());
  }
  return result.value();
}

// --- synthetic model helpers ----------------------------------------------

cp::Node make_node(const std::string& id, const std::string& rack = std::string()) {
  cp::Node node;
  node.id = cp::NodeId{id};
  if (!rack.empty()) {
    node.placement.supplied = true;
    node.placement.site = "S0";
    node.placement.rack = rack;
    node.placement.host = id;
  }
  node.tier = cp::TierId{std::string("LEAF")};
  return node;
}

cp::Edge make_edge(const std::string& id, const std::string& from, const std::string& to) {
  cp::Edge edge;
  edge.id = cp::EdgeId{id};
  edge.from = cp::NodeId{from};
  edge.to = cp::NodeId{to};
  edge.capacity_mbps = 25000;
  edge.latency_micros = 100;
  edge.tier = cp::TierId{std::string("LEAF")};
  edge.evidence = cp::EvidenceClass::kSynthetic;
  return edge;
}

cp::FailureDomain make_domain(const std::string& id, cp::DomainKind kind, const std::string& parent) {
  cp::FailureDomain domain;
  domain.id = cp::FailureDomainId{id};
  domain.kind = kind;
  if (!parent.empty()) {
    domain.parent = cp::FailureDomainId{parent};
  }
  return domain;
}

// Two nodes joined by one edge in each direction: the smallest graph the model
// accepts. SYNTHETIC.
cp::FabricSpec two_node_fabric() {
  cp::FabricSpec spec;
  spec.topology_generation = cp::TopologyGeneration{7};
  spec.failure_domain_generation = cp::FailureDomainGeneration{3};
  spec.capacity_evidence_generation = cp::CapacityEvidenceGeneration{11};
  spec.nodes.push_back(make_node("n0"));
  spec.nodes.push_back(make_node("n1"));
  spec.edges.push_back(make_edge("e0", "n0", "n1"));
  spec.edges.push_back(make_edge("e1", "n1", "n0"));
  return spec;
}

// A ring collective declared in the given member order, so that ring rotation
// can be exercised. SYNTHETIC.
cp::CollectiveSpec ring_collective(const std::vector<std::string>& members) {
  cp::CollectiveSpec spec;
  spec.id = cp::CollectiveId{std::string("c0")};
  spec.kind = cp::CollectiveKind::kRing;
  cp::GroupSpec group;
  group.id = cp::GroupId{std::string("g0")};
  group.level = 0;
  group.pattern = cp::GroupPattern::kRing;
  for (const std::string& member : members) {
    group.members.push_back(cp::ParticipantId{member});
  }
  spec.groups.push_back(std::move(group));
  return spec;
}

std::vector<std::uint8_t> canonical_bytes(const cp::Collective& collective) {
  cp::ByteWriter writer;
  collective.encode_canonical(writer);
  return writer.bytes();
}

std::vector<std::string> edge_names(const cp::Collective& collective) {
  std::vector<std::string> names;
  names.reserve(collective.logical_edges.size());
  for (const cp::LogicalEdge& edge : collective.logical_edges) {
    names.push_back(edge.src.value() + ">" + edge.dst.value());
  }
  return names;
}

template <class T>
void shuffle(std::vector<T>& values, ct::Random& rng) {
  for (std::size_t remaining = values.size(); remaining > 1; --remaining) {
    const std::size_t other = static_cast<std::size_t>(rng.below(remaining));
    std::swap(values[remaining - 1], values[other]);
  }
}

// --- text DSL helpers ------------------------------------------------------

std::string replace_first(const std::string& text, const std::string& from, const std::string& to) {
  const std::size_t position = text.find(from);
  if (position == std::string::npos) {
    return text;
  }
  return text.substr(0, position) + to + text.substr(position + from.size());
}

// Inserts a line directly after the named section header, which is where the
// reader attributes it.
std::string insert_after_section(const std::string& text, const std::string& section, const std::string& line) {
  const std::string marker = "\n[" + section + "]\n";
  const std::size_t position = text.find(marker);
  if (position == std::string::npos) {
    return text;
  }
  return text.substr(0, position + marker.size()) + line + "\n" + text.substr(position + marker.size());
}

struct RejectionCase {
  const char* label;
  cp::ErrorCode expected;
  std::string text;
};

void check_rejection_case(const RejectionCase& item) {
  const cp::Result<cp::PlanningRequest> parsed = cp::parse_request_text(item.text);
  if (parsed.has_value()) {
    ct::record_failure(__FILE__, __LINE__, std::string(item.label) + ": expected " + symbol_of(item.expected) +
                                                 " but the request parsed successfully");
    return;
  }
  if (parsed.status().code() != item.expected) {
    ct::record_failure(__FILE__, __LINE__, std::string(item.label) + ": expected " + symbol_of(item.expected) +
                                                 " but got " + code_of(parsed.status()) + " (" +
                                                 parsed.status().detail() + ")");
  }
}

// --- plan helpers ----------------------------------------------------------

cp::GenerationBindings sample_bindings() {
  cp::GenerationBindings bindings;
  bindings.topology = cp::TopologyGeneration{7};
  bindings.failure_domains = cp::FailureDomainGeneration{3};
  bindings.capacity_evidence = cp::CapacityEvidenceGeneration{11};
  bindings.policy = cp::PolicyGeneration{5};
  bindings.plan = cp::CollectivePlanGeneration{1};
  return bindings;
}

cp::Plan plan_with_bindings(const cp::GenerationBindings& bindings) {
  cp::Plan plan;
  const cp::Digest digest = cp::Sha256::hash("synthetic-plan");
  plan.id = cp::CollectivePlanId{digest};
  plan.input_digest = digest;
  plan.generation = cp::CollectivePlanGeneration{1};
  plan.bindings = bindings;
  plan.collective = cp::CollectiveId{std::string("c0")};
  return plan;
}

// The diamond fabric used by the plan-comparison proofs: a single tree logical
// edge p0 -> p1 with two disjoint physical routes whose latency is set by the
// caller. SYNTHETIC.
cp::RequestSpec diamond_request(std::uint64_t fast_latency, std::uint64_t slow_latency) {
  cp::RequestSpec spec;
  spec.fabric.topology_generation = cp::TopologyGeneration{7};
  spec.fabric.failure_domain_generation = cp::FailureDomainGeneration{3};
  spec.fabric.capacity_evidence_generation = cp::CapacityEvidenceGeneration{11};
  spec.policy.generation = cp::PolicyGeneration{5};
  spec.plan_generation = cp::CollectivePlanGeneration{1};
  spec.fabric.failure_domains.push_back(make_domain("S0", cp::DomainKind::kSite, std::string()));
  spec.fabric.failure_domains.push_back(make_domain("R0", cp::DomainKind::kRack, "S0"));
  for (const char* id : {"n0", "a", "b", "n1"}) {
    spec.fabric.nodes.push_back(make_node(id, "R0"));
  }
  const auto route = [&spec](const std::string& id, const std::string& from, const std::string& to,
                             std::uint64_t latency) {
    cp::Edge edge = make_edge(id, from, to);
    edge.latency_micros = latency;
    edge.failure_domain = cp::FailureDomainId{std::string("R0")};
    spec.fabric.edges.push_back(std::move(edge));
  };
  route("e0", "n0", "a", fast_latency);
  route("e1", "a", "n1", fast_latency);
  route("e2", "n0", "b", slow_latency);
  route("e3", "b", "n1", slow_latency);

  spec.collective.id = cp::CollectiveId{std::string("c0")};
  spec.collective.kind = cp::CollectiveKind::kTree;
  cp::GroupSpec group;
  group.id = cp::GroupId{std::string("g0")};
  group.level = 0;
  group.pattern = cp::GroupPattern::kTree;
  group.direction = cp::TreeDirection::kForward;
  group.root = cp::ParticipantId{std::string("p0")};
  group.members.push_back(cp::ParticipantId{std::string("p0")});
  group.members.push_back(cp::ParticipantId{std::string("p1")});
  spec.collective.groups.push_back(std::move(group));

  cp::EndpointBinding source;
  source.participant = cp::ParticipantId{std::string("p0")};
  source.node = cp::NodeId{std::string("n0")};
  spec.bindings.push_back(std::move(source));
  cp::EndpointBinding target;
  target.participant = cp::ParticipantId{std::string("p1")};
  target.node = cp::NodeId{std::string("n1")};
  spec.bindings.push_back(std::move(target));
  return spec;
}

}  // namespace

// ===========================================================================
// Strong identities
// ===========================================================================

CPATH_TEST(UnitIds, default_constructed_ids_are_invalid) {
  const cp::NodeId node{};
  CPATH_CHECK(!node.valid());
  CPATH_CHECK(!cp::NodeId{std::string()}.valid());
  CPATH_CHECK(cp::NodeId{std::string("n0")}.valid());

  const cp::LogicalEdgeId logical{};
  CPATH_CHECK(!logical.valid());
  CPATH_CHECK(!cp::LogicalEdgeId{0u}.valid());
  CPATH_CHECK(cp::LogicalEdgeId{1u}.valid());

  const cp::TopologyGeneration generation{};
  CPATH_CHECK(!generation.valid());
  CPATH_CHECK(cp::TopologyGeneration{1u}.valid());

  const cp::ParticipantId participant{};
  CPATH_CHECK(!participant.valid());
  CPATH_CHECK(!cp::EdgeId{std::string()}.valid());
  CPATH_CHECK(!cp::TierId{std::string()}.valid());
  CPATH_CHECK(!cp::FailureDomainId{std::string()}.valid());

  CPATH_CHECK_EQ(cp::to_string(cp::NodeId{std::string("n7")}), std::string("n7"));
  CPATH_CHECK_EQ(cp::to_decimal(cp::TopologyGeneration{42u}), std::string("42"));
}

CPATH_TEST(UnitIds, digest_backed_plan_id_validity) {
  const cp::CollectivePlanId empty{};
  CPATH_CHECK(!empty.valid());
  CPATH_CHECK(!cp::CollectivePlanId{cp::Digest{}}.valid());

  const cp::Digest digest = cp::Sha256::hash(std::string_view("abc"));
  const cp::CollectivePlanId plan_id{digest};
  CPATH_CHECK(plan_id.valid());
  CPATH_CHECK_EQ(cp::to_string(plan_id), digest.hex());
  CPATH_CHECK_EQ(plan_id.value().hex(),
                 std::string("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"));
}

CPATH_TEST(UnitIds, ordering_and_hashing_are_stable) {
  std::vector<cp::NodeId> ids;
  ids.push_back(cp::NodeId{std::string("nc")});
  ids.push_back(cp::NodeId{std::string("na")});
  ids.push_back(cp::NodeId{std::string("nb")});
  std::sort(ids.begin(), ids.end());
  CPATH_CHECK_EQ(ids[0].value(), std::string("na"));
  CPATH_CHECK_EQ(ids[1].value(), std::string("nb"));
  CPATH_CHECK_EQ(ids[2].value(), std::string("nc"));
  CPATH_CHECK(ids[0] < ids[1]);
  CPATH_CHECK(ids[1] < ids[2]);
  CPATH_CHECK(!(ids[0] < ids[0]));

  const cp::NodeId copy = ids[1];
  CPATH_CHECK(copy == ids[1]);
  // Equal identities hash equally, and the hash only depends on the value.
  const cp::StrongIdHash<cp::NodeIdTag, std::string> node_hasher;
  CPATH_CHECK_EQ(node_hasher(copy), node_hasher(ids[1]));
  CPATH_CHECK_EQ(node_hasher(ids[1]), std::hash<std::string>{}(std::string("nb")));

  const cp::Digest digest = cp::Sha256::hash(std::string_view("abc"));
  const cp::CollectivePlanId first{digest};
  const cp::CollectivePlanId second{cp::Sha256::hash(std::string_view("abc"))};
  CPATH_CHECK(first == second);
  const cp::StrongIdHash<cp::CollectivePlanIdTag, cp::Digest> plan_hasher;
  CPATH_CHECK_EQ(plan_hasher(first), cp::DigestHash{}(digest));
}

CPATH_TEST(UnitIds, id_map_matches_equal_identities) {
  cp::IdMap<cp::NodeId> map;
  map.emplace(cp::NodeId{std::string("n0")}, 0u);
  map.emplace(cp::NodeId{std::string("n1")}, 1u);
  map.emplace(cp::NodeId{std::string("n2")}, 2u);

  const auto found = map.find(cp::NodeId{std::string("n1")});
  CPATH_REQUIRE(found != map.end());
  CPATH_CHECK_EQ(found->second, std::uint32_t{1});
  CPATH_CHECK(map.find(cp::NodeId{std::string("n9")}) == map.end());
  // An invalid sentinel never aliases a stored identity.
  CPATH_CHECK(map.find(cp::NodeId{}) == map.end());
}

// ===========================================================================
// Canonical byte encoding
// ===========================================================================

CPATH_TEST(UnitBuffer, identical_values_encode_identically) {
  const cp::Digest digest = cp::Sha256::hash(std::string_view("payload"));
  cp::ByteWriter first;
  cp::ByteWriter second;
  for (cp::ByteWriter* writer : {&first, &second}) {
    writer->u8(0xABu);
    writer->u16(0x1234u);
    writer->u32(0x12345678u);
    writer->u64(0x0123456789ABCDEFull);
    writer->boolean(true);
    writer->boolean(false);
    writer->string(std::string_view("collective"));
    writer->digest(digest);
    writer->tagged(std::string_view("fabric.v1"));
  }
  CPATH_CHECK_EQ(first.size(), second.size());
  CPATH_CHECK(first.bytes() == second.bytes());
  CPATH_CHECK_EQ(first.sha256().hex(), second.sha256().hex());

  cp::ByteWriter different;
  different.u8(0xABu);
  CPATH_CHECK(!(different.bytes() == first.bytes()));
  CPATH_CHECK(different.sha256() != first.sha256());
  CPATH_CHECK(first.bytes().size() == first.size());
}

CPATH_TEST(UnitBuffer, integers_are_little_endian) {
  cp::ByteWriter writer;
  writer.u16(0x0102u);
  writer.u32(0x03040506u);
  writer.u64(0x0708090A0B0C0D0Eu);
  const std::vector<std::uint8_t> expected = {0x02u, 0x01u,                              // u16
                                              0x06u, 0x05u, 0x04u, 0x03u,                // u32
                                              0x0Eu, 0x0Du, 0x0Cu, 0x0Bu, 0x0Au, 0x09u, 0x08u, 0x07u};
  CPATH_CHECK(writer.bytes() == expected);

  cp::ByteReader reader(writer.bytes());
  std::uint16_t short_value = 0;
  std::uint32_t word = 0;
  std::uint64_t wide = 0;
  CPATH_REQUIRE(reader.u16(short_value).is_ok());
  CPATH_REQUIRE(reader.u32(word).is_ok());
  CPATH_REQUIRE(reader.u64(wide).is_ok());
  CPATH_CHECK_EQ(short_value, std::uint16_t{0x0102u});
  CPATH_CHECK_EQ(word, std::uint32_t{0x03040506u});
  CPATH_CHECK_EQ(wide, std::uint64_t{0x0708090A0B0C0D0Eu});
  CPATH_CHECK(reader.require_end().is_ok());
  CPATH_CHECK(reader.at_end());
  CPATH_CHECK_EQ(reader.remaining(), std::size_t{0});
}

CPATH_TEST(UnitBuffer, count_rejects_over_large_counts) {
  cp::ByteWriter writer;
  writer.u32(11u);
  const std::vector<std::uint8_t> bytes = writer.bytes();

  cp::ByteReader rejected(bytes);
  std::uint32_t value = 0;
  check_rejected(rejected.count(value, 10u), cp::ErrorCode::kTooManyItems, "count above the accepted bound");

  cp::ByteReader accepted(bytes);
  CPATH_REQUIRE(accepted.count(value, 11u).is_ok());
  CPATH_CHECK_EQ(value, std::uint32_t{11u});

  cp::ByteReader generous(bytes);
  CPATH_REQUIRE(generous.count(value, 4096u).is_ok());
  CPATH_CHECK_EQ(value, std::uint32_t{11u});
  CPATH_CHECK(generous.at_end());
}

CPATH_TEST(UnitBuffer, string_rejects_over_long_strings) {
  const std::string oversized(cp::kMaxIdentifierBytes + 1u, 'x');
  cp::ByteWriter writer;
  writer.string(oversized);
  const std::vector<std::uint8_t> bytes = writer.bytes();

  cp::ByteReader rejected(bytes);
  std::string value;
  check_rejected(rejected.string(value), cp::ErrorCode::kStringTooLong, "string above the default bound");

  cp::ByteReader accepted(bytes);
  CPATH_REQUIRE(accepted.string(value, oversized.size()).is_ok());
  CPATH_CHECK_EQ(value, oversized);

  cp::ByteReader exact(bytes);
  CPATH_REQUIRE(exact.string(value, cp::kMaxIdentifierBytes + 1u).is_ok());
  CPATH_CHECK_EQ(value.size(), oversized.size());
}

CPATH_TEST(UnitBuffer, require_end_rejects_trailing_bytes) {
  cp::ByteWriter writer;
  writer.u8(1u);
  writer.u8(2u);
  const std::vector<std::uint8_t> bytes = writer.bytes();

  cp::ByteReader reader(bytes);
  std::uint8_t value = 0;
  CPATH_REQUIRE(reader.u8(value).is_ok());
  CPATH_CHECK(!reader.at_end());
  check_rejected(reader.require_end(), cp::ErrorCode::kTrailingGarbage, "trailing byte");

  cp::ByteReader exact(bytes);
  std::span<const std::uint8_t> view;
  CPATH_REQUIRE(exact.raw(bytes.size(), view).is_ok());
  CPATH_CHECK(exact.require_end().is_ok());
}

CPATH_TEST(UnitBuffer, read_failure_poisons_later_reads) {
  cp::ByteReader empty(nullptr, 0u);
  std::uint8_t byte = 0;
  const cp::Status first = empty.u8(byte);
  CPATH_CHECK_EQ(code_of(first), symbol_of(cp::ErrorCode::kTruncatedRecord));

  std::uint64_t wide = 0;
  std::string text;
  cp::Digest digest;
  const cp::Status second = empty.u64(wide);
  const cp::Status third = empty.string(text);
  const cp::Status fourth = empty.digest(digest);
  // Every later read reports exactly the first failure, never a different one.
  CPATH_CHECK(second == first);
  CPATH_CHECK(third == first);
  CPATH_CHECK(fourth == first);
  // require_end() would otherwise succeed here (the reader is at its end); a
  // poisoned reader must still report the original failure.
  CPATH_CHECK(empty.at_end());
  CPATH_CHECK(empty.require_end() == first);
  CPATH_CHECK(empty.status() == first);

  cp::ByteReader sized(reinterpret_cast<const std::uint8_t*>("ab"), 2u);
  std::string captured;
  const cp::Status truncation = sized.string(captured);
  CPATH_CHECK_EQ(code_of(truncation), symbol_of(cp::ErrorCode::kTruncatedRecord));
  std::uint32_t word = 0;
  CPATH_CHECK(sized.u32(word) == truncation);
}

CPATH_TEST(UnitBuffer, checked_helpers_never_truncate) {
  CPATH_CHECK(cp::fits_u32(0u));
  CPATH_CHECK(cp::fits_u32(0xFFFFFFFFu));
  CPATH_CHECK(!cp::fits_u32(0x100000000ull));

  std::uint64_t out = 0;
  CPATH_CHECK(cp::checked_add_u64(1u, 2u, cp::kCostCeiling, out).is_ok());
  CPATH_CHECK_EQ(out, std::uint64_t{3u});
  const cp::Status overflow = cp::checked_add_u64(cp::kCostCeiling, 1u, cp::kCostCeiling, out);
  CPATH_CHECK_EQ(code_of(overflow), symbol_of(cp::ErrorCode::kOverflow));
  CPATH_CHECK_EQ(out, cp::kCostCeiling);
}

// ===========================================================================
// Digests and saturating arithmetic
// ===========================================================================

CPATH_TEST(UnitDigest, sha256_matches_published_vectors) {
  CPATH_CHECK_EQ(cp::Sha256::hash(std::string_view()).hex(),
                 std::string("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"));
  CPATH_CHECK_EQ(cp::Sha256::hash(std::string_view("abc")).hex(),
                 std::string("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"));
  // 56 bytes: crosses the padding boundary of a single block.
  CPATH_CHECK_EQ(cp::Sha256::hash(std::string_view("abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq")).hex(),
                 std::string("248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"));
  CPATH_CHECK(cp::Sha256::hash(std::string_view("abc")).is_zero() == false);
  CPATH_CHECK(cp::Digest{}.is_zero());
}

CPATH_TEST(UnitDigest, sha256_incremental_matches_one_shot) {
  cp::Sha256 hasher;
  hasher.update(std::string_view("a"));
  hasher.update(std::string_view("b"));
  hasher.update(std::string_view("c"));
  CPATH_CHECK_EQ(hasher.finish().hex(), cp::Sha256::hash(std::string_view("abc")).hex());

  // A long input split at an awkward boundary must still hash identically.
  std::string payload;
  for (int index = 0; index < 200; ++index) {
    payload += "collective-path-planner/";
  }
  cp::Sha256 incremental;
  const std::size_t split = 63u;
  incremental.update(std::string_view(payload).substr(0, split));
  incremental.update(std::string_view(payload).substr(split));
  CPATH_CHECK_EQ(incremental.finish().hex(), cp::Sha256::hash(std::string_view(payload)).hex());
  CPATH_CHECK(payload.size() > 64u);
}

CPATH_TEST(UnitDigest, crc32_and_fnv1a64_known_values) {
  const std::string_view check = "123456789";
  CPATH_CHECK_EQ(cp::crc32(reinterpret_cast<const std::uint8_t*>(check.data()), check.size()),
                 std::uint32_t{0xCBF43926u});
  CPATH_CHECK_EQ(cp::crc32(nullptr, 0u), std::uint32_t{0u});
  CPATH_CHECK_EQ(cp::fnv1a64(std::string_view()), std::uint64_t{0xCBF29CE484222325ull});
  CPATH_CHECK_EQ(cp::fnv1a64(std::string_view("a")), std::uint64_t{0xAF63DC4C8601EC8Cull});
  CPATH_CHECK(cp::fnv1a64(std::string_view("abc")) != cp::fnv1a64(std::string_view("abd")));
}

CPATH_TEST(UnitDigest, from_hex_round_trips_and_rejects_bad_input) {
  const cp::Digest digest = cp::Sha256::hash(std::string_view("abc"));
  const std::string text = digest.hex();
  CPATH_CHECK_EQ(text.size(), std::size_t{64});
  const cp::Digest decoded = require_value(cp::Digest::from_hex(text), "digest round trip");
  CPATH_CHECK(decoded == digest);
  CPATH_CHECK_EQ(decoded.hex(), text);
  CPATH_CHECK_EQ(cp::Digest::from_hex(text).value().short_id(), digest.short_id());

  // Documented decision: hexadecimal input is case-insensitive on decode, the
  // canonical rendering is always lower case.
  std::string upper = text;
  for (char& ch : upper) {
    if (ch >= 'a' && ch <= 'f') {
      ch = static_cast<char>(ch - 'a' + 'A');
    }
  }
  CPATH_CHECK(upper != text);
  CPATH_CHECK(require_value(cp::Digest::from_hex(upper), "upper case digest") == digest);

  check_rejected(cp::Digest::from_hex(text.substr(0, 63)), cp::ErrorCode::kInvalidSyntax, "63 hex characters");
  check_rejected(cp::Digest::from_hex(text + "0"), cp::ErrorCode::kInvalidSyntax, "65 hex characters");
  check_rejected(cp::Digest::from_hex(std::string_view()), cp::ErrorCode::kInvalidSyntax, "empty digest text");
  check_rejected(cp::Digest::from_hex(replace_first(text, "b", "z")), cp::ErrorCode::kInvalidCharacter,
                 "non hex character");
  check_rejected(cp::Digest::from_hex("0x" + text.substr(2)), cp::ErrorCode::kInvalidCharacter, "0x prefix");
}

CPATH_TEST(UnitDigest, saturating_helpers_never_wrap) {
  CPATH_CHECK_EQ(cp::saturating_add(5u, 3u, 10u), std::uint64_t{8u});
  CPATH_CHECK_EQ(cp::saturating_add(9u, 9u, 10u), std::uint64_t{10u});
  CPATH_CHECK_EQ(cp::saturating_add(10u, 0u, 10u), std::uint64_t{10u});
  CPATH_CHECK_EQ(cp::saturating_add(0u, 10u, 10u), std::uint64_t{10u});
  CPATH_CHECK_EQ(cp::saturating_mul(0u, 7u, 10u), std::uint64_t{0u});
  CPATH_CHECK_EQ(cp::saturating_mul(3u, 4u, 100u), std::uint64_t{12u});
  CPATH_CHECK_EQ(cp::saturating_mul(3u, 4u, 10u), std::uint64_t{10u});
  CPATH_CHECK_EQ(cp::saturating_mul(10u, 10u, 10u), std::uint64_t{10u});
  CPATH_CHECK_EQ(cp::saturating_sub(9u, 4u), std::uint64_t{5u});
  CPATH_CHECK_EQ(cp::saturating_sub(4u, 9u), std::uint64_t{0u});
  CPATH_CHECK_EQ(cp::saturating_sub(0u, 0u), std::uint64_t{0u});

  // Property: over the whole plausible scoring range the results saturate
  // exactly at the ceiling and never wrap around it.
  ct::Random rng = ct::make_random(1);
  for (int iteration = 0; iteration < 2000; ++iteration) {
    const std::uint64_t lhs = rng.below(cp::kCostCeiling);
    const std::uint64_t rhs = rng.below(cp::kCostCeiling);

    const std::uint64_t sum = cp::saturating_add(lhs, rhs, cp::kCostCeiling);
    CPATH_CHECK(sum <= cp::kCostCeiling);
    CPATH_CHECK(sum >= lhs);
    CPATH_CHECK(sum >= rhs);
    if (lhs <= cp::kCostCeiling - rhs) {
      CPATH_CHECK_EQ(sum, lhs + rhs);
    } else {
      CPATH_CHECK_EQ(sum, cp::kCostCeiling);
    }

    const std::uint64_t product = cp::saturating_mul(lhs, rhs, cp::kCostCeiling);
    CPATH_CHECK(product <= cp::kCostCeiling);
    if (lhs == 0u || rhs == 0u) {
      CPATH_CHECK_EQ(product, std::uint64_t{0u});
    } else if (lhs <= cp::kCostCeiling / rhs) {
      CPATH_CHECK_EQ(product, lhs * rhs);
    } else {
      CPATH_CHECK_EQ(product, cp::kCostCeiling);
    }

    CPATH_CHECK_EQ(cp::saturating_sub(lhs, rhs), lhs > rhs ? lhs - rhs : 0u);
  }
}

// ===========================================================================
// Fabric canonicalisation
// ===========================================================================

CPATH_TEST(UnitFabric, build_canonicalises_nodes_and_edges) {
  cp::FabricSpec spec;
  spec.nodes.push_back(make_node("n2"));
  spec.nodes.push_back(make_node("n0"));
  spec.nodes.push_back(make_node("n1"));
  spec.edges.push_back(make_edge("e9", "n1", "n2"));
  spec.edges.push_back(make_edge("e5", "n0", "n1"));
  spec.edges.push_back(make_edge("e2", "n0", "n1"));

  const cp::Result<cp::FabricGraph> built = cp::FabricGraph::build(spec);
  const cp::FabricGraph& graph = require_value(built, "canonical fabric");
  CPATH_REQUIRE_EQ(graph.node_count(), std::size_t{3});
  CPATH_CHECK_EQ(graph.nodes()[0].id.value(), std::string("n0"));
  CPATH_CHECK_EQ(graph.nodes()[1].id.value(), std::string("n1"));
  CPATH_CHECK_EQ(graph.nodes()[2].id.value(), std::string("n2"));
  CPATH_REQUIRE_EQ(graph.edge_count(), std::size_t{3});
  CPATH_CHECK_EQ(graph.edges()[0].id.value(), std::string("e2"));
  CPATH_CHECK_EQ(graph.edges()[1].id.value(), std::string("e5"));
  CPATH_CHECK_EQ(graph.edges()[2].id.value(), std::string("e9"));
  CPATH_CHECK(graph.validate().is_ok());

  const std::uint32_t index = graph.node_index(cp::NodeId{std::string("n0")});
  CPATH_REQUIRE(index != cp::kInvalidIndex);
  CPATH_REQUIRE_EQ(graph.out_edges(index).size(), std::size_t{2});
  CPATH_CHECK_EQ(graph.edges()[graph.out_edges(index)[0]].id.value(), std::string("e2"));
  CPATH_CHECK_EQ(graph.edges()[graph.out_edges(index)[1]].id.value(), std::string("e5"));
  CPATH_CHECK_EQ(graph.node_index(cp::NodeId{std::string("n9")}), cp::kInvalidIndex);
  CPATH_CHECK(graph.find_node(cp::NodeId{std::string("n1")}) != nullptr);
  CPATH_CHECK(graph.find_node(cp::NodeId{std::string("n9")}) == nullptr);
  CPATH_CHECK(graph.find_edge(cp::EdgeId{std::string("e5")}) != nullptr);
  CPATH_CHECK(graph.find_edge(cp::EdgeId{std::string("e6")}) == nullptr);

  // The same fabric declared in a different order encodes to the same bytes.
  cp::FabricSpec shuffled;
  shuffled.nodes.push_back(make_node("n1"));
  shuffled.nodes.push_back(make_node("n2"));
  shuffled.nodes.push_back(make_node("n0"));
  shuffled.edges.push_back(make_edge("e2", "n0", "n1"));
  shuffled.edges.push_back(make_edge("e9", "n1", "n2"));
  shuffled.edges.push_back(make_edge("e5", "n0", "n1"));
  const cp::FabricGraph& other = require_value(cp::FabricGraph::build(shuffled), "shuffled fabric");
  cp::ByteWriter first;
  cp::ByteWriter second;
  graph.encode_canonical(first);
  other.encode_canonical(second);
  CPATH_CHECK(first.bytes() == second.bytes());
}

CPATH_TEST(UnitFabric, duplicate_identifiers_are_rejected) {
  cp::FabricSpec duplicate_node = two_node_fabric();
  duplicate_node.nodes.push_back(make_node("n0"));
  check_rejected(cp::FabricGraph::build(duplicate_node), cp::ErrorCode::kDuplicateIdentifier, "duplicate node id");

  cp::FabricSpec duplicate_domain = two_node_fabric();
  duplicate_domain.failure_domains.push_back(make_domain("R0", cp::DomainKind::kRack, std::string()));
  duplicate_domain.failure_domains.push_back(make_domain("R0", cp::DomainKind::kRack, std::string()));
  check_rejected(cp::FabricGraph::build(duplicate_domain), cp::ErrorCode::kDuplicateIdentifier,
                 "duplicate failure domain id");

  cp::FabricSpec duplicate_edge = two_node_fabric();
  duplicate_edge.edges.push_back(make_edge("e0", "n0", "n1"));
  check_rejected(cp::FabricGraph::build(duplicate_edge), cp::ErrorCode::kDuplicateIdentifier, "duplicate edge id");
}

CPATH_TEST(UnitFabric, unknown_references_are_rejected) {
  cp::FabricSpec unknown_node = two_node_fabric();
  unknown_node.edges.push_back(make_edge("e2", "n0", "n7"));
  check_rejected(cp::FabricGraph::build(unknown_node), cp::ErrorCode::kUnknownReference, "edge to an unknown node");

  cp::FabricSpec unknown_domain = two_node_fabric();
  unknown_domain.failure_domains.push_back(make_domain("R0", cp::DomainKind::kRack, "S9"));
  check_rejected(cp::FabricGraph::build(unknown_domain), cp::ErrorCode::kUnknownReference,
                 "domain with an unknown parent");

  cp::FabricSpec unknown_edge_domain = two_node_fabric();
  cp::Edge edge = make_edge("e2", "n0", "n1");
  edge.failure_domain = cp::FailureDomainId{std::string("R7")};
  unknown_edge_domain.edges.push_back(edge);
  check_rejected(cp::FabricGraph::build(unknown_edge_domain), cp::ErrorCode::kUnknownReference,
                 "edge in an unknown failure domain");
}

CPATH_TEST(UnitFabric, self_loop_edge_is_rejected) {
  cp::FabricSpec spec = two_node_fabric();
  spec.edges.push_back(make_edge("e2", "n0", "n0"));
  check_rejected(cp::FabricGraph::build(spec), cp::ErrorCode::kInconsistentMetadata, "self loop edge");
}

CPATH_TEST(UnitFabric, reserved_above_capacity_is_rejected) {
  cp::FabricSpec spec = two_node_fabric();
  cp::Edge edge = make_edge("e2", "n0", "n1");
  edge.capacity_mbps = 1000;
  edge.reserved_mbps = 1001;
  spec.edges.push_back(edge);
  check_rejected(cp::FabricGraph::build(spec), cp::ErrorCode::kInconsistentMetadata,
                 "reserved capacity above verified capacity");

  cp::FabricSpec zero = two_node_fabric();
  cp::Edge unverified = make_edge("e2", "n0", "n1");
  unverified.capacity_mbps = 0;
  unverified.reserved_mbps = 1;
  zero.edges.push_back(unverified);
  check_rejected(cp::FabricGraph::build(zero), cp::ErrorCode::kInconsistentMetadata,
                 "reservation on an edge with no verified capacity");
}

CPATH_TEST(UnitFabric, failure_domain_cycle_is_rejected) {
  // A parent cycle can only be written with kinds that are not strictly
  // increasing around the loop, so the strict-containment rule is the guard
  // that fires. Either way the graph is refused, never silently accepted.
  cp::FabricSpec spec = two_node_fabric();
  spec.failure_domains.push_back(make_domain("A", cp::DomainKind::kRack, "B"));
  spec.failure_domains.push_back(make_domain("B", cp::DomainKind::kPod, "A"));
  check_rejected(cp::FabricGraph::build(spec), cp::ErrorCode::kInconsistentMetadata, "failure domain cycle");

  // A self-parenting domain is refused as well.
  cp::FabricSpec self_parent = two_node_fabric();
  self_parent.failure_domains.push_back(make_domain("A", cp::DomainKind::kRack, "A"));
  check_rejected(cp::FabricGraph::build(self_parent), cp::ErrorCode::kInconsistentMetadata,
                 "failure domain parented by itself");
}

CPATH_TEST(UnitFabric, parent_must_be_strictly_broader) {
  cp::FabricSpec same_kind = two_node_fabric();
  same_kind.failure_domains.push_back(make_domain("A", cp::DomainKind::kRack, std::string()));
  same_kind.failure_domains.push_back(make_domain("B", cp::DomainKind::kRack, "A"));
  check_rejected(cp::FabricGraph::build(same_kind), cp::ErrorCode::kInconsistentMetadata,
                 "parent of the same kind");

  cp::FabricSpec narrower = two_node_fabric();
  narrower.failure_domains.push_back(make_domain("A", cp::DomainKind::kPod, std::string()));
  narrower.failure_domains.push_back(make_domain("B", cp::DomainKind::kSite, "A"));
  check_rejected(cp::FabricGraph::build(narrower), cp::ErrorCode::kInconsistentMetadata, "narrower parent");

  // The full four level chain is legal.
  cp::FabricSpec chain = two_node_fabric();
  chain.failure_domains.push_back(make_domain("FD-SITE", cp::DomainKind::kSite, std::string()));
  chain.failure_domains.push_back(make_domain("FD-POD", cp::DomainKind::kPod, "FD-SITE"));
  chain.failure_domains.push_back(make_domain("FD-RACK", cp::DomainKind::kRack, "FD-POD"));
  chain.failure_domains.push_back(make_domain("FD-HOST", cp::DomainKind::kHost, "FD-RACK"));
  CPATH_CHECK(cp::FabricGraph::build(chain).has_value());
}

CPATH_TEST(UnitFabric, duplicate_physical_links_are_retained) {
  cp::FabricSpec spec = two_node_fabric();
  cp::Edge parallel = make_edge("e2", "n0", "n1");
  parallel.capacity_mbps = 40000;
  spec.edges.push_back(parallel);

  const cp::FabricGraph& graph = require_value(cp::FabricGraph::build(spec), "parallel links");
  CPATH_REQUIRE_EQ(graph.edge_count(), std::size_t{3});
  // Canonical order is (from, to, id): both n0 -> n1 links survive, e0 first.
  CPATH_CHECK_EQ(graph.edges()[0].id.value(), std::string("e0"));
  CPATH_CHECK_EQ(graph.edges()[1].id.value(), std::string("e2"));
  CPATH_CHECK_EQ(graph.edges()[2].id.value(), std::string("e1"));
  CPATH_CHECK_EQ(graph.edges()[1].capacity_mbps, std::uint64_t{40000u});
  const std::uint32_t index = graph.node_index(cp::NodeId{std::string("n0")});
  CPATH_REQUIRE(index != cp::kInvalidIndex);
  CPATH_CHECK_EQ(graph.out_edges(index).size(), std::size_t{2});
  CPATH_CHECK(graph.validate().is_ok());
}

CPATH_TEST(UnitFabric, domain_chain_and_contains_follow_the_hierarchy) {
  cp::FabricSpec spec = two_node_fabric();
  spec.failure_domains.push_back(make_domain("FD-SITE", cp::DomainKind::kSite, std::string()));
  spec.failure_domains.push_back(make_domain("FD-POD", cp::DomainKind::kPod, "FD-SITE"));
  spec.failure_domains.push_back(make_domain("FD-RACK", cp::DomainKind::kRack, "FD-POD"));
  spec.failure_domains.push_back(make_domain("FD-HOST", cp::DomainKind::kHost, "FD-RACK"));
  const cp::FabricGraph& graph = require_value(cp::FabricGraph::build(spec), "four level hierarchy");

  const cp::FailureDomainId host{std::string("FD-HOST")};
  const cp::FailureDomainId rack{std::string("FD-RACK")};
  const cp::FailureDomainId pod{std::string("FD-POD")};
  const cp::FailureDomainId site{std::string("FD-SITE")};

  const std::vector<cp::FailureDomainId>& chain = graph.domain_chain(host);
  CPATH_REQUIRE_EQ(chain.size(), std::size_t{4});
  CPATH_CHECK_EQ(chain[0].value(), std::string("FD-HOST"));
  CPATH_CHECK_EQ(chain[1].value(), std::string("FD-RACK"));
  CPATH_CHECK_EQ(chain[2].value(), std::string("FD-POD"));
  CPATH_CHECK_EQ(chain[3].value(), std::string("FD-SITE"));

  // A root domain has no parent of any kind: the chain is the domain itself,
  // self first.
  const std::vector<cp::FailureDomainId>& root_chain = graph.domain_chain(site);
  CPATH_REQUIRE_EQ(root_chain.size(), std::size_t{1});
  CPATH_CHECK_EQ(root_chain[0].value(), std::string("FD-SITE"));
  // An unknown domain has an empty chain rather than a dangling reference.
  CPATH_CHECK_EQ(graph.domain_chain(cp::FailureDomainId{std::string("FD-NONE")}).size(), std::size_t{0});

  CPATH_CHECK(graph.domain_contains(site, host));
  CPATH_CHECK(graph.domain_contains(rack, host));
  CPATH_CHECK(graph.domain_contains(host, host));
  CPATH_CHECK(!graph.domain_contains(host, rack));
  CPATH_CHECK(!graph.domain_contains(pod, site));
  CPATH_CHECK(!graph.domain_contains(cp::FailureDomainId{}, host));
  CPATH_CHECK(!graph.domain_contains(site, cp::FailureDomainId{}));
  CPATH_CHECK_EQ(std::string(cp::to_string(graph.find_failure_domain(rack)->kind)), std::string("rack"));
}

// ===========================================================================
// Collective canonicalisation
// ===========================================================================

CPATH_TEST(UnitCollective, ring_rotation_is_canonical) {
  const cp::Collective& from_zero = require_value(cp::Collective::build(ring_collective({"p0", "p1", "p2", "p3"})),
                                                 "ring starting at p0");
  const cp::Collective& from_two = require_value(cp::Collective::build(ring_collective({"p2", "p3", "p0", "p1"})),
                                                "ring starting at p2");
  // Entering the same cycle at a different member is the same collective.
  CPATH_CHECK(canonical_bytes(from_zero) == canonical_bytes(from_two));
  CPATH_CHECK(edge_names(from_zero) == edge_names(from_two));
  CPATH_REQUIRE_EQ(from_two.groups.size(), std::size_t{1});
  CPATH_CHECK_EQ(from_two.groups[0].members[0].value(), std::string("p0"));
  CPATH_CHECK_EQ(from_two.groups[0].members[3].value(), std::string("p3"));

  const std::vector<std::string> expected = {"p0>p1", "p1>p2", "p2>p3", "p3>p0"};
  CPATH_CHECK(edge_names(from_zero) == expected);
  CPATH_CHECK(from_zero.validate().is_ok());
  CPATH_REQUIRE_EQ(from_zero.stage_count, std::uint32_t{1});
  CPATH_CHECK(from_zero.logical_edge_id(0) == cp::LogicalEdgeId{1u});
  CPATH_CHECK(from_zero.logical_edge_id(3) == cp::LogicalEdgeId{4u});
}

CPATH_TEST(UnitCollective, ring_reversal_changes_the_encoding) {
  const cp::Collective& forward = require_value(cp::Collective::build(ring_collective({"p0", "p1", "p2", "p3"})),
                                                "forward ring");
  const cp::Collective& reverse = require_value(cp::Collective::build(ring_collective({"p0", "p3", "p2", "p1"})),
                                                "reversed ring");
  CPATH_CHECK(!(canonical_bytes(forward) == canonical_bytes(reverse)));
  // Reversal changes the direction of every logical edge.
  const std::vector<std::string> expected = {"p0>p3", "p1>p0", "p2>p1", "p3>p2"};
  CPATH_CHECK(edge_names(reverse) == expected);
  CPATH_CHECK(edge_names(forward) != edge_names(reverse));
  CPATH_CHECK_EQ(reverse.participants.size(), std::size_t{4});
}

CPATH_TEST(UnitCollective, tree_directions_produce_the_declared_edge_sets) {
  const auto tree = [](cp::TreeDirection direction) {
    cp::CollectiveSpec spec;
    spec.id = cp::CollectiveId{std::string("t0")};
    spec.kind = cp::CollectiveKind::kTree;
    cp::GroupSpec group;
    group.id = cp::GroupId{std::string("g0")};
    group.level = 0;
    group.pattern = cp::GroupPattern::kTree;
    group.direction = direction;
    group.root = cp::ParticipantId{std::string("p0")};
    group.members.push_back(cp::ParticipantId{std::string("p2")});
    group.members.push_back(cp::ParticipantId{std::string("p0")});
    group.members.push_back(cp::ParticipantId{std::string("p1")});
    spec.groups.push_back(std::move(group));
    return spec;
  };

  const cp::Collective& forward =
      require_value(cp::Collective::build(tree(cp::TreeDirection::kForward)), "forward tree");
  CPATH_CHECK(edge_names(forward) == std::vector<std::string>({"p0>p1", "p0>p2"}));

  const cp::Collective& reverse =
      require_value(cp::Collective::build(tree(cp::TreeDirection::kReverse)), "reverse tree");
  CPATH_CHECK(edge_names(reverse) == std::vector<std::string>({"p1>p0", "p2>p0"}));

  const cp::Collective& both =
      require_value(cp::Collective::build(tree(cp::TreeDirection::kBidirectional)), "bidirectional tree");
  CPATH_CHECK(edge_names(both) == std::vector<std::string>({"p0>p1", "p0>p2", "p1>p0", "p2>p0"}));

  cp::CollectiveSpec missing_root = tree(cp::TreeDirection::kForward);
  missing_root.groups[0].root = cp::ParticipantId{};
  check_rejected(cp::Collective::build(missing_root), cp::ErrorCode::kMissingRequiredField, "tree without a root");

  cp::CollectiveSpec foreign_root = tree(cp::TreeDirection::kForward);
  foreign_root.groups[0].root = cp::ParticipantId{std::string("p9")};
  check_rejected(cp::Collective::build(foreign_root), cp::ErrorCode::kUnknownReference,
                 "tree root outside the member set");
}

CPATH_TEST(UnitCollective, pairwise_requires_an_even_member_count) {
  cp::CollectiveSpec odd;
  odd.id = cp::CollectiveId{std::string("w0")};
  odd.kind = cp::CollectiveKind::kPairwise;
  cp::GroupSpec group;
  group.id = cp::GroupId{std::string("g0")};
  group.pattern = cp::GroupPattern::kPairwise;
  for (const char* member : {"p0", "p1", "p2"}) {
    group.members.push_back(cp::ParticipantId{member});
  }
  odd.groups.push_back(group);
  check_rejected(cp::Collective::build(odd), cp::ErrorCode::kInconsistentMetadata, "odd pairwise group");

  cp::CollectiveSpec even = odd;
  even.groups[0].members.push_back(cp::ParticipantId{std::string("p3")});
  const cp::Collective& built = require_value(cp::Collective::build(even), "even pairwise group");
  CPATH_CHECK(edge_names(built) == std::vector<std::string>({"p0>p1", "p1>p0", "p2>p3", "p3>p2"}));
  CPATH_CHECK_EQ(built.stage_count, std::uint32_t{1});
}

CPATH_TEST(UnitCollective, all_to_all_produces_ordered_pairs) {
  cp::CollectiveSpec spec;
  spec.id = cp::CollectiveId{std::string("a0")};
  spec.kind = cp::CollectiveKind::kAllToAll;
  cp::GroupSpec group;
  group.id = cp::GroupId{std::string("g0")};
  group.pattern = cp::GroupPattern::kAllToAll;
  for (const char* member : {"p3", "p1", "p0", "p2"}) {
    group.members.push_back(cp::ParticipantId{member});
  }
  spec.groups.push_back(group);

  const cp::Collective& built = require_value(cp::Collective::build(spec), "all to all");
  CPATH_CHECK_EQ(built.logical_edges.size(), std::size_t{12});
  CPATH_CHECK_EQ(built.participants.size(), std::size_t{4});
  CPATH_CHECK_EQ(built.logical_edges.size(), built.participants.size() * (built.participants.size() - 1u));
  // Members were declared out of order; the canonical list is sorted.
  CPATH_CHECK_EQ(built.groups[0].members[0].value(), std::string("p0"));
  const std::vector<std::string> names = edge_names(built);
  for (const std::string& name : names) {
    const std::size_t separator = name.find('>');
    CPATH_REQUIRE(separator != std::string::npos);
    CPATH_CHECK(name.substr(0, separator) != name.substr(separator + 1u));
  }
  cp::LogicalEdge probe;
  probe.src = cp::ParticipantId{std::string("p0")};
  probe.dst = cp::ParticipantId{std::string("p3")};
  CPATH_CHECK(std::find(built.logical_edges.begin(), built.logical_edges.end(), probe) != built.logical_edges.end());
}

CPATH_TEST(UnitCollective, hierarchy_levels_become_stages) {
  cp::CollectiveSpec spec;
  spec.id = cp::CollectiveId{std::string("h0")};
  spec.kind = cp::CollectiveKind::kHierarchical;
  cp::GroupSpec inner;
  inner.id = cp::GroupId{std::string("g-inner")};
  inner.level = 0;
  inner.pattern = cp::GroupPattern::kRing;
  inner.members.push_back(cp::ParticipantId{std::string("p1")});
  inner.members.push_back(cp::ParticipantId{std::string("p0")});
  cp::GroupSpec outer;
  outer.id = cp::GroupId{std::string("g-outer")};
  outer.level = 1;
  outer.pattern = cp::GroupPattern::kRing;
  outer.members.push_back(cp::ParticipantId{std::string("p2")});
  outer.members.push_back(cp::ParticipantId{std::string("p3")});
  spec.groups.push_back(outer);
  spec.groups.push_back(inner);

  const cp::Collective& built = require_value(cp::Collective::build(spec), "hierarchy");
  CPATH_CHECK_EQ(built.stage_count, std::uint32_t{2});
  CPATH_REQUIRE_EQ(built.logical_edges.size(), std::size_t{4});
  CPATH_REQUIRE_EQ(built.logical_edge_stage.size(), built.logical_edges.size());
  // Groups are canonicalised by (level, id).
  CPATH_CHECK_EQ(built.groups[0].id.value(), std::string("g-inner"));
  CPATH_CHECK_EQ(built.groups[1].id.value(), std::string("g-outer"));
  for (std::size_t index = 0; index < built.logical_edges.size(); ++index) {
    const std::string& src = built.logical_edges[index].src.value();
    const std::uint32_t expected = (src == "p0" || src == "p1") ? 0u : 1u;
    CPATH_CHECK_EQ(built.logical_edge_stage[index], expected);
  }

  // The same logical edge implied by two levels is attributed to the earliest
  // stage and is still one exchange.
  cp::CollectiveSpec shared = spec;
  cp::GroupSpec duplicate;
  duplicate.id = cp::GroupId{std::string("g-dup")};
  duplicate.level = 1;
  duplicate.pattern = cp::GroupPattern::kRing;
  duplicate.members.push_back(cp::ParticipantId{std::string("p0")});
  duplicate.members.push_back(cp::ParticipantId{std::string("p1")});
  shared.groups.push_back(duplicate);
  const cp::Collective& merged = require_value(cp::Collective::build(shared), "shared logical edge");
  CPATH_CHECK_EQ(merged.logical_edges.size(), std::size_t{4});
  for (std::size_t index = 0; index < merged.logical_edges.size(); ++index) {
    if (merged.logical_edges[index].src.value() == "p0" || merged.logical_edges[index].src.value() == "p1") {
      CPATH_CHECK_EQ(merged.logical_edge_stage[index], std::uint32_t{0});
    }
  }
}

CPATH_TEST(UnitCollective, duplicate_members_are_rejected) {
  check_rejected(cp::Collective::build(ring_collective({"p0", "p1", "p0"})), cp::ErrorCode::kDuplicateIdentifier,
                 "ring repeating a member");

  cp::CollectiveSpec pairwise;
  pairwise.id = cp::CollectiveId{std::string("w0")};
  cp::GroupSpec group;
  group.id = cp::GroupId{std::string("g0")};
  group.pattern = cp::GroupPattern::kPairwise;
  group.members.push_back(cp::ParticipantId{std::string("p0")});
  group.members.push_back(cp::ParticipantId{std::string("p0")});
  pairwise.groups.push_back(group);
  check_rejected(cp::Collective::build(pairwise), cp::ErrorCode::kDuplicateIdentifier,
                 "pairwise repeating a member");

  cp::CollectiveSpec no_groups;
  no_groups.id = cp::CollectiveId{std::string("c0")};
  check_rejected(cp::Collective::build(no_groups), cp::ErrorCode::kEmptyCollective, "collective without groups");
}

CPATH_TEST(UnitCollective, self_loop_logical_edge_is_rejected) {
  // A self loop cannot be derived from a group (duplicate members are refused
  // first), so the structural guard is proved directly on the model.
  cp::Collective collective;
  collective.id = cp::CollectiveId{std::string("c0")};
  collective.kind = cp::CollectiveKind::kRing;
  collective.participants.push_back(cp::ParticipantId{std::string("p0")});
  collective.logical_edges.push_back(
      cp::LogicalEdge{cp::ParticipantId{std::string("p0")}, cp::ParticipantId{std::string("p0")}});
  collective.logical_edge_stage.push_back(0u);
  collective.stage_count = 1;
  check_rejected(collective.validate(), cp::ErrorCode::kSelfLoopLogicalEdge, "self loop logical edge");

  const cp::Collective& valid =
      require_value(cp::Collective::build(ring_collective({"p0", "p1"})), "two member ring");
  CPATH_CHECK(valid.validate().is_ok());
  CPATH_CHECK_EQ(valid.logical_edges.size(), std::size_t{2});
}

// ===========================================================================
// Policy validation and canonicalisation
// ===========================================================================

CPATH_TEST(UnitPolicy, validate_rejects_out_of_range_limits) {
  cp::Policy policy;
  policy.generation = cp::PolicyGeneration{1};
  CPATH_CHECK(policy.validate().is_ok());

  policy.max_hops = 0;
  check_rejected(policy.validate(), cp::ErrorCode::kValueOutOfRange, "max-hops of zero");
  policy.max_hops = cp::kMaxHops + 1u;
  check_rejected(policy.validate(), cp::ErrorCode::kValueOutOfRange, "max-hops above the model bound");
  policy.max_hops = cp::kMaxHops;
  CPATH_CHECK(policy.validate().is_ok());

  policy.paths_per_logical_edge = 0;
  check_rejected(policy.validate(), cp::ErrorCode::kPathCountUnsupported, "zero paths per logical edge");
  policy.paths_per_logical_edge = cp::kMaxPathsPerLogicalEdge + 1u;
  check_rejected(policy.validate(), cp::ErrorCode::kPathCountUnsupported, "too many paths per logical edge");
  policy.paths_per_logical_edge = cp::kMaxPathsPerLogicalEdge;
  CPATH_CHECK(policy.validate().is_ok());
  policy.paths_per_logical_edge = cp::kMinPathsPerLogicalEdge;

  policy.generation = cp::PolicyGeneration{};
  check_rejected(policy.validate(), cp::ErrorCode::kMissingRequiredField, "policy without a generation");
  policy.generation = cp::PolicyGeneration{1};

  policy.max_search_expansions = 0;
  check_rejected(policy.validate(), cp::ErrorCode::kValueOutOfRange, "empty search budget");
  policy.max_search_expansions = cp::kMaxSearchExpansions + 1u;
  check_rejected(policy.validate(), cp::ErrorCode::kValueOutOfRange, "search budget above the model bound");
  policy.max_search_expansions = 1u << 18;

  policy.max_path_cost = 0;
  check_rejected(policy.validate(), cp::ErrorCode::kValueOutOfRange, "zero cost limit");
  policy.max_path_cost = cp::kCostCeiling;
  policy.latency_weight_milli = cp::kMaxScoringWeightMilli + 1u;
  check_rejected(policy.validate(), cp::ErrorCode::kValueOutOfRange, "scoring weight above the model bound");
}

CPATH_TEST(UnitPolicy, validate_rejects_a_tier_that_is_allowed_and_forbidden) {
  cp::Policy policy;
  policy.generation = cp::PolicyGeneration{1};
  policy.forbidden_tiers.push_back(cp::TierId{std::string("T1")});
  policy.allowed_path_tiers.push_back(cp::TierId{std::string("T1")});
  check_rejected(policy.validate(), cp::ErrorCode::kInconsistentMetadata, "tier both allowed and forbidden");

  policy.allowed_path_tiers.clear();
  policy.allowed_path_tiers.push_back(cp::TierId{std::string("T2")});
  CPATH_CHECK(policy.validate().is_ok());

  policy.forbidden_nodes.push_back(cp::NodeId{std::string("bad node")});
  check_rejected(policy.validate(), cp::ErrorCode::kInvalidCharacter, "forbidden node with a space");
}

CPATH_TEST(UnitPolicy, canonicalize_sorts_and_deduplicates_sets) {
  cp::Policy policy;
  policy.generation = cp::PolicyGeneration{1};
  policy.forbidden_nodes.push_back(cp::NodeId{std::string("n2")});
  policy.forbidden_nodes.push_back(cp::NodeId{std::string("n1")});
  policy.forbidden_nodes.push_back(cp::NodeId{std::string("n2")});
  policy.forbidden_tiers.push_back(cp::TierId{std::string("T2")});
  policy.forbidden_tiers.push_back(cp::TierId{std::string("T1")});
  policy.forbidden_tiers.push_back(cp::TierId{std::string("T1")});
  policy.forbidden_failure_domains.push_back(cp::FailureDomainId{std::string("F2")});
  policy.forbidden_failure_domains.push_back(cp::FailureDomainId{std::string("F1")});
  policy.forbidden_failure_domains.push_back(cp::FailureDomainId{std::string("F1")});
  policy.allowed_path_tiers.push_back(cp::TierId{std::string("T9")});
  policy.allowed_path_tiers.push_back(cp::TierId{std::string("T8")});
  policy.allowed_path_tiers.push_back(cp::TierId{std::string("T9")});

  // A set-valued field is rejected until it is canonicalised, which proves the
  // canonicalisation below is doing real work.
  check_rejected(policy.validate(), cp::ErrorCode::kInconsistentMetadata, "unsorted policy sets");

  policy.canonicalize();
  CPATH_REQUIRE_EQ(policy.forbidden_nodes.size(), std::size_t{2});
  CPATH_CHECK_EQ(policy.forbidden_nodes[0].value(), std::string("n1"));
  CPATH_CHECK_EQ(policy.forbidden_nodes[1].value(), std::string("n2"));
  CPATH_REQUIRE_EQ(policy.forbidden_tiers.size(), std::size_t{2});
  CPATH_CHECK_EQ(policy.forbidden_tiers[0].value(), std::string("T1"));
  CPATH_REQUIRE_EQ(policy.forbidden_failure_domains.size(), std::size_t{2});
  CPATH_CHECK_EQ(policy.forbidden_failure_domains[0].value(), std::string("F1"));
  CPATH_REQUIRE_EQ(policy.allowed_path_tiers.size(), std::size_t{2});
  CPATH_CHECK_EQ(policy.allowed_path_tiers[0].value(), std::string("T8"));
  CPATH_CHECK(policy.validate().is_ok());
}

// ===========================================================================
// Request construction
// ===========================================================================

CPATH_TEST(UnitRequest, declaration_order_does_not_change_the_digest) {
  ct::SyntheticParams params;
  params.participants = 6;
  params.spine_count = 2;
  params.rack_count = 3;
  const cp::RequestSpec ordered = ct::make_ring_spec(params);  // SYNTHETIC fabric

  const cp::PlanningRequest& first = require_value(cp::build_request(ordered), "ordered request");

  // A deterministic reversal proves the declaration order really moved.
  cp::RequestSpec reversed = ordered;
  std::reverse(reversed.fabric.failure_domains.begin(), reversed.fabric.failure_domains.end());
  std::reverse(reversed.fabric.nodes.begin(), reversed.fabric.nodes.end());
  std::reverse(reversed.fabric.edges.begin(), reversed.fabric.edges.end());
  std::reverse(reversed.bindings.begin(), reversed.bindings.end());
  std::reverse(reversed.collective.groups.begin(), reversed.collective.groups.end());
  CPATH_REQUIRE(reversed.fabric.nodes.size() > 1u);
  CPATH_CHECK(reversed.fabric.nodes[0].id.value() != ordered.fabric.nodes[0].id.value());
  CPATH_CHECK(reversed.fabric.edges[0].id.value() != ordered.fabric.edges[0].id.value());

  const cp::PlanningRequest& second = require_value(cp::build_request(reversed), "reversed request");
  CPATH_CHECK_EQ(first.canonical_digest.hex(), second.canonical_digest.hex());
  CPATH_CHECK_EQ(first.canonical_bytes, second.canonical_bytes);
  cp::ByteWriter rebuilt;
  second.encode_canonical(rebuilt);
  CPATH_CHECK_EQ(rebuilt.size(), second.canonical_bytes);
  CPATH_CHECK_EQ(rebuilt.sha256().hex(), first.canonical_digest.hex());

  // A seeded shuffle of the same declarations is equivalent as well.
  cp::RequestSpec shuffled = ordered;
  ct::Random rng = ct::make_random(11);
  shuffle(shuffled.fabric.failure_domains, rng);
  shuffle(shuffled.fabric.nodes, rng);
  shuffle(shuffled.fabric.edges, rng);
  shuffle(shuffled.bindings, rng);
  shuffle(shuffled.collective.groups, rng);
  const cp::PlanningRequest& third = require_value(cp::build_request(shuffled), "shuffled request");
  CPATH_CHECK_EQ(first.canonical_digest.hex(), third.canonical_digest.hex());
  CPATH_CHECK_EQ(first.canonical_bytes, third.canonical_bytes);
}

CPATH_TEST(UnitRequest, binding_change_changes_the_digest) {
  ct::SyntheticParams params;
  params.participants = 6;
  params.spine_count = 2;
  params.rack_count = 3;
  const cp::RequestSpec base = ct::make_ring_spec(params);  // SYNTHETIC fabric

  cp::RequestSpec changed = base;
  CPATH_REQUIRE(!changed.bindings.empty());
  CPATH_REQUIRE_EQ(changed.bindings[0].participant.value(), std::string("p0"));
  CPATH_REQUIRE_EQ(changed.bindings[0].node.value(), std::string("n0"));
  changed.bindings[0].node = cp::NodeId{std::string("n1")};

  const cp::PlanningRequest& original = require_value(cp::build_request(base), "original request");
  const cp::PlanningRequest& rebound = require_value(cp::build_request(changed), "rebound request");
  CPATH_CHECK(original.canonical_digest != rebound.canonical_digest);
  CPATH_CHECK(original.canonical_digest.hex() != rebound.canonical_digest.hex());
  CPATH_REQUIRE(rebound.find_binding(cp::ParticipantId{std::string("p0")}) != nullptr);
  CPATH_CHECK_EQ(rebound.find_binding(cp::ParticipantId{std::string("p0")})->node.value(), std::string("n1"));
  CPATH_CHECK(rebound.find_binding(cp::ParticipantId{std::string("p9")}) == nullptr);

  // A binding for a participant the collective does not declare is refused.
  cp::RequestSpec foreign = base;
  cp::EndpointBinding extra;
  extra.participant = cp::ParticipantId{std::string("p9")};
  extra.node = cp::NodeId{std::string("n0")};
  foreign.bindings.push_back(extra);
  check_rejected(cp::build_request(foreign), cp::ErrorCode::kUnknownReference, "binding outside the collective");

  // Two bindings for one participant are refused rather than silently merged.
  cp::RequestSpec doubled = base;
  doubled.bindings.push_back(doubled.bindings[0]);
  check_rejected(cp::build_request(doubled), cp::ErrorCode::kDuplicateBinding, "duplicate binding");
}

CPATH_TEST(UnitRequest, plan_generation_is_not_part_of_the_digest) {
  ct::SyntheticParams params;
  params.participants = 6;
  params.spine_count = 2;
  params.rack_count = 3;
  cp::RequestSpec low = ct::make_ring_spec(params);  // SYNTHETIC fabric
  low.plan_generation = cp::CollectivePlanGeneration{1};
  cp::RequestSpec high = low;
  high.plan_generation = cp::CollectivePlanGeneration{2};

  const cp::PlanningRequest& first = require_value(cp::build_request(low), "plan generation 1");
  const cp::PlanningRequest& second = require_value(cp::build_request(high), "plan generation 2");

  // Documented design decision (request.hpp): the canonical digest excludes the
  // plan generation, which is a caller-supplied sequencing label rather than an
  // input to the mapping. The plan binds it separately.
  CPATH_CHECK_EQ(first.canonical_digest.hex(), second.canonical_digest.hex());
  CPATH_CHECK_EQ(first.canonical_bytes, second.canonical_bytes);

  const cp::PlanningOutcome first_outcome = cp::plan_collective(first);
  const cp::PlanningOutcome second_outcome = cp::plan_collective(second);
  CPATH_REQUIRE(first_outcome.ok());
  CPATH_REQUIRE(second_outcome.ok());
  const cp::Plan& first_plan = *first_outcome.plan;
  const cp::Plan& second_plan = *second_outcome.plan;

  // ... yet the plans bind the generation they were produced under, and that
  // binding is what a caller revalidates against.
  CPATH_CHECK_EQ(first_plan.generation.value(), std::uint64_t{1u});
  CPATH_CHECK_EQ(second_plan.generation.value(), std::uint64_t{2u});
  CPATH_CHECK_EQ(first_plan.bindings.plan.value(), std::uint64_t{1u});
  CPATH_CHECK_EQ(second_plan.bindings.plan.value(), std::uint64_t{2u});
  CPATH_CHECK(first_plan.bindings != second_plan.bindings);
  CPATH_CHECK(first_plan.id == second_plan.id);
  CPATH_CHECK_EQ(first_plan.id.value().hex(), second_plan.id.value().hex());
  CPATH_CHECK(!(first_plan.encode() == second_plan.encode()));
  CPATH_CHECK(cp::validate_plan(first_plan, first).is_ok());
  CPATH_CHECK(cp::validate_plan(second_plan, second).is_ok());
  check_rejected(cp::validate_plan(first_plan, second), cp::ErrorCode::kStalePlanGeneration,
                 "plan validated against a newer plan generation");
}

CPATH_TEST(UnitRequest, policy_generation_is_part_of_the_digest) {
  ct::SyntheticParams params;
  params.participants = 6;
  params.spine_count = 2;
  params.rack_count = 3;
  cp::RequestSpec low = ct::make_ring_spec(params);  // SYNTHETIC fabric
  low.policy.generation = cp::PolicyGeneration{5};
  cp::RequestSpec high = low;
  high.policy.generation = cp::PolicyGeneration{9};

  const cp::PlanningRequest& first = require_value(cp::build_request(low), "policy generation 5");
  const cp::PlanningRequest& second = require_value(cp::build_request(high), "policy generation 9");

  // The policy generation fences the policy content, and the policy content is
  // a mapping input, so it is inside the canonical digest.
  CPATH_CHECK(first.canonical_digest != second.canonical_digest);
  CPATH_CHECK_EQ(first.current_bindings().policy.value(), std::uint64_t{5u});
  CPATH_CHECK_EQ(second.current_bindings().policy.value(), std::uint64_t{9u});

  const cp::PlanningOutcome outcome = cp::plan_collective(second);
  CPATH_REQUIRE(outcome.ok());
  CPATH_CHECK_EQ(outcome.plan->bindings.policy.value(), std::uint64_t{9u});
  CPATH_CHECK_EQ(outcome.plan->input_digest.hex(), second.canonical_digest.hex());
  // Because the policy generation is inside the digest, a plan produced under a
  // different one no longer matches the request at the strictest check.
  check_rejected(cp::validate_plan(*outcome.plan, first), cp::ErrorCode::kPlanInputMismatch,
                 "plan validated against a different policy generation");
}

// ===========================================================================
// Text DSL reader
// ===========================================================================

CPATH_TEST(UnitDsl, fixture_texts_parse_with_the_declared_values) {
  const cp::PlanningRequest& minimal =
      require_value(cp::parse_request_text(ct::minimal_ring_text()), "minimal_ring_text");
  CPATH_CHECK_EQ(minimal.collective.id.value(), std::string("c0"));
  CPATH_CHECK_EQ(minimal.collective.logical_edges.size(), std::size_t{2});
  CPATH_CHECK_EQ(minimal.collective.participants.size(), std::size_t{2});
  CPATH_CHECK_EQ(minimal.fabric.node_count(), std::size_t{2});
  CPATH_CHECK_EQ(minimal.fabric.edge_count(), std::size_t{2});
  CPATH_CHECK_EQ(minimal.bindings.size(), std::size_t{2});
  CPATH_CHECK_EQ(minimal.policy.max_hops, std::size_t{4});
  CPATH_CHECK_EQ(minimal.policy.paths_per_logical_edge, std::size_t{1});
  CPATH_CHECK_EQ(minimal.plan_generation.value(), std::uint64_t{1u});
  CPATH_CHECK_EQ(minimal.current_bindings().topology.value(), std::uint64_t{7u});
  CPATH_CHECK_EQ(minimal.current_bindings().failure_domains.value(), std::uint64_t{3u});
  CPATH_CHECK_EQ(minimal.current_bindings().capacity_evidence.value(), std::uint64_t{11u});
  CPATH_CHECK(minimal.validate().is_ok());

  const cp::PlanningRequest& four =
      require_value(cp::parse_request_text(ct::four_node_ring_text()), "four_node_ring_text");
  CPATH_CHECK_EQ(four.collective.logical_edges.size(), std::size_t{4});
  CPATH_CHECK_EQ(four.collective.demand_mbps, std::uint64_t{1000u});
  CPATH_CHECK_EQ(four.policy.paths_per_logical_edge, std::size_t{2});
  CPATH_CHECK_EQ(four.policy.max_hops, std::size_t{6});
  CPATH_CHECK_EQ(std::string(cp::to_string(four.policy.disjointness)), std::string("edge"));
  CPATH_CHECK_EQ(std::string(cp::to_string(four.policy.domain_diversity)), std::string("required"));
  CPATH_CHECK_EQ(std::string(cp::to_string(four.policy.domain_diversity_level)), std::string("rack"));
  // Declared by the shipped fixture text: four leaves, two spines, sixteen
  // directed links, three failure domains and four endpoint bindings.
  CPATH_CHECK_EQ(four.fabric.node_count(), std::size_t{6});
  CPATH_CHECK_EQ(four.fabric.edge_count(), std::size_t{16});
  CPATH_CHECK_EQ(four.fabric.failure_domains().size(), std::size_t{3});
  CPATH_CHECK_EQ(four.bindings.size(), std::size_t{4});
  CPATH_CHECK(four.validate().is_ok());
  for (const cp::EndpointBinding& binding : four.bindings) {
    CPATH_CHECK(four.fabric.find_node(binding.node) != nullptr);
    CPATH_CHECK(std::find(four.collective.participants.begin(), four.collective.participants.end(),
                          binding.participant) != four.collective.participants.end());
  }
  for (const cp::Edge& edge : four.fabric.edges()) {
    CPATH_CHECK(four.fabric.find_node(edge.from) != nullptr);
    CPATH_CHECK(four.fabric.find_node(edge.to) != nullptr);
  }
}

CPATH_TEST(UnitDsl, encoded_requests_round_trip_to_the_same_digest) {
  const std::vector<std::string> texts = {ct::minimal_ring_text(), ct::four_node_ring_text()};
  for (const std::string& text : texts) {
    const cp::PlanningRequest& parsed = require_value(cp::parse_request_text(text), "fixture request");
    const std::string rendered = cp::encode_request_text(parsed);
    CPATH_CHECK(rendered.find("cpath-request 1") == 0u);
    const cp::PlanningRequest& again = require_value(cp::parse_request_text(rendered), "re-parsed request");
    CPATH_CHECK_EQ(again.canonical_digest.hex(), parsed.canonical_digest.hex());
    CPATH_CHECK_EQ(again.canonical_bytes, parsed.canonical_bytes);
    CPATH_CHECK_EQ(cp::encode_request_text(again), rendered);
    // The re-parse rebuilds the same model, not merely the same digest.
    CPATH_CHECK(again.collective.logical_edges.size() == parsed.collective.logical_edges.size());
    CPATH_CHECK(again.fabric.edges().size() == parsed.fabric.edges().size());
    CPATH_CHECK(again.bindings.size() == parsed.bindings.size());
  }
}

CPATH_TEST(UnitDsl, reader_rejections_use_exact_codes) {
  const std::string minimal = ct::minimal_ring_text();
  std::vector<RejectionCase> cases;
  cases.push_back({"missing banner", cp::ErrorCode::kMissingRequiredField, "plan-generation 1\n"});
  cases.push_back({"wrong banner version", cp::ErrorCode::kUnsupportedFormatVersion, "cpath-request 2\n"});
  cases.push_back({"unknown section", cp::ErrorCode::kUnknownKeyword, minimal + "\n[bogus]\n"});
  cases.push_back({"unknown key", cp::ErrorCode::kUnknownKeyword, minimal + "bogus=1\n"});
  cases.push_back({"duplicate section", cp::ErrorCode::kDuplicateIdentifier, minimal + "\n[policy]\n"});
  cases.push_back({"duplicate node", cp::ErrorCode::kDuplicateIdentifier,
                   insert_after_section(minimal, "nodes", "n0 site=S0 rack=R0 host=HX device=0 tier=LEAF")});
  cases.push_back({"missing required key", cp::ErrorCode::kMissingRequiredField,
                   insert_after_section(minimal, "edges", "e9 from=n0 capacity=1000")});
  cases.push_back({"non numeric number", cp::ErrorCode::kMalformedNumber,
                   replace_first(minimal, "plan-generation 1", "plan-generation abc")});
  cases.push_back({"leading zero number", cp::ErrorCode::kMalformedNumber,
                   replace_first(minimal, "plan-generation 1", "plan-generation 01")});
  cases.push_back({"out of range number", cp::ErrorCode::kValueOutOfRange,
                   replace_first(minimal, "plan-generation 1", "plan-generation 18446744073709551616")});
  cases.push_back({"line too long", cp::ErrorCode::kLineTooLong, minimal + "#" + std::string(4096u, 'x') + "\n"});
  cases.push_back({"assignment without equals", cp::ErrorCode::kInvalidSyntax, minimal + "max-hops\n"});
  cases.push_back({"repeated key on one line", cp::ErrorCode::kDuplicateIdentifier,
                   minimal + "max-hops=8 max-hops=9\n"});

  // The spliced texts must still differ from the original, otherwise a case
  // would silently assert the wrong thing.
  for (const RejectionCase& item : cases) {
    CPATH_CHECK(!item.text.empty());
    check_rejection_case(item);
  }
  // The unmodified fixture remains acceptable, so the cases above prove
  // rejection rather than general breakage.
  CPATH_CHECK(cp::parse_request_text(minimal).has_value());
}

// ===========================================================================
// Freshness
// ===========================================================================

CPATH_TEST(UnitFreshness, each_generation_field_has_its_own_freshness) {
  const cp::GenerationBindings current = sample_bindings();
  const cp::Plan plan = plan_with_bindings(current);
  CPATH_CHECK_EQ(std::string(cp::to_string(cp::assess_freshness(plan, current))), std::string("current"));

  cp::GenerationBindings changed = current;
  changed.topology = cp::TopologyGeneration{8};
  CPATH_CHECK_EQ(std::string(cp::to_string(cp::assess_freshness(plan, changed))), std::string("stale-topology"));

  changed = current;
  changed.failure_domains = cp::FailureDomainGeneration{4};
  CPATH_CHECK_EQ(std::string(cp::to_string(cp::assess_freshness(plan, changed))),
                 std::string("stale-failure-domains"));

  changed = current;
  changed.capacity_evidence = cp::CapacityEvidenceGeneration{12};
  CPATH_CHECK_EQ(std::string(cp::to_string(cp::assess_freshness(plan, changed))),
                 std::string("stale-capacity-evidence"));

  changed = current;
  changed.policy = cp::PolicyGeneration{6};
  CPATH_CHECK_EQ(std::string(cp::to_string(cp::assess_freshness(plan, changed))), std::string("stale-policy"));

  changed = current;
  changed.plan = cp::CollectivePlanGeneration{2};
  CPATH_CHECK_EQ(std::string(cp::to_string(cp::assess_freshness(plan, changed))),
                 std::string("stale-plan-generation"));

  // The classification is ordered: topology wins over every later fence.
  changed = current;
  changed.topology = cp::TopologyGeneration{8};
  changed.policy = cp::PolicyGeneration{6};
  CPATH_CHECK_EQ(std::string(cp::to_string(cp::assess_freshness(plan, changed))), std::string("stale-topology"));

  // A plan produced from a real request is current against that request.
  ct::SyntheticParams params;
  params.participants = 6;
  params.spine_count = 2;
  params.rack_count = 3;
  const cp::PlanningRequest& request =
      require_value(cp::build_request(ct::make_ring_spec(params)), "synthetic request");
  const cp::PlanningOutcome outcome = cp::plan_collective(request);
  CPATH_REQUIRE(outcome.ok());
  CPATH_CHECK_EQ(std::string(cp::to_string(cp::assess_freshness(*outcome.plan, request.current_bindings()))),
                 std::string("current"));
}

CPATH_TEST(UnitFreshness, describe_freshness_maps_to_error_codes) {
  const std::vector<std::pair<cp::PlanFreshness, cp::ErrorCode>> expected = {
      {cp::PlanFreshness::kCurrent, cp::ErrorCode::kOk},
      {cp::PlanFreshness::kStaleTopology, cp::ErrorCode::kStaleTopologyGeneration},
      {cp::PlanFreshness::kStaleFailureDomains, cp::ErrorCode::kStaleFailureDomainGeneration},
      {cp::PlanFreshness::kStaleCapacityEvidence, cp::ErrorCode::kStaleCapacityEvidenceGeneration},
      {cp::PlanFreshness::kStalePolicy, cp::ErrorCode::kStalePolicyGeneration},
      {cp::PlanFreshness::kStalePlanGeneration, cp::ErrorCode::kStalePlanGeneration},
      {cp::PlanFreshness::kUnverified, cp::ErrorCode::kRevalidationRequired},
  };
  for (const auto& [freshness, code] : expected) {
    cp::ErrorCode observed = cp::ErrorCode::kInternalError;
    const char* description = cp::describe_freshness(freshness, observed);
    CPATH_CHECK(observed == code);
    CPATH_REQUIRE(description != nullptr);
    CPATH_CHECK(std::string(description).size() > 0u);
    CPATH_CHECK_EQ(std::string(cp::to_string(freshness)).empty(), false);
  }
  // Only kCurrent maps to success.
  cp::ErrorCode code = cp::ErrorCode::kInternalError;
  (void)cp::describe_freshness(cp::PlanFreshness::kCurrent, code);
  CPATH_CHECK(code == cp::ErrorCode::kOk);
}

// ===========================================================================
// Plan comparison
// ===========================================================================

CPATH_TEST(UnitCompare, identical_plans_compare_identical) {
  const cp::RequestSpec spec = diamond_request(10u, 100u);  // SYNTHETIC diamond
  const cp::PlanningRequest& request = require_value(cp::build_request(spec), "diamond request");
  const cp::PlanningOutcome first = cp::plan_collective(request);
  const cp::PlanningOutcome second = cp::plan_collective(request);
  CPATH_REQUIRE(first.ok());
  CPATH_REQUIRE(second.ok());
  CPATH_CHECK(first.plan->encode() == second.plan->encode());

  const cp::PlanComparison comparison = cp::compare_plans(*first.plan, *second.plan);
  CPATH_CHECK(comparison.identical);
  CPATH_CHECK(comparison.same_input_digest);
  CPATH_CHECK(comparison.same_collective);
  CPATH_CHECK(!comparison.left_is_replan_of_right);
  CPATH_CHECK_EQ(comparison.changed_logical_edges, std::size_t{0});
  CPATH_CHECK_EQ(comparison.added_paths, std::size_t{0});
  CPATH_CHECK_EQ(comparison.removed_paths, std::size_t{0});
  CPATH_CHECK_EQ(comparison.rewritten_paths, std::size_t{0});
  CPATH_CHECK_EQ(comparison.summary, std::string("plans are byte-identical"));
}

CPATH_TEST(UnitCompare, topology_change_reports_the_changed_logical_edge) {
  // Same collective and bindings, different physical latency: the mapping must
  // move to the other route while the collective identity stays the same.
  const cp::PlanningRequest& original =
      require_value(cp::build_request(diamond_request(10u, 100u)), "fast route first");  // SYNTHETIC
  const cp::PlanningRequest& replanned =
      require_value(cp::build_request(diamond_request(200u, 5u)), "fast route second");  // SYNTHETIC
  const cp::PlanningOutcome before = cp::plan_collective(original);
  const cp::PlanningOutcome after = cp::plan_collective(replanned);
  CPATH_REQUIRE(before.ok());
  CPATH_REQUIRE(after.ok());
  CPATH_REQUIRE_EQ(before.plan->paths.size(), std::size_t{1});
  CPATH_REQUIRE_EQ(after.plan->paths.size(), std::size_t{1});
  CPATH_CHECK_EQ(before.plan->paths[0].hops[0].edge.value(), std::string("e0"));
  CPATH_CHECK_EQ(after.plan->paths[0].hops[0].edge.value(), std::string("e2"));

  const cp::PlanComparison comparison = cp::compare_plans(*after.plan, *before.plan);
  CPATH_CHECK(!comparison.identical);
  CPATH_CHECK(!comparison.same_input_digest);
  CPATH_CHECK(comparison.same_collective);
  CPATH_CHECK_EQ(comparison.changed_logical_edges, std::size_t{1});
  CPATH_CHECK_EQ(comparison.rewritten_paths, std::size_t{1});
  CPATH_CHECK_EQ(comparison.added_paths, std::size_t{0});
  CPATH_CHECK_EQ(comparison.removed_paths, std::size_t{0});
  CPATH_REQUIRE_EQ(comparison.differences.size(), std::size_t{1});
  CPATH_CHECK_EQ(comparison.differences[0].logical_edge.value(), std::uint64_t{1u});
  CPATH_CHECK(comparison.differences[0].left_present);
  CPATH_CHECK(comparison.differences[0].right_present);
  CPATH_CHECK(!comparison.differences[0].identical);
  CPATH_CHECK(comparison.differences[0].summary.find("rewritten") != std::string::npos);
  CPATH_CHECK(comparison.summary.find("1 logical edge(s) changed") != std::string::npos);
}

int main(int argc, char** argv) { return cpath_test::Registry::instance().run(argc, argv); }
