// Independent downstream consumer of the installed Collective Path Planner.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
//
// This program links only against the installed package. It parses a request,
// plans it, commits the plan to a durable store, reopens the store, and proves
// that the reopened plan is not treated as current until it is revalidated.
//
// PROOF LABEL: SYNTHETIC. The fabric is generated by this program.

#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <string>

#include <cpath/dsl.hpp>
#include <cpath/explain.hpp>
#include <cpath/persistence.hpp>
#include <cpath/planner.hpp>
#include <cpath/version.hpp>

namespace {

std::string request_text() {
  return std::string(
      "cpath-request 1\n"
      "plan-generation 1\n"
      "topology-generation 4\n"
      "failure-domain-generation 2\n"
      "capacity-evidence-generation 6\n"
      "policy-generation 3\n"
      "\n"
      "[collective]\n"
      "id=consumer kind=ring demand=500\n"
      "\n"
      "[groups]\n"
      "g0 level=0 pattern=ring members=p0,p1,p2,p3\n"
      "\n"
      "[domains]\n"
      "SITE kind=site\n"
      "RACKA kind=rack parent=SITE\n"
      "RACKB kind=rack parent=SITE\n"
      "\n"
      "[nodes]\n"
      "n0 site=SITE rack=RACKA host=H0 device=0 tier=LEAF\n"
      "n1 site=SITE rack=RACKB host=H1 device=0 tier=LEAF\n"
      "n2 site=SITE rack=RACKA host=H2 device=0 tier=LEAF\n"
      "n3 site=SITE rack=RACKB host=H3 device=0 tier=LEAF\n"
      "sp0 site=SITE pod=P0 rack=CORE host=SP0 device=0 tier=SPINE\n"
      "sp1 site=SITE pod=P0 rack=CORE host=SP1 device=0 tier=SPINE\n"
      "\n"
      "[edges]\n"
      "c0 from=n0 to=sp0 capacity=25000 latency=90 tier=LEAF domain=RACKA evidence=synthetic\n"
      "c1 from=sp0 to=n0 capacity=25000 latency=90 tier=LEAF domain=RACKA evidence=synthetic\n"
      "c2 from=n0 to=sp1 capacity=25000 latency=140 tier=LEAF domain=RACKA evidence=synthetic\n"
      "c3 from=sp1 to=n0 capacity=25000 latency=140 tier=LEAF domain=RACKA evidence=synthetic\n"
      "c4 from=n1 to=sp0 capacity=25000 latency=110 tier=LEAF domain=RACKB evidence=synthetic\n"
      "c5 from=sp0 to=n1 capacity=25000 latency=110 tier=LEAF domain=RACKB evidence=synthetic\n"
      "c6 from=n1 to=sp1 capacity=25000 latency=95 tier=LEAF domain=RACKB evidence=synthetic\n"
      "c7 from=sp1 to=n1 capacity=25000 latency=95 tier=LEAF domain=RACKB evidence=synthetic\n"
      "c8 from=n2 to=sp0 capacity=25000 latency=105 tier=LEAF domain=RACKA evidence=synthetic\n"
      "c9 from=sp0 to=n2 capacity=25000 latency=105 tier=LEAF domain=RACKA evidence=synthetic\n"
      "c10 from=n2 to=sp1 capacity=25000 latency=150 tier=LEAF domain=RACKA evidence=synthetic\n"
      "c11 from=sp1 to=n2 capacity=25000 latency=150 tier=LEAF domain=RACKA evidence=synthetic\n"
      "c12 from=n3 to=sp0 capacity=25000 latency=120 tier=LEAF domain=RACKB evidence=synthetic\n"
      "c13 from=sp0 to=n3 capacity=25000 latency=120 tier=LEAF domain=RACKB evidence=synthetic\n"
      "c14 from=n3 to=sp1 capacity=25000 latency=100 tier=LEAF domain=RACKB evidence=synthetic\n"
      "c15 from=sp1 to=n3 capacity=25000 latency=100 tier=LEAF domain=RACKB evidence=synthetic\n"
      "c16 from=sp0 to=sp1 capacity=100000 latency=40 tier=SPINE domain=SITE evidence=synthetic\n"
      "c17 from=sp1 to=sp0 capacity=100000 latency=40 tier=SPINE domain=SITE evidence=synthetic\n"
      "\n"
      "[bindings]\n"
      "p0 node=n0\n"
      "p1 node=n1\n"
      "p2 node=n2\n"
      "p3 node=n3\n"
      "\n"
      "[policy]\n"
      "max-hops=6\n"
      "paths-per-logical-edge=2\n"
      "disjointness=edge\n"
      "domain-diversity=required\n"
      "domain-diversity-level=rack\n"
      "congestion-weight-milli=200\n");
}

std::string environment_value(const char* name) {
#ifdef _WIN32
  char* buffer = nullptr;
  std::size_t size = 0;
  if (::_dupenv_s(&buffer, &size, name) != 0 || buffer == nullptr) {
    return std::string();
  }
  const std::string value(buffer);
  std::free(buffer);
  return value;
#else
  const char* value = std::getenv(name);
  return value != nullptr ? std::string(value) : std::string();
#endif
}

std::string store_path() {
#ifdef _WIN32
  const std::string root = environment_value("TEMP").empty() ? std::string(".") : environment_value("TEMP");
  const char separator = '\\';
#else
  const std::string root = environment_value("TMPDIR").empty() ? std::string("/tmp") : environment_value("TMPDIR");
  const char separator = '/';
#endif
  return root + separator + "cpath-consumer-store";
}

int fail(const std::string& message) {
  std::cerr << "consumer: " << message << "\n";
  return 1;
}

}  // namespace

int main() {
  std::cout << "linked against " << cpath::build_summary() << "\n";
  std::cout << "PROOF LABEL: SYNTHETIC fabric (no device was measured)\n";

  auto request = cpath::parse_request_text(request_text());
  if (!request.has_value()) {
    return fail("request rejected: " + request.status().to_string());
  }

  const cpath::PlanningOutcome outcome = cpath::plan_collective(request.value());
  if (!outcome.ok()) {
    std::cerr << cpath::explain_denials(outcome);
    return fail("planning refused");
  }
  const cpath::Plan& plan = *outcome.plan;
  std::cout << "planned " << plan.id.value().hex() << ": " << plan.stats.path_count << " paths over "
            << plan.stats.hop_count << " hops, weakest evidence " << cpath::to_string(plan.weakest_evidence)
            << "\n";

  const cpath::Status validation = cpath::validate_plan(plan, request.value());
  if (!validation.is_ok()) {
    return fail("produced plan failed validation: " + validation.to_string());
  }

  cpath::StoreConfig config;
  config.root = store_path();
  cpath::PlanStore store(config);
  if (cpath::Status status = store.open(); !status.is_ok()) {
    return fail("store open failed: " + status.to_string());
  }
  auto stored = store.put(plan, request.value());
  if (!stored.has_value()) {
    return fail("store put failed: " + stored.status().to_string());
  }
  store.close();

  cpath::PlanStore reopened(config);
  if (cpath::Status status = reopened.open(); !status.is_ok()) {
    return fail("store reopen failed: " + status.to_string());
  }
  auto revalidated = reopened.revalidate(cpath::CollectivePlanId{plan.id.value()}, request.value());
  if (!revalidated.has_value()) {
    return fail("revalidate failed: " + revalidated.status().to_string());
  }
  std::cout << "reopened under incarnation " << reopened.incarnation().value()
            << ", still-valid=" << (revalidated.value().still_valid ? "yes" : "no")
            << ", freshness=" << cpath::to_string(revalidated.value().freshness) << "\n";
  reopened.close();

  std::cout << "consumer proof complete\n";
  return 0;
}
