// Collective Path Planner - shared synthetic fixtures for the test suites.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
//
// Every fabric produced here is SYNTHETIC: generated by a model, never measured
// on a device. Suites that use it must say so in their output.
#ifndef CPATH_TEST_FIXTURES_HPP
#define CPATH_TEST_FIXTURES_HPP

#include <cstdint>
#include <string>
#include <vector>

#include "cpath/dsl.hpp"
#include "cpath/planner.hpp"
#include "cpath/request.hpp"
#include "test_framework.hpp"

namespace cpath_test {

struct SyntheticParams {
  std::uint64_t seed{1};
  std::size_t participants{6};
  std::size_t spine_count{2};
  std::size_t rack_count{3};
  std::uint64_t capacity_mbps{10000};
  std::uint64_t latency_micros{100};
  std::uint64_t demand_mbps{0};
  std::uint64_t topology_generation{7};
  std::uint64_t failure_domain_generation{3};
  std::uint64_t capacity_evidence_generation{11};
  std::uint64_t policy_generation{5};
  std::uint64_t plan_generation{1};
  // Adversarial knobs. Each injects a specific defect class into the fabric.
  unsigned duplicate_edge_percent{0};
  unsigned zero_capacity_percent{0};
  unsigned unknown_evidence_percent{0};
  unsigned asymmetric_percent{0};
  unsigned huge_latency_percent{0};
  unsigned ineligible_edge_percent{0};
};

// Ring collective over participants p0..p{n-1}; leaf n{i} hosts p{i}.
cpath::RequestSpec make_ring_spec(const SyntheticParams& params);
// All-to-all collective over the same participants and fabric.
cpath::RequestSpec make_alltoall_spec(const SyntheticParams& params);
// Hierarchical collective: one ring inside each rack, then a ring across racks.
cpath::RequestSpec make_hierarchical_spec(const SyntheticParams& params);
// Pairwise exchange over the participants.
cpath::RequestSpec make_pairwise_spec(const SyntheticParams& params);

cpath::PlanningRequest build_or_fail(const cpath::RequestSpec& spec, const char* context);
cpath::PlanningRequest build_or_fail(cpath::RequestSpec&& spec, const char* context);

// A minimal hand-written request in the text DSL. Used by the reader tests and
// as the smallest end-to-end input in the planner tests.
std::string minimal_ring_text();
// The same request with the collective expanded to four participants.
std::string four_node_ring_text();

std::string describe_outcome(const cpath::PlanningOutcome& outcome);

// True when any hop of any path uses an edge that the fabric marks ineligible.
bool plan_uses_ineligible_edge(const cpath::Plan& plan, const cpath::FabricGraph& fabric);

}  // namespace cpath_test

#endif  // CPATH_TEST_FIXTURES_HPP
