// Collective Path Planner example: a request that must be refused, and the
// precise reason it is refused.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
//
// PROOF LABEL: SYNTHETIC. The fabric is generated by this program.

#include <iostream>
#include <string>

#include "cpath/dsl.hpp"
#include "cpath/explain.hpp"
#include "cpath/planner.hpp"

namespace {

// The only physical path from p0 to p1 crosses n1, which the policy forbids.
// The planner must refuse the whole collective rather than return a partial or
// unsafe mapping.
std::string blocked_request_text() {
  return std::string(
      "cpath-request 1\n"
      "plan-generation 1\n"
      "topology-generation 5\n"
      "failure-domain-generation 2\n"
      "capacity-evidence-generation 3\n"
      "policy-generation 1\n"
      "\n"
      "[collective]\n"
      "id=blocked kind=ring\n"
      "\n"
      "[groups]\n"
      "g0 level=0 pattern=ring members=p0,p1,p2\n"
      "\n"
      "[domains]\n"
      "SITE kind=site\n"
      "RACK kind=rack parent=SITE\n"
      "\n"
      "[nodes]\n"
      "n0 site=SITE rack=RACK host=H0 device=0 tier=LEAF\n"
      "n1 site=SITE rack=RACK host=H1 device=0 tier=LEAF\n"
      "n2 site=SITE rack=RACK host=H2 device=0 tier=LEAF\n"
      "\n"
      "[edges]\n"
      "e0 from=n0 to=n1 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
      "e1 from=n1 to=n2 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
      "e2 from=n2 to=n0 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
      "e3 from=n1 to=n0 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
      "e4 from=n2 to=n1 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
      "e5 from=n0 to=n2 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
      "\n"
      "[bindings]\n"
      "p0 node=n0\n"
      "p1 node=n1\n"
      "p2 node=n2\n"
      "\n"
      "[policy]\n"
      "max-hops=4\n"
      "paths-per-logical-edge=1\n"
      "\n"
      "[forbidden]\n"
      "nodes=n1\n");
}

}  // namespace

int main() {
  std::cout << "PROOF LABEL: SYNTHETIC fabric (no device was measured)\n\n";

  auto request = cpath::parse_request_text(blocked_request_text());
  if (!request.has_value()) {
    std::cerr << "request rejected: " << request.status().to_string() << "\n";
    return 1;
  }
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request.value());
  if (outcome.ok()) {
    std::cerr << "expected a denial but a plan was produced\n";
    return 1;
  }
  std::cout << cpath::explain_denials(outcome);
  std::cout << "\nprimary code: " << cpath::code_symbol(outcome.primary_code()) << "\n";
  std::cout << "json:\n" << cpath::render_outcome_json(outcome) << "\n";

  // A denial must never be accompanied by a plan.
  if (outcome.plan.has_value()) {
    std::cerr << "denial carried a partial plan\n";
    return 1;
  }
  return 0;
}
