// Collective Path Planner example: plan a ring collective onto a synthetic
// two-tier fabric and explain the result.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
//
// PROOF LABEL: SYNTHETIC. The fabric below is generated by this program. No
// physical device was measured and no path here is evidence about real hardware.

#include <cstdint>
#include <iostream>
#include <string>
#include <vector>

#include "cpath/dsl.hpp"
#include "cpath/explain.hpp"
#include "cpath/planner.hpp"
#include "cpath/version.hpp"

namespace {

// Two racks, four leaves, one spine. Every leaf is connected to the spine in
// both directions with 25 Gbit/s and 100 microseconds of latency.
std::string synthetic_request_text() {
  return std::string(
      "cpath-request 1\n"
      "plan-generation 1\n"
      "topology-generation 21\n"
      "failure-domain-generation 4\n"
      "capacity-evidence-generation 9\n"
      "policy-generation 2\n"
      "\n"
      "[collective]\n"
      "id=demo-ring kind=ring demand=1000\n"
      "\n"
      "[groups]\n"
      "g0 level=0 pattern=ring members=p0,p1,p2,p3\n"
      "\n"
      "[domains]\n"
      "SITE kind=site\n"
      "RACK-A kind=rack parent=SITE\n"
      "RACK-B kind=rack parent=SITE\n"
      "HOST-0 kind=host parent=RACK-A\n"
      "HOST-1 kind=host parent=RACK-B\n"
      "HOST-2 kind=host parent=RACK-A\n"
      "HOST-3 kind=host parent=RACK-B\n"
      "\n"
      "[nodes]\n"
      "n0 site=SITE rack=RACK-A host=HOST-0 device=0 tier=LEAF\n"
      "n1 site=SITE rack=RACK-B host=HOST-1 device=0 tier=LEAF\n"
      "n2 site=SITE rack=RACK-A host=HOST-2 device=0 tier=LEAF\n"
      "n3 site=SITE rack=RACK-B host=HOST-3 device=0 tier=LEAF\n"
      "s0 site=SITE pod=POD-0 rack=RACK-SPINE host=SPINE-0 device=0 tier=SPINE\n"
      "\n"
      "[edges]\n"
      "a0 from=n0 to=s0 capacity=25000 latency=100 tier=LEAF domain=HOST-0 evidence=synthetic\n"
      "a1 from=s0 to=n0 capacity=25000 latency=100 tier=LEAF domain=HOST-0 evidence=synthetic\n"
      "a2 from=n1 to=s0 capacity=25000 latency=100 tier=LEAF domain=HOST-1 evidence=synthetic\n"
      "a3 from=s0 to=n1 capacity=25000 latency=100 tier=LEAF domain=HOST-1 evidence=synthetic\n"
      "a4 from=n2 to=s0 capacity=25000 latency=100 tier=LEAF domain=HOST-2 evidence=synthetic\n"
      "a5 from=s0 to=n2 capacity=25000 latency=100 tier=LEAF domain=HOST-2 evidence=synthetic\n"
      "a6 from=n3 to=s0 capacity=25000 latency=100 tier=LEAF domain=HOST-3 evidence=synthetic\n"
      "a7 from=s0 to=n3 capacity=25000 latency=100 tier=LEAF domain=HOST-3 evidence=synthetic\n"
      "\n"
      "[bindings]\n"
      "p0 node=n0\n"
      "p1 node=n1\n"
      "p2 node=n2\n"
      "p3 node=n3\n"
      "\n"
      "[policy]\n"
      "max-hops=4\n"
      "paths-per-logical-edge=1\n"
      "disjointness=none\n"
      "latency-weight-milli=1000\n"
      "congestion-weight-milli=250\n");
}

}  // namespace

int main() {
  std::cout << cpath::build_summary() << "\n";
  std::cout << "PROOF LABEL: SYNTHETIC fabric (no device was measured)\n\n";

  auto request = cpath::parse_request_text(synthetic_request_text());
  if (!request.has_value()) {
    std::cerr << "request rejected: " << request.status().to_string() << "\n";
    return 1;
  }
  std::cout << "canonical request digest " << request.value().canonical_digest.hex() << "\n";
  std::cout << "collective " << request.value().collective.id.value() << " with "
            << request.value().collective.logical_edges.size() << " logical edges, fabric with "
            << request.value().fabric.node_count() << " nodes and " << request.value().fabric.edge_count()
            << " directed edges\n\n";

  const cpath::PlanningOutcome outcome = cpath::plan_collective(request.value());
  if (!outcome.ok()) {
    std::cout << cpath::explain_denials(outcome);
    return 1;
  }
  std::cout << cpath::explain_plan(*outcome.plan, &request.value());
  std::cout << "\nsearch expansions: " << outcome.search_expansions << "\n";

  // Replanning under identical canonical inputs must reproduce the same plan.
  const cpath::PlanningOutcome again = cpath::plan_collective(request.value());
  if (!again.ok() || !(again.plan->body_digest() == outcome.plan->body_digest())) {
    std::cerr << "determinism check failed\n";
    return 1;
  }
  std::cout << "determinism: replanning produced identical plan bytes\n";
  return 0;
}
