// Collective Path Planner example: durable plan records for audit, and the
// explicit staleness of a reopened plan.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
//
// PROOF LABEL: SYNTHETIC. The fabric is generated by this program.

#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <iostream>
#include <string>

#include "cpath/dsl.hpp"
#include "cpath/explain.hpp"
#include "cpath/persistence.hpp"
#include "cpath/planner.hpp"

namespace {

std::string request_text(std::uint64_t topology_generation) {
  return std::string(
             "cpath-request 1\n"
             "plan-generation 1\n"
             "topology-generation ") +
         std::to_string(topology_generation) +
         "\n"
         "failure-domain-generation 2\n"
         "capacity-evidence-generation 3\n"
         "policy-generation 1\n"
         "\n"
         "[collective]\n"
         "id=audit kind=ring\n"
         "\n"
         "[groups]\n"
         "g0 level=0 pattern=ring members=p0,p1,p2\n"
         "\n"
         "[domains]\n"
         "SITE kind=site\n"
         "RACK kind=rack parent=SITE\n"
         "\n"
         "[nodes]\n"
         "n0 site=SITE rack=RACK host=H0 device=0 tier=LEAF\n"
         "n1 site=SITE rack=RACK host=H1 device=0 tier=LEAF\n"
         "n2 site=SITE rack=RACK host=H2 device=0 tier=LEAF\n"
         "\n"
         "[edges]\n"
         "e0 from=n0 to=n1 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
         "e1 from=n1 to=n2 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
         "e2 from=n2 to=n0 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
         "e3 from=n1 to=n0 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
         "e4 from=n2 to=n1 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
         "e5 from=n0 to=n2 capacity=10000 latency=100 tier=LEAF domain=RACK evidence=synthetic\n"
         "\n"
         "[bindings]\n"
         "p0 node=n0\n"
         "p1 node=n1\n"
         "p2 node=n2\n"
         "\n"
         "[policy]\n"
         "max-hops=4\n"
         "paths-per-logical-edge=1\n";
}

// Reads an environment variable without touching the deprecated CRT accessor.
std::string environment_value(const char* name) {
#ifdef _WIN32
  char* buffer = nullptr;
  std::size_t size = 0;
  if (::_dupenv_s(&buffer, &size, name) != 0 || buffer == nullptr) {
    return std::string();
  }
  const std::string value(buffer);
  std::free(buffer);
  return value;
#else
  const char* value = std::getenv(name);
  return value != nullptr ? std::string(value) : std::string();
#endif
}

// A fixed scratch path, cleared before use and removed afterwards, so that
// running this example repeatedly never accumulates directories on the host.
std::string store_path() {
#ifdef _WIN32
  const std::string root = environment_value("TEMP").empty() ? std::string(".") : environment_value("TEMP");
  const char separator = '\\';
#else
  const std::string root = environment_value("TMPDIR").empty() ? std::string("/tmp") : environment_value("TMPDIR");
  const char separator = '/';
#endif
  return root + separator + "cpath-example-store";
}

}  // namespace

int main() {
  std::cout << "PROOF LABEL: SYNTHETIC fabric (no device was measured)\n\n";

  auto request = cpath::parse_request_text(request_text(31));
  if (!request.has_value()) {
    std::cerr << "request rejected: " << request.status().to_string() << "\n";
    return 1;
  }
  const cpath::PlanningOutcome outcome = cpath::plan_collective(request.value());
  if (!outcome.ok()) {
    std::cerr << cpath::explain_denials(outcome);
    return 1;
  }
  const cpath::Plan& plan = *outcome.plan;
  std::cout << "planned " << plan.id.value().hex() << " with " << plan.stats.path_count << " paths\n";

  const std::string store_root = store_path();
  std::error_code cleanup_error;
  std::filesystem::remove_all(store_root, cleanup_error);
  cpath::StoreConfig config;
  config.root = store_root;

  {
    cpath::PlanStore store(config);
    if (cpath::Status status = store.open(); !status.is_ok()) {
      std::cerr << "store open failed: " << status.to_string() << "\n";
      return 1;
    }
    auto stored = store.put(plan, request.value());
    if (!stored.has_value()) {
      std::cerr << "store put failed: " << stored.status().to_string() << "\n";
      return 1;
    }
    std::cout << "committed record of " << stored.value().record_bytes << " bytes under incarnation "
              << store.incarnation().value() << "\n";
    store.close();
  }

  // Reopen in a fresh incarnation: nothing read back is authoritative yet.
  cpath::PlanStore reopened(config);
  if (cpath::Status status = reopened.open(); !status.is_ok()) {
    std::cerr << "store reopen failed: " << status.to_string() << "\n";
    return 1;
  }
  auto loaded = reopened.get(cpath::CollectivePlanId{plan.id.value()});
  if (!loaded.has_value()) {
    std::cerr << "store get failed: " << loaded.status().to_string() << "\n";
    return 1;
  }
  std::cout << "reopened plan under incarnation " << reopened.incarnation().value()
            << "; it is NOT current until revalidated\n";

  auto revalidated = reopened.revalidate(cpath::CollectivePlanId{plan.id.value()}, request.value());
  if (!revalidated.has_value()) {
    std::cerr << "revalidate failed: " << revalidated.status().to_string() << "\n";
    return 1;
  }
  std::cout << "revalidation: still-valid=" << (revalidated.value().still_valid ? "yes" : "no")
            << " freshness=" << cpath::to_string(revalidated.value().freshness) << "\n";
  std::cout << "  " << revalidated.value().detail << "\n";

  // Now change only the topology generation and revalidate again: the stored
  // plan must be reported stale, and a plan for the new inputs must differ.
  auto newer = cpath::parse_request_text(request_text(32));
  if (!newer.has_value()) {
    std::cerr << "second request rejected: " << newer.status().to_string() << "\n";
    return 1;
  }
  auto stale = reopened.revalidate(cpath::CollectivePlanId{plan.id.value()}, newer.value());
  if (!stale.has_value()) {
    std::cerr << "revalidate failed: " << stale.status().to_string() << "\n";
    return 1;
  }
  std::cout << "after a topology generation change: still-valid="
            << (stale.value().still_valid ? "yes" : "no")
            << " freshness=" << cpath::to_string(stale.value().freshness) << "\n";
  if (stale.value().still_valid) {
    std::cerr << "a plan whose topology generation changed was reported current\n";
    return 1;
  }
  reopened.close();

  std::error_code ignored;
  std::filesystem::remove_all(store_root, ignored);
  std::cout << "scratch store removed: " << store_root << "\n";
  return 0;
}
