// Collective Path Planner - physical fabric graph model.
//
// Copyright 2026 Summon Software Labs.
// Licensed under the Apache License, Version 2.0 (see LICENSE).
#ifndef CPATH_FABRIC_HPP
#define CPATH_FABRIC_HPP

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

#include "cpath/buffer.hpp"
#include "cpath/digest.hpp"
#include "cpath/ids.hpp"
#include "cpath/limits.hpp"
#include "cpath/status.hpp"

namespace cpath {

// Provenance label for every piece of capability evidence in the model. The
// library never upgrades kUnknown into positive evidence.
enum class EvidenceClass : std::uint8_t {
  kUnknown = 0,    // no evidence; capacity/eligibility are not established
  kSynthetic = 1,  // generated by a model or a test fixture, not measured
  kMeasured = 2,   // observed on real devices by an adjacent authority
};

const char* to_string(EvidenceClass value) noexcept;
bool parse_evidence_class(std::string_view text, EvidenceClass& out) noexcept;

// Position of a failure domain in the containment hierarchy. Narrower kinds are
// strictly contained by broader kinds.
enum class DomainKind : std::uint8_t {
  kDevice = 0,
  kHost = 1,
  kRack = 2,
  kPod = 3,
  kSite = 4,
};

const char* to_string(DomainKind value) noexcept;
bool parse_domain_kind(std::string_view text, DomainKind& out) noexcept;

// Physical placement of a node across the GPU/host/rack/pod/site abstraction.
// Labels are opaque; an empty label means "not supplied at this level".
struct Placement {
  std::string site{};
  std::string pod{};
  std::string rack{};
  std::string host{};
  std::uint32_t device_index{0};
  bool supplied{false};

  friend bool operator==(const Placement&, const Placement&) = default;
};

struct Node {
  NodeId id{};
  Placement placement{};
  TierId tier{};       // invalid when the input declared no tier
  bool eligible{true}; // declared eligibility; NOT authority to carry traffic

  friend bool operator==(const Node&, const Node&) = default;
};

struct FailureDomain {
  FailureDomainId id{};
  FailureDomainId parent{};  // invalid for a root domain
  DomainKind kind{DomainKind::kDevice};

  friend bool operator==(const FailureDomain&, const FailureDomain&) = default;
};

struct Edge {
  EdgeId id{};
  NodeId from{};
  NodeId to{};
  // Verified forwarding capacity. Zero means "no verified capacity", which is
  // not the same as "usable at zero cost".
  std::uint64_t capacity_mbps{0};
  std::uint64_t latency_micros{0};
  // Capacity already committed by an adjacent authority. Never owned here.
  std::uint64_t reserved_mbps{0};
  TierId tier{};
  FailureDomainId failure_domain{};
  EvidenceClass evidence{EvidenceClass::kUnknown};
  bool eligible{true};

  friend bool operator==(const Edge&, const Edge&) = default;
};

inline constexpr std::uint32_t kInvalidIndex = 0xFFFFFFFFu;

// Unvalidated input description of a fabric. Build a FabricGraph from it.
struct FabricSpec {
  TopologyGeneration topology_generation{};
  FailureDomainGeneration failure_domain_generation{};
  CapacityEvidenceGeneration capacity_evidence_generation{};
  std::vector<FailureDomain> failure_domains{};
  std::vector<Node> nodes{};
  std::vector<Edge> edges{};
};

// Validated, canonicalised fabric graph.
//
// Canonical form: failure domains ordered by id, nodes ordered by id, edges
// ordered by (from, to, id). Node indices in the adjacency lists therefore
// depend only on the canonical node order, which depends only on node ids.
class FabricGraph {
 public:
  FabricGraph() = default;

  static Result<FabricGraph> build(const FabricSpec& spec);
  static Result<FabricGraph> build(FabricSpec&& spec);

  const TopologyGeneration& topology_generation() const noexcept { return topology_generation_; }
  const FailureDomainGeneration& failure_domain_generation() const noexcept { return failure_domain_generation_; }
  const CapacityEvidenceGeneration& capacity_evidence_generation() const noexcept { return capacity_evidence_generation_; }

  const std::vector<FailureDomain>& failure_domains() const noexcept { return failure_domains_; }
  const std::vector<Node>& nodes() const noexcept { return nodes_; }
  const std::vector<Edge>& edges() const noexcept { return edges_; }

  std::size_t node_count() const noexcept { return nodes_.size(); }
  std::size_t edge_count() const noexcept { return edges_.size(); }

  const Node* find_node(const NodeId& id) const noexcept;
  const Edge* find_edge(const EdgeId& id) const noexcept;
  const FailureDomain* find_failure_domain(const FailureDomainId& id) const noexcept;
  std::uint32_t node_index(const NodeId& id) const noexcept;

  // Outgoing edges of a node in canonical edge order.
  const std::vector<std::uint32_t>& out_edges(std::uint32_t node_index) const noexcept;

  // Containment chain from the given domain to its root, self first. Bounded by
  // kMaxHierarchyLevels; a domain whose chain is longer is rejected at build
  // time, so this never cycles.
  const std::vector<FailureDomainId>& domain_chain(const FailureDomainId& id) const noexcept;

  // True when candidate is equal to ancestor or contained by it.
  bool domain_contains(const FailureDomainId& ancestor, const FailureDomainId& candidate) const noexcept;

  // Bytes appended to the canonical request encoding.
  void encode_canonical(ByteWriter& writer) const;

  // Structural re-check used by tests, persistence and revalidation.
  Status validate() const;

 private:
  TopologyGeneration topology_generation_{};
  FailureDomainGeneration failure_domain_generation_{};
  CapacityEvidenceGeneration capacity_evidence_generation_{};
  std::vector<FailureDomain> failure_domains_{};
  std::vector<Node> nodes_{};
  std::vector<Edge> edges_{};

  std::vector<std::vector<std::uint32_t>> out_edges_{};
  std::vector<std::vector<FailureDomainId>> domain_chains_{};
  IdMap<NodeId> node_index_{};
  IdMap<EdgeId> edge_index_{};
  IdMap<FailureDomainId> domain_index_{};

  void rebuild_index();
};

// Text decoding/encoding of the fabric section of the request DSL. Declared
// here, implemented with the rest of the reader in src/dsl.cpp.
std::string encode_fabric_section(const FabricGraph& fabric);

}  // namespace cpath

#endif  // CPATH_FABRIC_HPP
